### ISSUE TITLE
Auto timestamp lastUpdated not working with Java8 time during updateAll

### ISSUE THREAD

**Issue by andersb** [grails/grails-data-mapping#1003]
I'm not sure if this can be considered a bug or feature request.
The documentation clearly shows the use of Date for auto timestamps.
However, using for instance LocaleDateTime will work as well for the most parts but not all.

### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create an entity and declare property LocalDateTime lastUpdated
2. Save an instance of the entity
3. Perform a batch update like the on described in the documentation

````
DetachedCriteria<Person> query = Person.where {
    lastName == 'Simpson'
}
int total = query.updateAll(lastName:"Bloggs")
````

### Expected Behaviour

The update should succeed

### Actual Behaviour

Exception like below.
And the reason is that Date() is hard coded into this line

HibernateSession#updateAll
properties.put(GormProperties.LAST_UPDATED, new Date());

````
java.lang.ClassCastException: java.util.Date cannot be cast to java.time.LocalDateTime
	at org.hibernate.type.descriptor.java.LocalDateTimeJavaDescriptor.unwrap(LocalDateTimeJavaDescriptor.java:25)
	at org.hibernate.type.descriptor.sql.TimestampTypeDescriptor$1.doBind(TimestampTypeDescriptor.java:48)
	at org.hibernate.type.descriptor.sql.BasicBinder.bind(BasicBinder.java:74)
	at org.hibernate.type.AbstractStandardBasicType.nullSafeSet(AbstractStandardBasicType.java:253)
	at org.hibernate.type.AbstractStandardBasicType.nullSafeSet(AbstractStandardBasicType.java:248)
	at org.hibernate.param.NamedParameterSpecification.bind(NamedParameterSpecification.java:52)
	at org.hibernate.hql.internal.ast.exec.BasicExecutor.doExecute(BasicExecutor.java:83)
	at org.hibernate.hql.internal.ast.exec.BasicExecutor.execute(BasicExecutor.java:60)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.executeUpdate(QueryTranslatorImpl.java:429)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performExecuteUpdate(HQLQueryPlan.java:374)
	at org.hibernate.internal.SessionImpl.executeUpdate(SessionImpl.java:1361)
	at org.hibernate.internal.QueryImpl.executeUpdate(QueryImpl.java:102)
	at org.grails.orm.hibernate.HibernateSession$2.doInHibernate(HibernateSession.java:145)
	at org.grails.orm.hibernate.HibernateSession$2.doInHibernate(HibernateSession.java:121)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.doExecute(GrailsHibernateTemplate.java:298)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.execute(GrailsHibernateTemplate.java:242)
	at org.grails.orm.hibernate.HibernateSession.updateAll(HibernateSession.java:121)
	at grails.gorm.DetachedCriteria.updateAll_closure7(DetachedCriteria.groovy:570)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at org.grails.datastore.gorm.GormStaticApi.withDatastoreSession_closure22(GormStaticApi.groovy:823)
	at groovy.lang.Closure.call(Closure.java:414)
	at org.grails.datastore.mapping.core.DatastoreUtils.execute(DatastoreUtils.java:319)
	at org.grails.datastore.gorm.AbstractDatastoreApi.execute(AbstractDatastoreApi.groovy:40)
	at org.grails.datastore.gorm.GormStaticApi.withDatastoreSession(GormStaticApi.groovy:822)
	at grails.gorm.DetachedCriteria.updateAll(DetachedCriteria.groovy:569)

````

### Environment Information

- **Operating System**: Windows 10
- **GORM Version:** 6.1.4
- **Grails Version (if using Grails):** 3.2.9
- **JDK Version:** 1.8.0_131

**Comment by jameskleeh** [comment]
Fixed by https://github.com/grails/gorm-hibernate5/commit/010bd48adde1af6d388bbb79dd5467b9862347b4
