### ISSUE TITLE
DetachedCriteria eq restriction on hasOne association throws SQLException

### ISSUE THREAD

**Issue by zyro23** [grails/grails-data-mapping#1004]
the exception below is also thrown if you validate a domain class (e.g. implicitly by using it as a controller action parameter) that has a unique constraint on a hasOne association property.

ref. https://github.com/grails/grails-data-mapping/blob/v6.1.7/grails-datastore-gorm/src/main/groovy/org/grails/datastore/gorm/validation/constraints/builtin/UniqueConstraint.groovy#L75

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. run sample app test

### Expected Behaviour

`notThrown Exception`

### Actual Behaviour

```
2017-09-23 14:11:33.948 ERROR --- [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : Parameter "#2" is not set
Parameter "#2" is not set; SQL statement:
select this_.id as id1_0_0_, this_.version as version2_0_0_ from child this_ where this_.id=? limit ? [90012-196]

Expected no exception of type 'java.lang.Exception' to be thrown, but got it nevertheless

	at spock.lang.Specification.notThrown(Specification.java:107)
	at myapp.DetachedCriteriaHasOneEqIntegrationSpec.test a detachedCriteria eq query on a hasOne association(DetachedCriteriaHasOneEqIntegrationSpec.groovy:23)
Caused by: org.hibernate.exception.GenericJDBCException: could not extract ResultSet
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:111)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:97)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:79)
	at org.hibernate.loader.Loader.getResultSet(Loader.java:2122)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1905)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1881)
	at org.hibernate.loader.Loader.doQuery(Loader.java:925)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:342)
	at org.hibernate.loader.Loader.doList(Loader.java:2622)
	at org.hibernate.loader.Loader.doList(Loader.java:2605)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2434)
	at org.hibernate.loader.Loader.list(Loader.java:2429)
	at org.hibernate.loader.criteria.CriteriaLoader.list(CriteriaLoader.java:109)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1787)
	at org.hibernate.internal.CriteriaImpl.list(CriteriaImpl.java:363)
	at org.grails.orm.hibernate.query.AbstractHibernateQuery.singleResultViaListCall(AbstractHibernateQuery.java:804)
	at org.grails.orm.hibernate.query.AbstractHibernateQuery.singleResult(AbstractHibernateQuery.java:791)
	at grails.gorm.DetachedCriteria.get_closure1(DetachedCriteria.groovy:115)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at grails.gorm.DetachedCriteria.withPopulatedQuery_closure8(DetachedCriteria.groovy:766)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at org.grails.datastore.gorm.GormStaticApi.withDatastoreSession_closure22(GormStaticApi.groovy:836)
	at groovy.lang.Closure.call(Closure.java:414)
	at org.grails.datastore.mapping.core.DatastoreUtils.execute(DatastoreUtils.java:319)
	at org.grails.datastore.gorm.AbstractDatastoreApi.execute(AbstractDatastoreApi.groovy:40)
	at org.grails.datastore.gorm.GormStaticApi.withDatastoreSession(GormStaticApi.groovy:835)
	at grails.gorm.DetachedCriteria.withPopulatedQuery(DetachedCriteria.groovy:737)
	at grails.gorm.DetachedCriteria.get(DetachedCriteria.groovy:114)
	at grails.gorm.DetachedCriteria.get(DetachedCriteria.groovy:113)
	at myapp.DetachedCriteriaHasOneEqIntegrationSpec.test a detachedCriteria eq query on a hasOne association_closure2(DetachedCriteriaHasOneEqIntegrationSpec.groovy:17)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)
	at org.grails.datastore.gorm.GormStaticApi.withTransaction(GormStaticApi.groovy:988)
	at org.grails.datastore.gorm.GormStaticApi.withTransaction(GormStaticApi.groovy:851)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.withTransaction(GormEntity.groovy:920)
	at myapp.DetachedCriteriaHasOneEqIntegrationSpec.test a detachedCriteria eq query on a hasOne association(DetachedCriteriaHasOneEqIntegrationSpec.groovy:16)
Caused by: org.h2.jdbc.JdbcSQLException: Parameter "#2" is not set
Parameter "#2" is not set; SQL statement:
select this_.id as id1_0_0_, this_.version as version2_0_0_ from child this_ where this_.id=? limit ? [90012-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.Parameter.checkSet(Parameter.java:81)
	at org.h2.command.Prepared.checkParameters(Prepared.java:164)
	at org.h2.command.CommandContainer.query(CommandContainer.java:112)
	at org.h2.command.Command.executeQuery(Command.java:201)
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:111)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:70)
	... 38 more
```

### Environment Information

- **Operating System**: win x64
- **GORM Version:** 6.1.7
- **Grails Version (if using Grails):** 3.3.1
- **JDK Version:** oracle 8u131

### Example Application

will be referenced in a minute

**Comment by jameskleeh** [comment]
You can't use `eq` with a null value in any of the database implementations I can think of. You must use `isNull`.

I've submitted a PR that causes the test to pass.

https://github.com/zyro23/grails-data-mapping-1004/compare/master...jameskleeh:patch-1

**Comment by zyro23** [comment]
got your point, thx for the pr! but did you take a look at the `UniqueConstraint` code referenced? that uses `eq propertyValue` no matter if it is null or not?

**Comment by jameskleeh** [comment]
@zyro23 Submit an example application that demonstrates it fails with the same exception and I'll fix it

**Comment by zyro23** [comment]
the new sample app contains in `BootStrap`:
* one example covering the referenced grails-core issue description (`Face`/`Nose`/`Monkey`)
* one example demonstrating the issue with a hasOne association (`Foo`/`Bar`)
