### ISSUE TITLE
[6.1.7] LazyInitializationException when updating MultiTenant domain after upgrade to Grails 3.3.1

### ISSUE THREAD

**Issue by andersb** [grails/grails-data-mapping#1011]
Updating a domain with a parent will cause org.hibernate.LazyInitializationException on the parent domain but only for MultiTenant domains.

Both tests works when using Grails 3.2.8.

### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Run integration test on attached project

### Expected Behaviour

Both tests should pass

### Actual Behaviour

Test for updating domain in tenant db fails

````

org.springframework.orm.hibernate5.HibernateSystemException: failed to lazily initialize a collection of role: se.demo.plugin.clientdb.TenantParent.tenantChild1s, could not initialize proxy - no Session; nested exception is org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: se.demo.plugin.clientdb.TenantParent.tenantChild1s, could not initialize proxy - no Session

	at org.springframework.orm.hibernate5.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:296)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.convertHibernateAccessException(GrailsHibernateTemplate.java:724)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.doExecute(GrailsHibernateTemplate.java:303)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.execute(GrailsHibernateTemplate.java:243)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.executeWithNewSession(GrailsHibernateTemplate.java:150)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.executeWithExistingOrCreateNewSession(GrailsHibernateTemplate.java:209)
	at org.grails.orm.hibernate.AbstractHibernateDatastore.withNewSession(AbstractHibernateDatastore.java:362)
	at grails.gorm.multitenancy.Tenants.withId_closure1(Tenants.groovy:222)
	at grails.gorm.multitenancy.Tenants$CurrentTenant.withTenant(Tenants.groovy:322)
	at grails.gorm.multitenancy.Tenants.withId(Tenants.groovy:200)
	at org.grails.datastore.gorm.services.DefaultTenantService.withCurrent(DefaultTenantService.groovy:71)
	at se.demo.plugin.IntegrationSpec.$tt__$spock_feature_0_1(IntegrationSpec.groovy:75)
	at se.demo.plugin.IntegrationSpec.test update in tenant db_closure2(IntegrationSpec.groovy)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at grails.gorm.transactions.GrailsTransactionTemplate$1.doInTransaction(GrailsTransactionTemplate.groovy:68)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at grails.gorm.transactions.GrailsTransactionTemplate.executeAndRollback(GrailsTransactionTemplate.groovy:65)
	at se.demo.plugin.IntegrationSpec.test update in tenant db(IntegrationSpec.groovy)
Caused by: org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: se.demo.plugin.clientdb.TenantParent.tenantChild1s, could not initialize proxy - no Session
	at org.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:584)
	at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:201)
	at org.hibernate.collection.internal.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:563)
	at org.hibernate.collection.internal.AbstractPersistentCollection.read(AbstractPersistentCollection.java:132)
	at org.hibernate.collection.internal.PersistentSet.iterator(PersistentSet.java:163)
	at grails.gorm.validation.PersistentEntityValidator.cascadeValidationToMany(PersistentEntityValidator.groovy:165)
	at grails.gorm.validation.PersistentEntityValidator.cascadeToAssociativeProperty(PersistentEntityValidator.groovy:130)
	at grails.gorm.validation.PersistentEntityValidator.cascadeValidationToOne(PersistentEntityValidator.groovy:251)
	at grails.gorm.validation.PersistentEntityValidator.cascadeToAssociativeProperty(PersistentEntityValidator.groovy:114)
	at grails.gorm.validation.PersistentEntityValidator.validate(PersistentEntityValidator.groovy:79)
	at org.grails.orm.hibernate.AbstractHibernateGormInstanceApi.save(AbstractHibernateGormInstanceApi.groovy:123)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.save(GormEntity.groovy:151)
	at se.demo.plugin.clientdb.TenantChild2Service.$tt__save(TenantChild2Service.groovy:11)
	at se.demo.plugin.clientdb.TenantChild2Service._mt__save_closure2(TenantChild2Service.groovy)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)
	at se.demo.plugin.clientdb.TenantChild2Service.save_closure1(TenantChild2Service.groovy)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at grails.gorm.multitenancy.Tenants.withId_closure1$_closure3(Tenants.groovy:229)
	at org.grails.orm.hibernate.GrailsHibernateTemplate$1.doInHibernate(GrailsHibernateTemplate.java:153)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.doExecute(GrailsHibernateTemplate.java:299)
	... 16 more

````

### Environment Information

- **Operating System**: Windows 10
- **GORM Version:** 6.1.4 and 6.1.7
- **Grails Version (if using Grails):** 3.3.1
- **JDK Version:** 1.8.0

### Example Application

[multi-tenancy-demo-plugin.zip](https://github.com/grails/grails-data-mapping/files/1363112/multi-tenancy-demo-plugin.zip)

**Comment by andersb** [comment]
I just realized this might actually be a duplicate of #1005

**Comment by jameskleeh** [comment]
Confirmed this duplicates #1005 . In the future, please create example applications that don't have external dependencies (postgres in this example). It just adds time to the process.
