### ISSUE TITLE
Problem Testing Data Services

### ISSUE THREAD

**Issue by jeffbrown** [grails/grails-data-mapping#1020]
See https://github.com/jeffbrown/servicetestproblem

Domain:

```groovy
package servicetestproblem

class Person {
    String name
}
```

Data Service:

```groovy
package servicetestproblem

import grails.gorm.services.Service

@Service(Person)
abstract class PersonService {
    abstract List<Person> list()
}
```

Unit test:

```groovy
package servicetestproblem

import grails.testing.gorm.DataTest
import grails.testing.services.ServiceUnitTest
import spock.lang.Specification

class PersonServiceSpec extends Specification implements ServiceUnitTest<PersonService>, DataTest {

    def setupSpec() {
        mockDomain Person
    }

    void 'first test'() {
        expect:
        service.list().size() == 0
    }

    void 'second test'() {
        expect:
        service.list().size() == 0
    }
}
```

There is no reason to have a unit test like that of course but this is a simple example that demonstrates the problem.  The second test method will fail with the following:

```
Condition failed with Exception:

service.list().size() == 0
|
java.lang.reflect.InvocationTargetException

	at servicetestproblem.PersonServiceSpec.second test(PersonServiceSpec.groovy:20)
Caused by: java.lang.reflect.InvocationTargetException
	at grails.testing.services.ServiceUnitTest$Trait$Helper.mockArtefact(ServiceUnitTest.groovy:66)
	at org.grails.testing.ParameterizedGrailsUnitTest$Trait$Helper.getArtefactInstance(ParameterizedGrailsUnitTest.groovy:48)
	at grails.testing.services.ServiceUnitTest$Trait$Helper.getService(ServiceUnitTest.groovy:83)
	... 1 more
Caused by: java.lang.IllegalStateException: Could not register object [servicetestproblem.$PersonServiceImplementation@42339ea2] under bean name 'personService': there is already object [servicetestproblem.$PersonServiceImplementation@42339ea2] bound
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.registerSingleton(DefaultSingletonBeanRegistry.java:130)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.registerSingleton(DefaultListableBeanFactory.java:936)
	at grails.testing.gorm.DataTest$Trait$Helper.mockDataService(DataTest.groovy:101)
	... 4 more
```

**Comment by jeffbrown** [comment]
I haven't investigated to know if this is a GORM problem or a problem with https://github.com/grails/grails-testing-support.

**Comment by jeffbrown** [comment]
Moving to https://github.com/grails/grails-testing-support/issues/18
