### ISSUE TITLE
NPE in HibernateMappingContext when using a CustomTypeMarshaller 

### ISSUE THREAD

**Issue by longwa** [grails/grails-data-mapping#1092]
If you configure a custom type marshaller using:
```
grails.gorm.custom.types = [new MyTypeMarshaller(Foo)]
```
Construction of the `HibernateMappingContext` will fail in `AbstractMappingContext` with:

```
java.lang.NullPointerException
	at org.grails.datastore.mapping.model.AbstractMappingContext.initialize(AbstractMappingContext.java:98)
	at org.grails.datastore.mapping.model.AbstractMappingContext.<init>(AbstractMappingContext.java:81)
	at org.grails.orm.hibernate.cfg.HibernateMappingContext.<init>(HibernateMappingContext.java:59)
	at org.grails.orm.hibernate.cfg.HibernateMappingContext.<init>(HibernateMappingContext.java:82)
	at org.grails.orm.hibernate.cfg.HibernateMappingContextSpec.test entity with custom type marshaller is registered correctly(HibernateMappingContextSpec.groovy:31)
```

The problem is caused by the `HibernateMappingContext` constructor. It calls `super` before setting the `mappingFactory`, however, the factory is required in the `initialize()` call made in `AbstractMappingContext`.

It looks like `AbstractMappingContext` was designed to allow initialize to be called directly. The simplest solution is to skip the call to `super()`, setup the `mappingFactory` and then call `initialize(settings)` directly from `HibernateMappingContext`.

I will submit a PR with a `HibernateMappingContextSpec` feature that demonstrates and verifies the solution.

### Expected Behaviour
You should be able to create a HibernateMappingFactory with custom type marshalers registered

### Actual Behaviour
NPE trying to use the mappingFactory to register custom types

### Environment Information
GORM 6.1.9
Grails 3.3.5

**Comment by graemerocher** [comment]
Thanks!
