### ISSUE TITLE
failed to lazily initialize a collection, no session or session was closed

### ISSUE THREAD

**Issue by demon101** [grails/grails-data-mapping#1096]
During upgrade to Grails 3.3.5 with GORM 6.1.9 I got error during data initialisation. I will try to reproduce it in small project soon.  

### Task List

- [ ] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

**hibernateDirtyChecking:true**, **flush.mode: AUTO**
We are using old dirty checking becouse of bug in new version (issue will be created soon)

In bootstrap I got following exception. 

> org.hibernate.LazyInitializationException: failed to lazily initialize a collection, no session or session was closed
> 	at org.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:584)
> 	at org.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationExceptionIfNotConnected(AbstractPersistentCollection.java:576)
> 	at org.hibernate.collection.internal.AbstractPersistentCollection.access$200(AbstractPersistentCollection.java:55)
> 	at org.hibernate.collection.internal.AbstractPersistentCollection$1.doWork(AbstractPersistentCollection.java:165)
> 	at org.hibernate.collection.internal.AbstractPersistentCollection$1.doWork(AbstractPersistentCollection.java:146)
> 	at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:249)
> 	at org.hibernate.collection.internal.AbstractPersistentCollection.readSize(AbstractPersistentCollection.java:145)
> 	at org.hibernate.collection.internal.PersistentBag.size(PersistentBag.java:261)
> 	at org.codehaus.groovy.runtime.DefaultGroovyMethods.equals(DefaultGroovyMethods.java:11743)
> 	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.compareEqual(DefaultTypeTransformation.java:649)
> 	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.compareEqual(ScriptBytecodeAdapter.java:697)
> 	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.compareNotEqual(ScriptBytecodeAdapter.java:701)
> 	at org.grails.datastore.mapping.dirty.checking.DirtyCheckable$Trait$Helper.markDirty(DirtyCheckable.groovy:81)
> 	at org.grails.datastore.mapping.dirty.checking.DirtyCheckable$Trait$Helper$markDirty.call(Unknown Source)
> 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
> 	at org.grails.datastore.mapping.dirty.checking.DirtyCheckable$Trait$Helper$markDirty.call(Unknown Source)
> 	at com.x.notification.NotificationList.markDirty(NotificationList.groovy)
> 	at com.x.notification.NotificationList.setEmailAddresses(NotificationList.groovy)

```
class NotificationList {
    Collection<EmailAddress> emailAddresses
    static hasMany = [emailAddresses: EmailAddress]
}

class EmailAddress {
    String address

    static belongsTo = [notificationList : NotificationList]

    static constraints = {
        address nullable: false
    }

    static mapping = {
        sort "address"
    }
}

.............
def l = new NotificationList()
l.emailAddresses = [new EmailAddress(address: 'mailto36@me.com')]
l.save()
```

With new dirty checking (**hibernateDirtyChecking:false**) happens at another place also for one-to-many relation

> org.hibernate.LazyInitializationException: failed to lazily initialize a collection, no session or session was closed
> 	at org.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:584)
> 	at org.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationExceptionIfNotConnected(AbstractPersistentCollection.java:576)
> 	at org.hibernate.collection.internal.AbstractPersistentCollection.access$200(AbstractPersistentCollection.java:55)
> 	at org.hibernate.collection.internal.AbstractPersistentCollection$1.doWork(AbstractPersistentCollection.java:165)
> 	at org.hibernate.collection.internal.AbstractPersistentCollection$1.doWork(AbstractPersistentCollection.java:146)
> 	at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:249)
> 	at org.hibernate.collection.internal.AbstractPersistentCollection.readSize(AbstractPersistentCollection.java:145)
> 	at org.hibernate.collection.internal.PersistentSet.size(PersistentSet.java:143)
> 	at org.codehaus.groovy.runtime.DefaultGroovyMethods.equals(DefaultGroovyMethods.java:11795)
> 	at org.codehaus.groovy.runtime.dgm$184.doMethodInvoke(Unknown Source)
> 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
> 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
> 	at org.codehaus.groovy.runtime.InvokerHelper.invokePojoMethod(InvokerHelper.java:935)
> 	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:926)
> 	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.compareEqual(DefaultTypeTransformation.java:662)
> 	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.compareEqual(ScriptBytecodeAdapter.java:697)
> 	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.compareNotEqual(ScriptBytecodeAdapter.java:701)
> 	at org.grails.datastore.mapping.dirty.checking.DirtyCheckable$Trait$Helper.markDirty(DirtyCheckable.groovy:81)
> 	at org.grails.datastore.mapping.dirty.checking.DirtyCheckable$Trait$Helper$markDirty.call(Unknown Source)
> 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
> 	at org.grails.datastore.mapping.dirty.checking.DirtyCheckable$Trait$Helper$markDirty.call(Unknown Source)
> 	at com.x.company.Branch.markDirty(Branch.groovy)
> 	at com.x.company.Branch.setWorkCenters(Branch.groovy)

### Environment Information

- **Operating System**: Ubuntu
- **GORM Version:** 6.1.9
- **Grails Version (if using Grails):** 3.3.5
- **JDK Version:** oracle 8.152

### Example Application

- TODO: link to github repository with example that reproduces the issue

**Comment by demon101** [comment]
hm, can't reproduce in simple app.

Looks like problem with creating-updating in different transactions

**Comment by demon101** [comment]
I think this issue is duplicate of #1210
