### ISSUE TITLE
Multi Tenancy with schema mode an PostgreSQL DB throwns an error because executes an incorrect sql command

### ISSUE THREAD

**Issue by xavier-gallofre** [grails/grails-data-mapping#1148]
Issue implementing Multi Tenancy with schema mode an PostgreSQL DB. The project is working with h2 DB but is not working with postgreSQL DB.
The problem is related with how gorm is switching the schema with MultiTenancy

### Problem

The web app is configured with Multi Tenancy in `SCHEMA` mode, a `PostgreSQL` database and a `SubDomain Tenant Resolver`.
Retrieving the log from postgresql I've found an SQL Command with an error. 

I think that it's necessary to change the command that it's executing to change the schema.

### Task List

- [/] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [/] Example that reproduces the problem uploaded to Github
- [/] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a database in postgresql with another schema different of public
2. Configure the app to execute in MultiTenancy Schema mode and SubDomain tenant resolver
3. Try to access with a subdomain to the web app

### Expected Behaviour

It's expected to work with the current tenant 

### Actual Behaviour

It throws an `HibernateException` with a message `No session found for current thread`.
Taking a look to the database log I found a `SET SCHEMA schema1` command failing. The schema name must be a string 

It's trying to execute `SET SCHEMA schema1` instead of
`SET SCHEMA 'schema1'` as it's defined in postgresql docs https://www.postgresql.org/docs/9.6/static/sql-set.html.
Another way to resolve it could it be executing `SET search_path TO schema1` instead of SET SCHEMA.

### Environment Information

- **Operating System**: Linux Mint 19 Cinnamon
- **GORM Version:** 6.1.10.RELEASE
- **Grails Version (if using Grails):** 3.3.8
- **JDK Version:** jdk1.8.0_181

### Stacktrace

```
2018-08-27 10:54:50.224 ERROR --- [nio-8080-exec-1] o.g.web.errors.GrailsExceptionResolver   : HibernateException occurred when processing request: [GET] /vehicles
No Session found for current thread. Stacktrace follows:

java.lang.reflect.InvocationTargetException: null
	at org.grails.core.DefaultGrailsControllerClass$ReflectionInvoker.invoke(DefaultGrailsControllerClass.java:211)
	at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
	at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
	at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
	at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.hibernate.HibernateException: No Session found for current thread
	at org.grails.orm.hibernate.GrailsSessionContext.currentSession(GrailsSessionContext.java:117)
	at org.hibernate.internal.SessionFactoryImpl.getCurrentSession(SessionFactoryImpl.java:688)
	at org.grails.orm.hibernate.HibernateSession.createQuery(HibernateSession.java:182)
	at org.grails.orm.hibernate.HibernateSession.createQuery(HibernateSession.java:175)
	at grails.gorm.DetachedCriteria$_withPopulatedQuery_closure8.doCall(DetachedCriteria.groovy:747)
	at org.grails.datastore.gorm.GormStaticApi$_withDatastoreSession_closure24.doCall(GormStaticApi.groovy:862)
	at org.grails.datastore.mapping.core.DatastoreUtils.execute(DatastoreUtils.java:319)
	at org.grails.datastore.gorm.AbstractDatastoreApi.execute(AbstractDatastoreApi.groovy:40)
	at org.grails.datastore.gorm.GormStaticApi.withDatastoreSession(GormStaticApi.groovy:861)
	at grails.gorm.DetachedCriteria.withPopulatedQuery(DetachedCriteria.groovy:740)
	at grails.gorm.DetachedCriteria.count(DetachedCriteria.groovy:513)
	at grails.gorm.DetachedCriteria.count(DetachedCriteria.groovy:512)
	at grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)
	at demo.VehicleController.index(VehicleController.groovy:21)
	... 14 common frames omitted
```

### Example Application

https://github.com/xavier-gallofre/multi-tenancy-schema-postgresql-issue

**Comment by xavier-gallofre** [comment]
I've found a solution that I have implemented in the example application. [commit](https://github.com/xavier-gallofre/multi-tenancy-schema-postgresql-issue/commit/10874db8ab712758cb6a5009e773d4502bcb672a)

I've set another schemaHandler for the connection on the application.yml config file. It's a handler that extends the [DefaultSchemaHandler](https://github.com/grails/grails-data-mapping/blob/master/grails-datastore-gorm/src/main/groovy/org/grails/datastore/gorm/jdbc/schema/DefaultSchemaHandler.groovy) called [PostgreSQLSchemaHandler](https://github.com/xavier-gallofre/multi-tenancy-schema-postgresql-issue/blob/10874db8ab712758cb6a5009e773d4502bcb672a/src/main/groovy/demo/PostgreSQLSchemaHandler.groovy)
