### ISSUE TITLE
null value in column "date_created" violates not-null constraint error

### ISSUE THREAD

**Issue by demon101** [grails/grails-data-mapping#1171]
- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce
Following code produce exception with Postgres DB

```
    @Transactional
    def index() {
        def t = new Test()
        t.save()

        t.uid = "dfsdf"
        t.save()
        render "ok"
    }
```

> ERROR:  null value in column "date_created" violates not-null constraint
> DETAIL:  Failing row contains (1, 1, null, 2018-03-14 13:18:16.527, dfsdf).
> STATEMENT:  update test set version=$1, date_created=$2, last_updated=$3, uid=$4 where id=$5 and version=$6
> 2018-03-14 13:18:16.544 ERROR --- [nio-8080-exec-8] o.h.engine.jdbc.spi.SqlExceptionHelper   : ERROR: null value in column "date_created" violates not-null constraint
>   Detail: Failing row contains (1, 1, null, 2018-03-14 13:18:16.527, dfsdf).
> 2018-03-14 13:18:16.550 ERROR --- [nio-8080-exec-8] org.hibernate.internal.SessionImpl       : HHH000346: Error during managed flush [could not execute statement]
> 2018-03-14 13:18:16.650 ERROR --- [nio-8080-exec-8] o.g.web.errors.GrailsExceptionResolver   : PSQLException occurred when processing request: [GET] /test/index
> ERROR: null value in column "date_created" violates not-null constraint
>   Detail: Failing row contains (1, 1, null, 2018-03-14 13:18:16.527, dfsdf).. Stacktrace follows:
> 
> java.lang.reflect.InvocationTargetException: null
> 	at org.grails.core.DefaultGrailsControllerClass$ReflectionInvoker.invoke(DefaultGrailsControllerClass.java:211)
> 	at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
> 	at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
> 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
> 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
> 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
> 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
> 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
> 	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
> 	at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
> 	at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [date_created]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
> 	at org.springframework.orm.hibernate5.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:241)
> 	at org.springframework.orm.hibernate5.HibernateTransactionManager.convertHibernateAccessException(HibernateTransactionManager.java:755)
> 	at org.springframework.orm.hibernate5.HibernateTransactionManager.doCommit(HibernateTransactionManager.java:590)
> 	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:761)
> 	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:730)
> 	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:150)
> 	at grails.transaction.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:93)
> 	... 14 common frames omitted
> Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement
> 	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:112)
> 	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
> 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:111)
> 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:97)
> 	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:207)
> 	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:45)
> 	at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3132)
> 	at org.hibernate.persister.entity.AbstractEntityPersister.updateOrInsert(AbstractEntityPersister.java:3011)
> 	at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3391)
> 	at org.hibernate.action.internal.EntityUpdateAction.execute(EntityUpdateAction.java:145)
> 	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:582)
> 	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:456)
> 	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:337)
> 	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:39)
> 	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1295)
> 	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:468)
> 	at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:3135)
> 	at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2352)
> 	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:491)
> 	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:147)
> 	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.access$100(JdbcResourceLocalTransactionCoordinatorImpl.java:38)
> 	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:231)
> 	at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:65)
> 	at org.springframework.orm.hibernate5.HibernateTransactionManager.doCommit(HibernateTransactionManager.java:582)
> 	... 18 common frames omitted
> Caused by: org.postgresql.util.PSQLException: ERROR: null value in column "date_created" violates not-null constraint
>   Detail: Failing row contains (1, 1, null, 2018-03-14 13:18:16.527, dfsdf).
> 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2458)
> 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2158)
> 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:291)
> 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:432)
> 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:358)
> 	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:171)
> 	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:138)
> 	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:204)
> 	... 37 common frames omitted

### Expected Behaviour

Entity must be saved without errors. dateCreated must be filled

### Actual Behaviour

Exception fails

### Environment Information

- **Operating System**: Ubuntu
- **Grails Version:** 3.2.11
- **JDK Version:** 8
- **Container Version (If Applicable):** TODO

### Example Application

https://github.com/demon101/dateCreatedError

embed DB has been used in test upp. But error was reproduced with usual DB

**Comment by demon101** [comment]
@ilopmar I can't understand, where in method synchronizePersisterState dateCreated filled?
By method naming better to add method synchronizeEntityInsertActionState in else section with only dateCreated logic. Is it?

**Comment by demon101** [comment]
@ilopmar @jeffbrown the bug can't be reproduced in GORM 6.1 with Grails 3.3.9  
I think, it result of new default flush strategy. The issue can be closed
