### ISSUE TITLE
Grails 3.3 - OneToOne mapping not working

### ISSUE THREAD

**Issue by jglapa** [grails/grails-data-mapping#1173]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. download and start the example project: https://github.com/jglapa/g335-oneToOne
 * `./gradlew bootRun`
2. navigate to http://localhost:8080/body/create
 * should succeed and create Face and Nose objects in H2 db
3. navigate to http://localhost:8080/body/update
 * will fail:
```
        ... 14 common frames omitted
Caused by: org.h2.jdbc.JdbcSQLException: Parameter "#2" is not set; SQL statement:
select this_.id as y0_ from face this_ where this_.id=? limit ? [90012-197]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
        at org.h2.message.DbException.get(DbException.java:179)
        at org.h2.message.DbException.get(DbException.java:155)
        at org.h2.expression.Parameter.checkSet(Parameter.java:81)
        at org.h2.command.Prepared.checkParameters(Prepared.java:170)
        at org.h2.command.CommandContainer.query(CommandContainer.java:113)
        at org.h2.command.Command.executeQuery(Command.java:202)
        at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:114)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:70)
        ... 50 common frames omitted
```

### Expected Behaviour
update operation works

### Actual Behaviour

update operation fails with exception

#### Observation:
 * the `unique` constract for `nose` in `Face` domain seems to be the problem
 * this example is coming from the official  GORM guide : http://gorm.grails.org/6.1.x/hibernate/manual/#gormAssociation - 5.1.1. Many-to-one and one-to-one - Examples C
* the example works fine under Grails `3.2.13`
* the example fails already on `create` operation under Grails `3.3.0`

### Environment Information

- **Operating System**: Ubuntu 18
- **Grails Version:** 3.3.5
- **JDK Version:** 1.8

### Example Application

- https://github.com/jglapa/g335-oneToOne

**Comment by bassmartin** [comment]
I'm having issues with this also.

**Comment by ilopmar** [comment]
I'm able to reproduce the issue with your sample application but after upgrading it to Grails 3.3.9 and GORM 6.1.11 I can't reproduce it anymore and everything works as expected.

This is the patch you can apply:
```diff
diff --git a/gradle.properties b/gradle.properties
index 3b7b524..1365cec 100644
--- a/gradle.properties
+++ b/gradle.properties
@@ -1,3 +1,3 @@
-grailsVersion=3.3.5
-gormVersion=6.1.9.RELEASE
+grailsVersion=3.3.9
+gormVersion=6.1.11.RELEASE
 gradleWrapperVersion=3.5
```

**Comment by jglapa** [comment]
yay! thanks @ilopmar !
