### ISSUE TITLE
Method annotated @WithoutTenant throws "No Session found" error

### ISSUE THREAD

**Issue by ZacharyKlein** [grails/grails-data-mapping#1217]
1. Define a GORM Data Service in a Multi-Tenant Application
2. Annotate a method in the service with `@WithoutTenant`
3. Attempt to call annotated method

### Expected Behaviour

Method should return the expected result

### Actual Behaviour

```
Caused by: org.springframework.dao.DataAccessResourceFailureException: Could not obtain current Hibernate Session; nested exception is org.hibernate.HibernateException: No Session found for current thread
	at org.grails.orm.hibernate.GrailsHibernateTemplate.getSession(GrailsHibernateTemplate.java:337)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.doExecute(GrailsHibernateTemplate.java:286)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.execute(GrailsHibernateTemplate.java:243)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.execute(GrailsHibernateTemplate.java:117)
	at org.grails.orm.hibernate.AbstractHibernateDatastore.withSession(AbstractHibernateDatastore.java:355)
	at grails.gorm.multitenancy.Tenants.withoutId_closure1(Tenants.groovy:204)
	at grails.gorm.multitenancy.Tenants$CurrentTenant.withoutTenant(Tenants.groovy:380)
	at grails.gorm.multitenancy.Tenants.withoutId(Tenants.groovy:198)
	at org.grails.datastore.gorm.services.DefaultTenantService.withoutId(DefaultTenantService.groovy:59)
	... 1 more
```

### Environment Information

- **Operating System**: macOS
- **GORM Version:** 6.1.9 (6.1.10 and 6.1.11 are also affected)
- **Grails Version (if using Grails):** N/A
- **JDK Version:** 1.8

### Example Application

- https://github.com/ZacharyKlein/without-tenant-issue

**Comment by puneetbehl** [comment]
@ZacharyKlein You might also want to move `configurations` block above the `dependencies` block, i.e.:
```
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        if(details.requested.group == 'org.grails' && details.requested.name.startsWith('grails-datastore')) {
            details.useVersion(gormVersion)
        }
    }
}

dependencies { 
...
```

As I wasn't able to see the expected gorm version without this change. 

_PS: Check the current GORM version using `dependencyInsight` as:_
```
./gradlew -q dependencyInsight --configuration compile --dependency grails-datastore-gorm
```
