### ISSUE TITLE
MultiTenant HibernateSpec Tests fail after Grails 4 Upgrade

### ISSUE THREAD

**Issue by mftruso** [grails/grails-data-mapping#1274]
After upgrading to Grails 4, tests which configure a `SystemPropertyTenantResolver` are now failing. 
To demonstrate, I upgraded the sample `database-per-tenant` project referenced in the [Multi-Tenant Grails Guide](https://guides.grails.org/database-per-tenant/guide/index.html). 
### Task List
- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)
### Steps to Reproduce
Using the example application below, run the tests on each branch
1. `git checkout master` (Grails 3.3.0)
2. `cd complete`
3. `./gradlew test`
4. `git checkout grails4` (Grails 4.0.1)
5. `./gradlew test`
### Expected Behaviour
Same tests pass after Grails 4 upgrade
### Actual Behaviour
`TenantNotFound` Exception
```
No tenantId found
org.grails.datastore.mapping.multitenancy.exceptions.TenantNotFoundException: No tenantId found
	at org.grails.datastore.mapping.multitenancy.resolvers.NoTenantResolver.resolveTenantIdentifier(NoTenantResolver.groovy:17)
	at grails.gorm.multitenancy.Tenants.currentId(Tenants.groovy:73)
	at org.grails.datastore.gorm.services.DefaultTenantService.currentId(DefaultTenantService.groovy:47)
	at org.grails.datastore.gorm.services.DefaultTenantService.withCurrent(DefaultTenantService.groovy:71)
	at example.VehicleController.index(VehicleController.groovy:20)
	at org.grails.testing.runtime.support.ActionSettingMethodHandler.invoke(ActionSettingMethodHandler.groovy:29)
	at example.VehicleControllerSpec.Test the index action returns the correct model(VehicleControllerSpec.groovy:41)
```
### Environment Information
- **Operating System**: MacOs 10.15.1
- **GORM Version:** 7.0.2.RELEASE
- **Grails Version (if using Grails):** 4.0.1
- **JDK Version:** 1.8
### Example Application
https://github.com/mftruso/database-per-tenant/blob/grails4/complete/src/test/groovy/example/VehicleControllerSpec.groovy

**Comment by puneetbehl** [comment]
Fixed gorm-hibernate5 `v7.0.2`
