### ISSUE TITLE
GPMONGODB-397: Criteria with nested properties

### ISSUE THREAD

**Issue by graemerocher** [grails/grails-data-mapping#423]
Original Reporter: orlandobcrra
Environment: Not Specified
Version: Not Specified
Migrated From: http://jira.grails.org/browse/GPMONGODB-397

I would like do something like:
{code}
def c = Products.createCriteria()
def result = c.get {
    projections {
        sum("subType.points")
    }
}
{code}
Where subType is embedded.
But I get an error:
{code}
org.springframework.dao.InvalidDataAccessResourceUsageException: Attempt to project on a non-existent project [subType.points]
	at org.grails.datastore.mapping.mongo.query.MongoQuery$58.doInDB(MongoQuery.java:915)
	at org.grails.datastore.mapping.mongo.query.MongoQuery$58.doInDB(MongoQuery.java:833)
	at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:391)
	at org.grails.datastore.mapping.mongo.query.MongoQuery.executeQuery(MongoQuery.java:833)
	at org.grails.datastore.mapping.query.Query.list(Query.java:516)
	at org.grails.datastore.mapping.query.Query.singleResult(Query.java:534)
	at grails.gorm.CriteriaBuilder.get(CriteriaBuilder.java:260)
	at grails.gorm.CriteriaBuilder$get.call(Unknown Source)
{code}

**Comment by minhajkk** [comment]
@graemerocher is it fixed? I'm still facing same issue with mongodb plugin 5.0.0.RC2
