### ISSUE TITLE
MyDomainClass.get(objId) doesn't work when domainClass id type is String and objId is String presentation of a Long number

### ISSUE THREAD

**Issue by make** [grails/grails-data-mapping#552]
Setup:
```groovy
class MyDomainClass {
  String name
  static mapping = {
    id name:'name'
  }
}
```
When:
```groovy
MyDomainClass.get('2015')
```
Output:
```
org.springframework.orm.hibernate4.HibernateSystemException: Provided id of the wrong type for class MyDomainClass. Expected: class java.lang.String, got class java.lang.Long; nested exception is org.hibernate.TypeMismatchException: Provided id of the wrong type for class MyDomainClass. Expected: class java.lang.String, got class java.lang.Long
	at org.springframework.orm.hibernate4.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:218) ~[spring-orm-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.grails.orm.hibernate.GrailsHibernateTemplate.convertHibernateAccessException(GrailsHibernateTemplate.java:616) ~[grails-datastore-gorm-hibernate4-4.0.4.RELEASE.jar:na]
	at org.grails.orm.hibernate.GrailsHibernateTemplate.doExecute(GrailsHibernateTemplate.java:202) ~[grails-datastore-gorm-hibernate4-4.0.4.RELEASE.jar:na]
	at org.grails.orm.hibernate.GrailsHibernateTemplate.get(GrailsHibernateTemplate.java:258) ~[grails-datastore-gorm-hibernate4-4.0.4.RELEASE.jar:na]
	at org.grails.orm.hibernate.AbstractHibernateGormStaticApi.get(AbstractHibernateGormStaticApi.groovy:58) ~[grails-datastore-gorm-hibernate-core-4.0.4.RELEASE.jar:na]
	at org.grails.orm.hibernate.AbstractHibernateGormStaticApi$get.call(Unknown Source) ~[na:na]
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.get(GormEntity.groovy:369) ~[grails-datastore-gorm-4.0.4.RELEASE.jar:na]
	at org.grails.datastore.gorm.GormEntity$Trait$Helper$get$5.call(Unknown Source) ~[na:na]
	at MyDomainClass.get(MyDomainClass.groovy) ~[main/:na]
```

**Comment by make** [comment]
When debugging 
the property persistentEntity.identity.type in AbstractHibernateGormStaticApi.convertIdentifier() is Long
