### ISSUE TITLE
could not initialize proxy - no Session

### ISSUE THREAD

**Issue by kasonyang** [grails/grails-data-mapping#562]
here is my code:Gorm.groovy
```java
import grails.orm.bootstrap.*
import grails.persistence.*
import org.springframework.jdbc.datasource.DriverManagerDataSource
import org.h2.Driver

init = new HibernateDatastoreSpringInitializer(Person,Book)
def dataSource = new DriverManagerDataSource(Driver.name, "jdbc:h2:prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE", 'sa', '')
init.configureForDataSource(dataSource)

//save person
def p = new Person()
p.name = 'kk'
p.save()
//assign person to book then save book
def b = new Book()
b.name = "bb"
b.author = p
b.save()
//load book and get it's author
def bb = Book.load(b.id)
println bb.author  //here throws exception

@Entity
class Person {
	String name
	static constraints = {
		name blank:false
	}
}
@Entity
class Book{
	String name
	Person author
}
```
It throws a exception when running it:
```java
Caught: org.hibernate.LazyInitializationException: could not initialize proxy - no Session
org.hibernate.LazyInitializationException: could not initialize proxy - no Session
	at org.hibernate.proxy.AbstractLazyInitializer.initialize(AbstractLazyInitializer.java:164)
	at org.hibernate.proxy.AbstractLazyInitializer.getImplementation(AbstractLazyInitializer.java:285)
	at Book_$$_jvstd35_1.getAuthor(Book_$$_jvstd35_1.java)
	at Gorm.run(Gorm.groovy:21)
```
what does it mean and why?

**Comment by graemerocher** [comment]
Standalone GORM doesn't automatically bind a session to the thread, you have to do this yourself. Best way is to wrap all your logic in `Person.withTransaction {  }`

**Comment by kasonyang** [comment]
Thank you!
It is ok to wrap all logic in ```Person.withTransaction ```

As you say:

> Standalone GORM doesn't automatically bind a session to the thread, you have to do this yourself

What should I do if I want to bind a session to the thread?

**Comment by graemerocher** [comment]
`Person.withNewSession`
