### ISSUE TITLE
mappedWith = "none" not working when using neo4j

### ISSUE THREAD

**Issue by mburak** [grails/grails-data-mapping#567]
GORM/Neo4j is treating this kind of clasess marked with static mapWith = "none" as persistent properties when it should not. So when saving an object that has an association to a property of that class, neo4j tries to save it and throws the following exception. 

<code>
Caused by: groovy.lang.MissingPropertyException: No such property: _neo4j_gorm_undecl_ for class: com.brinqa.platform.core.model.TextAttributeType
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
	at groovy.lang.GroovyObject$getProperty.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at groovy.lang.GroovyObject$getProperty.call(Unknown Source)
	at org.grails.datastore.gorm.neo4j.Neo4jGormEnhancer.amendMapWithUndeclaredProperties(Neo4jGormEnhancer.groovy:55)
	at org.grails.datastore.gorm.neo4j.NodePendingInsert.run(NodePendingInsert.java:42)
	at org.grails.datastore.mapping.core.impl.PendingOperationExecution.executePendingOperation(PendingOperationExecution.java:33)
	at org.grails.datastore.gorm.neo4j.Neo4jSession.flushPendingOperations(Neo4jSession.java:116)
</code>

**Comment by graemerocher** [comment]
Does adding `transients` not work?

     static transients = ['myProp']

**Comment by mburak** [comment]
Yes, that worked.
