### ISSUE TITLE
App with hibernate and neo4j starts with errors

### ISSUE THREAD

**Issue by amadfida** [grails/grails-data-mapping#576]
Grails 2.5.2 application that depends on both hibernate and neo4j plugins, starts with errors when configuring dynamic methods in hibernate plugin, 

``` Groovy

    plugins {
        compile ":neo4j:5.0.0.BUILD-SNAPSHOT"
        runtime ":hibernate4:4.3.8.1"
        ....
    }
```

Following is the error thrown,

``` java

2015-11-08 17:28:01,945	[localhost-startStop-1]	ERROR	StackTrace:213	Full Stack Trace:
java.lang.IllegalArgumentException: Constructor argument 'application' cannot be null
	at org.springframework.util.Assert.notNull(Assert.java:112)
	at org.codehaus.groovy.grails.orm.hibernate.metaclass.AbstractStaticPersistentMethod.<init>(AbstractStaticPersistentMethod.java:54)
	at org.codehaus.groovy.grails.orm.hibernate.metaclass.AbstractClausedStaticPersistentMethod.<init>(AbstractClausedStaticPersistentMethod.java:402)
	at org.codehaus.groovy.grails.orm.hibernate.metaclass.FindAllByPersistentMethod.<init>(FindAllByPersistentMethod.java:63)
	at org.codehaus.groovy.grails.orm.hibernate.HibernateGormEnhancer.createDynamicFinders(HibernateGormEnhancer.groovy:53)
	at org.grails.datastore.gorm.GormEnhancer.getFinders(GormEnhancer.groovy:207)
	at org.codehaus.groovy.grails.orm.hibernate.HibernateGormEnhancer.getStaticApi(HibernateGormEnhancer.groovy:69)
	at org.grails.datastore.gorm.GormEnhancer.<init>(GormEnhancer.groovy:84)
	at org.codehaus.groovy.grails.orm.hibernate.AbstractHibernateGormEnhancer.<init>(AbstractHibernateGormEnhancer.groovy:42)
	at org.codehaus.groovy.grails.orm.hibernate.HibernateGormEnhancer.<init>(HibernateGormEnhancer.groovy:47)
	at org.codehaus.groovy.grails.orm.hibernate.cfg.HibernateUtils.enhanceSessionFactory(HibernateUtils.groovy:114)
	at org.codehaus.groovy.grails.orm.hibernate.cfg.HibernateUtils.enhanceSessionFactories(HibernateUtils.groovy:95)
	at org.codehaus.groovy.grails.orm.hibernate.cfg.HibernateUtils.enhanceSessionFactories(HibernateUtils.groovy)
	at org.codehaus.groovy.grails.orm.hibernate.cfg.HibernateUtils$enhanceSessionFactories.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at grails.plugin.hibernate4.HibernatePluginSupport$__clinit__closure3.doCall(HibernatePluginSupport.groovy:459)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1210)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1123)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
	at groovy.lang.Closure.call(Closure.java:426)
	at org.codehaus.groovy.grails.plugins.DefaultGrailsPlugin.doWithDynamicMethods(DefaultGrailsPlugin.java:702)
	at org.codehaus.groovy.grails.plugins.DefaultGrailsPluginManager.doDynamicMethods(DefaultGrailsPluginManager.java:783)
	at org.codehaus.groovy.grails.commons.spring.GrailsRuntimeConfigurator.configure(GrailsRuntimeConfigurator.java:172)
	at org.codehaus.groovy.grails.commons.spring.GrailsRuntimeConfigurator.configure(GrailsRuntimeConfigurator.java:127)
	at org.codehaus.groovy.grails.web.context.GrailsConfigUtils.configureWebApplicationContext(GrailsConfigUtils.java:126)
	at org.codehaus.groovy.grails.web.context.GrailsContextLoaderListener.initWebApplicationContext(GrailsContextLoaderListener.java:109)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4992)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5490)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1575)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1565)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2015-11-08 17:28:01,949	[localhost-startStop-1]	ERROR	StackTrace:213	Full Stack Trace:
java.lang.IllegalArgumentException: Constructor argument 'application' cannot be null
	at org.grails.datastore.gorm.GormEnhancer.getFinders(GormEnhancer.groovy:207)
	at org.grails.datastore.gorm.GormEnhancer.<init>(GormEnhancer.groovy:84)
	at grails.plugin.hibernate4.HibernatePluginSupport$__clinit__closure3.doCall(HibernatePluginSupport.groovy:459)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2015-11-08 17:28:01,949	[localhost-startStop-1]	ERROR	DefaultGrailsPluginManager:213	Error configuring dynamic methods for plugin [hibernate4:4.3.10]: Constructor argument 'application' cannot be null
java.lang.IllegalArgumentException: Constructor argument 'application' cannot be null
	at org.grails.datastore.gorm.GormEnhancer.getFinders(GormEnhancer.groovy:207)
	at org.grails.datastore.gorm.GormEnhancer.<init>(GormEnhancer.groovy:84)
	at grails.plugin.hibernate4.HibernatePluginSupport$__clinit__closure3.doCall(HibernatePluginSupport.groovy:459)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by amadfida** [comment]
I think i need a grails 2.5.x compatible `:hibernate4:5.0.0.BUILD-SNAPSHOT` version.

**Comment by graemerocher** [comment]
Right, I am working on this, it will be ready in a week or 2

**Comment by amadfida** [comment]
Is it possible to get a SNAPSHOT that resolved the compile issue?

**Comment by graemerocher** [comment]
No it isn't

**Comment by amadfida** [comment]
bumper !! ok please us posted on your progress, as this blocks our testing.

**Comment by mburak** [comment]
Still getting this error on latest snapshot, is it supposed to be fixed?

**Comment by graemerocher** [comment]
Nope it isn't supposed to be fixed, I only just pushed some initial code but there are still issues I'm fixing when using neo and hibernate together

**Comment by graemerocher** [comment]
Please try the latest snapshot of the `hibernate4` plugin:

      runtime ":hibernate4:5.0.0.BUILD-SNAPSHOT"

**Comment by mburak** [comment]
Now I'm getting another error:

```
Caused by: java.lang.NullPointerException
	at org.grails.orm.hibernate.cfg.AbstractGrailsDomainBinder.canBindOneToOneWithSingleColumnAndForeignKey(AbstractGrailsDomainBinder.java:2012)
	at org.grails.orm.hibernate.cfg.AbstractGrailsDomainBinder.createClassProperties(AbstractGrailsDomainBinder.java:1905)
	at org.grails.orm.hibernate.cfg.AbstractGrailsDomainBinder.bindRootPersistentClassCommonValues(AbstractGrailsDomainBinder.java:1759)
	at org.grails.orm.hibernate.cfg.AbstractGrailsDomainBinder.bindRoot(AbstractGrailsDomainBinder.java:1436)
	at org.grails.orm.hibernate.cfg.AbstractGrailsDomainBinder.bindClass(AbstractGrailsDomainBinder.java:1280)
	at org.grails.orm.hibernate.cfg.HibernateMappingContextConfiguration.secondPassCompile(HibernateMappingContextConfiguration.java:283)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1846)
	at org.grails.orm.hibernate.cfg.HibernateMappingContextConfiguration.buildSessionFactory(HibernateMappingContextConfiguration.java:196)
	at org.grails.orm.hibernate.HibernateMappingContextSessionFactoryBean.doBuildSessionFactory(HibernateMappingContextSessionFactoryBean.java:476)
	at org.grails.orm.hibernate.HibernateMappingContextSessionFactoryBean.buildSessionFactory(HibernateMappingContextSessionFactoryBean.java:470)
	at org.grails.orm.hibernate.HibernateMappingContextSessionFactoryBean.afterPropertiesSet(HibernateMappingContextSessionFactoryBean.java:93)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1633)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570)
	... 50 more
```

**Comment by graemerocher** [comment]
Please upload an example that reproduces the error

**Comment by mburak** [comment]
Actually there is another error first:

```
Caused by: groovy.lang.MissingMethodException: No signature of method: app.League$__clinit__closure2$_closure3.doCall() is applicable for argument types: () values: []
Possible solutions: doCall(org.grails.datastore.gorm.neo4j.GraphPersistentEntity, java.lang.Object), call(), call([Ljava.lang.Object;), call(java.lang.Object), call(org.grails.datastore.gorm.neo4j.GraphPersistentEntity, java.lang.Object), equals(java.lang.Object)
	at org.grails.orm.hibernate.cfg.HibernateMappingBuilder$_closure1.doCall(HibernateMappingBuilder.groovy:475)
	at org.grails.orm.hibernate.cfg.HibernateMappingBuilder.methodMissing(HibernateMappingBuilder.groovy:629)
	at app.League$__clinit__closure2.doCall(League.groovy:27)
	at org.grails.orm.hibernate.cfg.HibernateMappingBuilder.evaluate(HibernateMappingBuilder.groovy:79)
	at org.grails.datastore.mapping.config.AbstractGormMappingFactory.evaluateWithContext(AbstractGormMappingFactory.java:84)
	at org.grails.datastore.mapping.config.AbstractGormMappingFactory.createMappedForm(AbstractGormMappingFactory.java:71)
	at org.grails.orm.hibernate.cfg.HibernatePersistentEntity$1.<init>(HibernatePersistentEntity.java:41)
	at org.grails.orm.hibernate.cfg.HibernatePersistentEntity.<init>(HibernatePersistentEntity.java:40)
	at org.grails.orm.hibernate.cfg.HibernateMappingContext.createPersistentEntity(HibernateMappingContext.java:89)
	at org.grails.datastore.mapping.model.AbstractMappingContext.addPersistentEntityInternal(AbstractMappingContext.java:223)
	at org.grails.datastore.mapping.model.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:216)
	at org.grails.datastore.mapping.model.config.GormMappingConfigurationStrategy.getOrCreateAssociatedEntity(GormMappingConfigurationStrategy.java:706)
	at org.grails.datastore.mapping.model.config.GormMappingConfigurationStrategy.establishDomainClassRelationship(GormMappingConfigurationStrategy.java:670)
	at org.grails.datastore.mapping.model.config.GormMappingConfigurationStrategy.getPersistentProperties(GormMappingConfigurationStrategy.java:217)
	at org.grails.datastore.mapping.model.AbstractPersistentEntity.initialize(AbstractPersistentEntity.java:116)
	at org.grails.datastore.mapping.reflect.FastClassData.<init>(FastClassData.groovy:47)
	at org.grails.datastore.mapping.model.AbstractMappingContext.registerEntityWithContext(AbstractMappingContext.java:245)
	at org.grails.datastore.mapping.model.AbstractMappingContext.addPersistentEntities(AbstractMappingContext.java:187)
	at org.grails.orm.hibernate.cfg.HibernateMappingContext.<init>(HibernateMappingContext.java:47)
	at org.grails.orm.hibernate.support.HibernateMappingContextFactoryBean.getObject(HibernateMappingContextFactoryBean.groovy:26)
	... 4 more
```
This happens when using dynamic labels:
```
    static mapping = {
        labels { GraphPersistentEntity pe, instance ->
            "`${instance?.tags?.findAll()?.collect { it.name }?.join(',')}`"
        }
    }
```

You can reproduce this by running the app in https://github.com/mburak/neo4j-app

I'm getting the other error in a bigger app but I'll try to reproduce it in this app.

**Comment by graemerocher** [comment]
The app works fine for me with the latest snapshot:

	compile ":neo4j:5.0.0.BUILD-SNAPSHOT"
        compile ":hibernate4:5.0.0.BUILD-SNAPSHOT"

I had to do a `clean` first but after the transforms were correctly compiled it worked fine.

**Comment by mburak** [comment]
Sorry, my latest push had failed. Could you try again now?

**Comment by graemerocher** [comment]
With that I get

/Users/graemerocher/grails/apps/neo4j-app/grails-app/domain/app/AbstractGraphDomain.groovy: 3: unable to resolve class AbstractBaseDomain 
 @ line 3, column 1.
   class AbstractGraphDomain extends AbstractBaseDomain {
   ^

1 error

**Comment by graemerocher** [comment]
But regardless you can't mix entities from different engines. You have a neo entity extending a hibernate entity (`NativeNationality` and `Nationality`) so it doesn't surprise me you get an error

**Comment by mburak** [comment]
I moved the AbstractBaseDomain to grails-app/domain and changed Nationality to be also neo4j an still getting the same error. You can pull and try.

**Comment by graemerocher** [comment]
I have pushed a fix for this, however Travis CI is having issues right now and the build is not running yet 

https://travis-ci.org/grails/grails-data-mapping/builds/91631048

See https://github.com/travis-ci/travis-ci/issues/5124

**Comment by mburak** [comment]
Ok, I see that build is running again but failing. Let me know when I can test again. Thanks.

**Comment by graemerocher** [comment]
The latest snapshot should be ready for testing

**Comment by graemerocher** [comment]
So I believe this can be closed?

**Comment by mburak** [comment]
Yes, I can't do it.
