### ISSUE TITLE
Exceptions on startup

### ISSUE THREAD

**Issue by mburak** [grails/grails-data-mapping#587]
With the latest g-d-m snapshot, something got broken:

```
Caused by: org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.cache.spi.RegionFactory]
	at org.grails.orm.hibernate.cfg.HibernateMappingContextConfiguration.buildSettings(HibernateMappingContextConfiguration.java:219)
	at org.grails.orm.hibernate.cfg.HibernateMappingContextConfiguration.buildSessionFactory(HibernateMappingContextConfiguration.java:196)
	at org.grails.orm.hibernate.HibernateMappingContextSessionFactoryBean.doBuildSessionFactory(HibernateMappingContextSessionFactoryBean.java:476)
	at org.grails.orm.hibernate.HibernateMappingContextSessionFactoryBean.buildSessionFactory(HibernateMappingContextSessionFactoryBean.java:470)
	at org.grails.orm.hibernate.HibernateMappingContextSessionFactoryBean.afterPropertiesSet(HibernateMappingContextSessionFactoryBean.java:93)
	... 4 more
Caused by: org.hibernate.HibernateException: could not instantiate RegionFactory [org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory]
	... 9 more
Caused by: org.hibernate.boot.registry.selector.spi.StrategySelectionException: Unable to resolve name [org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory] as strategy [org.hibernate.cache.spi.RegionFactory]
	... 9 more
```

You can check it on this app: https://github.com/mburak/neo4j-app

**Comment by graemerocher** [comment]
Can't reproduce this, you probably had an older snapshot cached locally

**Comment by mburak** [comment]
It works with today's snapshot. Closing it.
