### ISSUE TITLE
java.lang.StackOverflowError using dynamic labels 

### ISSUE THREAD

**Issue by mburak** [grails/grails-data-mapping#588]
Something got broken in the latest snapshot because this was working before:

It seems that when saving an object that has a dynamic label mapping that refers to an association of that object, it's getting into a loop and throwing the following exception:

```
java.lang.StackOverflowError
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at groovy.lang.Closure.call(Closure.java:428)
	at app.Club$__clinit__closure2$_closure3.call(Club.groovy)
	at org.grails.datastore.gorm.neo4j.GraphPersistentEntity.getLabelFor(GraphPersistentEntity.groovy:202)
	at org.grails.datastore.gorm.neo4j.GraphPersistentEntity.getLabels(GraphPersistentEntity.groovy:132)
	at org.grails.datastore.gorm.neo4j.GraphPersistentEntity.getLabelsAsString(GraphPersistentEntity.groovy:157)
	at org.grails.datastore.gorm.neo4j.GraphPersistentEntity.appendRecursive(GraphPersistentEntity.groovy:214)
	at org.grails.datastore.gorm.neo4j.GraphPersistentEntity.getLabelsWithInheritance(GraphPersistentEntity.groovy:112)
	at org.grails.datastore.gorm.neo4j.Neo4jSession.flushPendingUpdates(Neo4jSession.java:246)
	at org.grails.datastore.mapping.core.AbstractSession.flush(AbstractSession.java:313)
	at org.grails.datastore.gorm.neo4j.Neo4jSession.flush(Neo4jSession.java:621)
	at org.grails.datastore.mapping.query.Query.flushBeforeQuery(Query.java:691)
	at org.grails.datastore.mapping.query.Query.list(Query.java:559)
	at org.grails.datastore.gorm.neo4j.engine.Neo4jEntityPersister.retrieveEntity(Neo4jEntityPersister.java:218)
	at org.grails.datastore.mapping.engine.EntityPersister.retrieve(EntityPersister.java:199)
	at org.grails.datastore.mapping.core.AbstractSession.retrieve(AbstractSession.java:624)
	at org.grails.datastore.gorm.proxy.ProxyInstanceMetaClass.getProxyTarget(ProxyInstanceMetaClass.java:66)
	at org.grails.datastore.gorm.proxy.ProxyInstanceMetaClass.invokeMethod(ProxyInstanceMetaClass.java:103)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:917)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:900)
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.castToBoolean(DefaultTypeTransformation.java:185)
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.booleanUnbox(DefaultTypeTransformation.java:74)
	at app.Club$__clinit__closure2$_closure3.doCall(Club.groovy:39)
	at sun.reflect.GeneratedMethodAccessor170.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springsource.loaded.ri.OriginalClassInvoker.invoke(OriginalClassInvoker.java:50)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1459)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1210)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1123)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
	at groovy.lang.Closure.call(Closure.java:426)
	at app.Club$__clinit__closure2$_closure3.call(Club.groovy)
	at org.grails.datastore.gorm.neo4j.GraphPersistentEntity.getLabelFor(GraphPersistentEntity.groovy:202)
	at org.grails.datastore.gorm.neo4j.GraphPersistentEntity.getLabels(GraphPersistentEntity.groovy:132)
	at org.grails.datastore.gorm.neo4j.GraphPersistentEntity.getLabelsAsString(GraphPersistentEntity.groovy:157)
	at org.grails.datastore.gorm.neo4j.GraphPersistentEntity.appendRecursive(GraphPersistentEntity.groovy:214)
	at org.grails.datastore.gorm.neo4j.GraphPersistentEntity.getLabelsWithInheritance(GraphPersistentEntity.groovy:112)
	at org.grails.datastore.gorm.neo4j.Neo4jSession.flushPendingUpdates(Neo4jSession.java:246)
	at org.grails.datastore.mapping.core.AbstractSession.flush(AbstractSession.java:313)
	at org.grails.datastore.gorm.neo4j.Neo4jSession.flush(Neo4jSession.java:621)
	at org.grails.datastore.mapping.query.Query.flushBeforeQuery(Query.java:691)
	at org.grails.datastore.mapping.query.Query.list(Query.java:559)
	at org.grails.datastore.gorm.neo4j.engine.Neo4jEntityPersister.retrieveEntity(Neo4jEntityPersister.java:218)
	at org.grails.datastore.mapping.engine.EntityPersister.retrieve(EntityPersister.java:199)
	at org.grails.datastore.mapping.core.AbstractSession.retrieve(AbstractSession.java:624)
	at org.grails.datastore.gorm.proxy.ProxyInstanceMetaClass.getProxyTarget(ProxyInstanceMetaClass.java:66)
	at org.grails.datastore.gorm.proxy.ProxyInstanceMetaClass.invokeMethod(ProxyInstanceMetaClass.java:103)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:917)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:900)
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.castToBoolean(DefaultTypeTransformation.java:185)
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.booleanUnbox(DefaultTypeTransformation.java:74)
	at app.Club$__clinit__closure2$_closure3.doCall(Club.groovy:39)
	at sun.reflect.GeneratedMethodAccessor170.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springsource.loaded.ri.OriginalClassInvoker.invoke(OriginalClassInvoker.java:50)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1459)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1210)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1123)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
	at groovy.lang.Closure.call(Closure.java:426)
	at app.Club$__clinit__closure2$_closure3.call(Club.groovy)
	at org.grails.datastore.gorm.neo4j.GraphPersistentEntity.getLabelFor(GraphPersistentEntity.groovy:202)
	at org.grails.datastore.gorm.neo4j.GraphPersistentEntity.getLabels(GraphPersistentEntity.groovy:132)
	at org.grails.datastore.gorm.neo4j.GraphPersistentEntity.getLabelsAsString(GraphPersistentEntity.groovy:157)
	at org.grails.datastore.gorm.neo4j.GraphPersistentEntity.appendRecursive(GraphPersistentEntity.groovy:214)
	at org.grails.datastore.gorm.neo4j.GraphPersistentEntity.getLabelsWithInheritance(GraphPersistentEntity.groovy:112)
	at org.grails.datastore.gorm.neo4j.Neo4jSession.flushPendingUpdates(Neo4jSession.java:246)
	at org.grails.datastore.mapping.core.AbstractSession.flush(AbstractSession.java:313)
	at org.grails.datastore.gorm.neo4j.Neo4jSession.flush(Neo4jSession.java:621)
	at org.grails.datastore.mapping.query.Query.flushBeforeQuery(Query.java:691)
	at org.grails.datastore.mapping.query.Query.list(Query.java:559)
	at org.grails.datastore.gorm.neo4j.engine.Neo4jEntityPersister.retrieveEntity(Neo4jEntityPersister.java:218)
	at org.grails.datastore.mapping.engine.EntityPersister.retrieve(EntityPersister.java:199)
	at org.grails.datastore.mapping.core.AbstractSession.retrieve(AbstractSession.java:624)
	at org.grails.datastore.gorm.proxy.ProxyInstanceMetaClass.getProxyTarget(ProxyInstanceMetaClass.java:66)
	at org.grails.datastore.gorm.proxy.ProxyInstanceMetaClass.invokeMethod(ProxyInstanceMetaClass.java:103)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:917)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:900)
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.castToBoolean(DefaultTypeTransformation.java:185)
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.booleanUnbox(DefaultTypeTransformation.java:74)
	at app.Club$__clinit__closure2$_closure3.doCall(Club.groovy:39)
	at sun.reflect.GeneratedMethodAccessor170.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
```

You can reproduce the error downloading the app at https://github.com/mburak/neo4j-app and executing the following controller action: http://localhost:8080/neo4j-app/clubs/addPlayer

**Comment by graemerocher** [comment]
I could not reproduce this, but made some changes that should fix it, if you could test and let me know ASAP if it is working for you https://github.com/grails/grails-data-mapping/commit/b462293d5e6005a947475b0196f1fbf18ec34c8e

**Comment by mburak** [comment]
Yeah, it's working now. Closing it.
