### ISSUE TITLE
NullPointerException when using MongoDB and Hibernate with mapWith

### ISSUE THREAD

**Issue by naman90** [grails/grails-data-mapping#592]
I am running 5.0.0.RC1 version with a new grails 3.0.9 project. It's giving the following error

org.grails.plugins:mongodb:5.0.0.RC1
   > Could not parse POM file:/C:/Users/Naman/.m2/repository/org/grails/grails-d
atastore-gorm-grails2-support/5.0.0.RC1/grails-datastore-gorm-grails2-support-5.
0.0.RC1.pom
      > Unable to resolve version for dependency 'org.grails:grails-async:jar'
   > Could not parse POM https://repo.grails.org/grails/core/org/grails/grails-d
atastore-gorm-grails2-support/5.0.0.RC1/grails-datastore-gorm-grails2-support-5.
0.0.RC1.pom

**Comment by graemerocher** [comment]
This is because you have the 2.x version of the plugin locally as well. Remove this first:

      rm -rf ~/.m2/repository/org/grails/plugins/mongodb

**Comment by naman90** [comment]
That worked, but ran into this error

ERROR grails.boot.GrailsApp - Application startup failed
java.lang.IllegalArgumentException: This class has been compiled with a super cl
ass which is binary incompatible with the current super class found on classpath
. You should recompile this class with the new version.
        at grails.orm.bootstrap.HibernateDatastoreSpringInitializer.<init>(Hiber
nateDatastoreSpringInitializer.groovy:89) ~[grails-datastore-gorm-hibernate4-4.0
.7.RELEASE.jar:na]
Exception in thread "main" java.lang.IllegalArgumentException: This class has be
en compiled with a super class which is binary incompatible with the current sup
er class found on classpath. You should recompile this class with the new versio
n.
        at grails.orm.bootstrap.HibernateDatastoreSpringInitializer.<init>(Hiber
nateDatastoreSpringInitializer.groovy:89)
        at grails.plugin.hibernate.HibernateGrailsPlugin$_doWithSpring_closure1.
doCall(HibernateGrailsPlugin.groovy:61)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(Refl
ectiveInterceptor.java:1426)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:
93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(C
losureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
        at groovy.lang.Closure.call(Closure.java:426)
        at groovy.lang.Closure.call(Closure.java:420)
        at grails.spring.BeanBuilder.invokeBeanDefiningClosure(BeanBuilder.java:
758)
        at grails.spring.BeanBuilder.beans(BeanBuilder.java:588)
        at grails.spring.BeanBuilder.invokeMethod(BeanBuilder.java:531)
        at grails.plugin.hibernate.HibernateGrailsPlugin$_doWithSpring_closure1.
doCall(HibernateGrailsPlugin.groovy:61) ~[hibernate-4.3.10.7.jar:na]

**Comment by graemerocher** [comment]
that is because you are using an old version of the HibernatePlugin, you need to remove the `hibernate` plugin and use the `hibernate4` plugin which is compatible:

       compile "org.grails.plugins:hibernate4:5.0.0.RC1"

**Comment by naman90** [comment]
Thanks that worked, but i am getting this error now

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManagerPostProcessor': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongoTransactionManager': Cannot resolve reference to bean 'mongoDatastore' while setting bean property 'datastore'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongoDatastore': Cannot resolve reference to bean 'gormMongoMappingContext' while setting bean property 'mappingContext'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gormMongoMappingContext': FactoryBean threw exception on object creation; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:547) ~[spring-beans-4.1.7.RELEASE.jar:4.1.7.RELEASE]

**Comment by graemerocher** [comment]
Please upload an example to Github that reproduces the issue

**Comment by graemerocher** [comment]
Or at least provide the full stack trace from `stacktrace.log`

**Comment by naman90** [comment]
@graemerocher Example uploaded at https://github.com/naman90/GrailsMongoTest/. errorLog.txt contains output in my machine.

**Comment by graemerocher** [comment]
Thanks for the example, will get this fixed for 5.0 GA
