### ISSUE TITLE
External domain class. ClassNotFoundException: org.grails.datastore.gorm.GormEntity$Trait$FieldHelper

### ISSUE THREAD

**Issue by wwarlock** [grails/grails-data-mapping#596]
Thank you very much for resolving issues #593 and #595.
But there is the next problem.
My domain classes are located in the separate grails plugin. And when I've include it to my project then I've got the next error.
```bash
$ gradle --stacktrace assemble
Cannot resolve reloading agent JAR: Could not resolve all dependencies for configuration ':agent'.
:assetCompile UP-TO-DATE
:buildProperties UP-TO-DATE
:compileJava UP-TO-DATE
:compileGroovy FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileGroovy'.
> org/grails/datastore/gorm/GormEntity$Trait$FieldHelper

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':compileGroovy'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
	at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:77)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:47)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
Caused by: java.lang.NoClassDefFoundError: org/grails/datastore/gorm/GormEntity$Trait$FieldHelper
	at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:164)
	at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:52)
	at org.gradle.api.internal.tasks.compile.daemon.CompilerDaemonServer.execute(CompilerDaemonServer.java:53)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.ClassNotFoundException: org.grails.datastore.gorm.GormEntity$Trait$FieldHelper
	... 8 more


BUILD FAILED
```
So, what I must to do with the plugin or project to remove that error in the current situation?
For the current modifications I've used instructions from the [manual](http://grails.github.io/grails-data-mapping/5.0.0.RC1/hibernate/manual/guide/gettingStarted.html) (section 2.1)

**Comment by wwarlock** [comment]
I forgot to mention that I've tried to add annotations from the section 2.2 of manual.
Though with the same result.

**Comment by graemerocher** [comment]
This is probably a classpath problem, check that the correct version of `grails-datastore-gorm` is on your classpath

**Comment by wwarlock** [comment]
We're talking about the project, not the plugin, right?

Here is my build settings

From the `gradle.properties`
```properties
gormVersion=5.0.0.BUILD-SNAPSHOT
hibernateVersion=5.0.3.Final
```
And from the `build.groovy`
```groovy
buildscript {
    ...
    dependencies {        
        classpath "org.grails:grails-gradle-plugin:$grailsVersion"
        classpath 'com.bertramlabs.plugins:asset-pipeline-gradle:2.5.0'
        classpath "org.grails.plugins:hibernate5:$gormVersion"
    }
}

...

configurations.all {
    resolutionStrategy {
        eachDependency { DependencyResolveDetails details ->
            if(details.requested.group == 'org.springframework') {
                details.useVersion('4.2.3.RELEASE')
            }
        }
    }
}

dependencies {
    runtime 'org.postgresql:postgresql:9.3-1100-jdbc41'
    ...
    compile "org.grails.plugins:hibernate5:$gormVersion"

    compile "org.grails.plugins:cache:3.0.1"
    compile "org.hibernate:hibernate-core:$hibernateVersion"
    compile "org.hibernate:hibernate-ehcache:$hibernateVersion"
}
```
At first I thought that the `postgres` version is `9.3-1100-jdbc41` and `jdbc41` is incorrect.
But I've also created an empty project with H2 DB and same problem was reproduced.
That problem also reproduced with the `org.grails.plugins:hibernate4:$gormVersion` and with the `org.grails.plugins:hibernate:$gormVersion` too.

**Comment by graemerocher** [comment]
Ok I will try to reproduce in the functional test suite.

**Comment by graemerocher** [comment]
As you can see from these commits:

https://github.com/grails/grails-data-mapping-functional-tests/commit/95d2494a761f5af6a4cbb6fad8287f5c1e0d761d
https://github.com/grails/grails-data-mapping-functional-tests/commit/5607e383eee090cdf7a89d67615d614a0236a373

This works fine. Only thing I ran into was the Spring Loaded bug during run-app: https://github.com/grails/grails-core/issues/9288

So you must have a problem with your classpath

**Comment by graemerocher** [comment]
If you want this investigated further please upload an example to Github that reproduces the issue

**Comment by wwarlock** [comment]
Yes, we can close that issue, there is no problem.
I have created new empty plugin and project compiled succesfully with it.
Thank you for your time.

**Comment by wwarlock** [comment]
I was wrong at last that there is no error.
Please look at my example. You will need the two projects.
https://github.com/wwarlock/GrailsGormHibernate5
https://github.com/wwarlock/GrailsGormHibernate5Plugin

**Comment by graemerocher** [comment]
From just a quick look at the projects, the `GrailsGormHibernate5Plugin` project has no compile dependency on the `hibernate5` plugin, this means it is being compiled with the version of `grails-datastore-gorm` that ships with Grails 3.0.x (4.0.7 of g-d-m I believe) instead of with 5.0.0.RC2. This is what leads to the error. I have seen the error locally as well and it is always because you are compiling with an older version of GORM.

**Comment by wwarlock** [comment]
Yes, I've looked at dependency-report. The only mention of hibernate is `org.hibernate.javax.persistence:hibernate-jpa-2.1-api:1.0.0.Final`.
I'll try to relocate classes from domains and mark them with `@Entry` annotation.
But also I'll exclude that dependency and maybe "org.grails:grails-datastore-core:4.0.7.RELEASE".
And will look how it will work.

**Comment by wwarlock** [comment]
Possibly I'll must to comment my operations.
I have the complex project with the several subprojects.
Lets look on three of them:
1) front-end (doesn't uses any DB operation, all data-flow through the REST)
2) back-end (classic grails app, which converts data-flow between DB and REST)
3) and the plugin with the classes which serves as domains for GORM in 2, and which just ordinary classes in 1.
Maybe this all incorrect architecture but it works with Grails 2.4

**Comment by wwarlock** [comment]
So, I need the way to fully disable gorm on plugin.
Lets back-end uses their own GORM on plugin's domains.

**Comment by graemerocher** [comment]
If you want to full disable GORM then the class shouldn't be in grails-app/domain

The reason it "works" in 2.x is because classes are runtime enhanced via metaprogramming in 2.x, whilst with Grails 3.x classes are compile time enhanced

There is also no way to runtime enhance classes anymore, so if you disable GORM on the plugin they can never be GORM entities in the future. They are either GORM entities or they are not.

**Comment by wwarlock** [comment]
Ok, I understood.
Thanks again.
