### ISSUE TITLE
Loading instances with dynamic relationships fails

### ISSUE THREAD

**Issue by mburak** [grails/grails-data-mapping#601]
When loading an instance from database that has a dynamic relationship, it's throwing an exception when it tries to unmarshall the dynamically related instance:

```
[User, user]. Stacktrace follows:
org.grails.datastore.mapping.engine.NonPersistentTypeException: [User, user]
	at org.grails.datastore.gorm.neo4j.Neo4jMappingContext.findPersistentEntityForLabels(Neo4jMappingContext.java:126)
	at org.grails.datastore.gorm.neo4j.engine.Neo4jEntityPersister.unmarshall(Neo4jEntityPersister.java:532)
	at org.grails.datastore.gorm.neo4j.engine.Neo4jEntityPersister.unmarshallOrFromCache(Neo4jEntityPersister.java:263)
	at org.grails.datastore.gorm.neo4j.collection.Neo4jResultList.nextDecodedInternal(Neo4jResultList.groovy:93)
	at org.grails.datastore.gorm.neo4j.collection.Neo4jResultList.nextDecoded(Neo4jResultList.groovy:77)
	at org.grails.datastore.gorm.query.AbstractResultList.convertObject(AbstractResultList.java:97)
	at org.grails.datastore.gorm.query.AbstractResultList$1.next(AbstractResultList.java:161)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2029)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2015)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2056)
	at org.codehaus.groovy.runtime.dgm$162.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoMetaMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:251)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:71)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:123)
	at com.brinqa.platform.marshallers.json.SearchResultMarshaller.marshalObject(SearchResultMarshaller.groovy:26)
```

It looks that findPersistentEntityForLabels method is not finding the right class for the given labels. This seems to be happening because those labels are generated dynamically but the method is searching in a map that is generated from static labels.

**Comment by graemerocher** [comment]
You'll need to provide an example to reproduce the problem. Thanks.

**Comment by mburak** [comment]
You can check it on http://github.com/mburak/neo4j-app. Run it with an empty db. On Bootstrap line's 54 it's creating a dynamic association and the saving in the next line is failing with that kind of exception.

**Comment by graemerocher** [comment]
Unfortunately I don't know how this can be fixed. What you want to do is combine dynamic associations with dynamic labels. The problem is with a dynamic associations we do not know the type of the underlying node at the point the associations is retrieved so we have to calculate the type (in this case `Club`) from the labels that are present in the node. If these labels are dynamic there is no way to perform that calculation.

In order to support this we would have to separate the notion of a discriminator for the Node from the label strategy, which is not currently implemented and is a much larger piece of work. It also has the downside that we would have to store the Java type within the node as property in order to perform the discrimination.

Another solution would be to provide some way to declare the type of the dynamic association, however again that would require a larger rethink on how they are loaded and wouldn't make them very dynamic :)

**Comment by amadfida** [comment]
One rather simple solution can be to use the relationship properties, to include source and target types when creating relationships. The code that is inserting relationship is fairly isolated and specific and can be modified to include additional properties when creating relationship. The next thing we will need to update is unmarshalling code to use these properties to lookup persistent entity vs. labels. for dynamic relationships.

**Comment by mburak** [comment]
We created a patch so we add the related object Java class as a property on the dynamic relationship. This way, when it unmarshalls the related object it can know what type to convert it.
The solution might not be the best, but it works for what we need for now.
Should I create a pull request for this?

[dynamic_assoc_fix.zip](https://github.com/grails/grails-data-mapping/files/74414/dynamic_assoc_fix.zip)

**Comment by graemerocher** [comment]
A pull request would be better yes.. thanks
