### ISSUE TITLE
Problems with a join not being lazy ;)

### ISSUE THREAD

**Issue by fsogni** [grails/grails-data-mapping#604]
I am using grails 2.5.0

In my model I have a Batch that has many Dataset(s), each Dataset has many File(s) and a File hasMany sourceFiles. When I retrieve the datasets also the sourceFiles are retrieved with a long list of selects, even if I am not requesting sourceFiles.
The problem is caused by the annotation @EqualsAndHashCode in the domain class File used to perform a unit test. If I remove the annotation everything behaves as expected.

This is my model:

```
    @Entity
    class Batch {
        static hasMany = [ datasets : Dataset]
    }

    @Entity
    class Dataset {
        File mainFile
        Batch batch

        static hasMany = [files : File]
        static mapping = {
            files column:"dataset_id"
            files joinTable:[name:"${Constants.phase3DB}${Constants.schemaName}.datasets_files"]
            files fetch:'join'
        }
}

    @Entity
    @EqualsAndHashCode
    class File {
        static hasMany = [ sourceFiles: String ] 
        static mapping = {
        sourceFiles joinTable: [name:
        "${Constants.phase3DB}${Constants.schemaName}.provenance",
        key:'product_file', column:'source_file', type:'text']
        }
}
```

This is the select:

```
Batch batch = Batch.get(batchId)
def datasets = Dataset.withCriteria {
    eq "batch", batch
    fetchMode "files", org.hibernate.FetchMode.JOIN
}
batch.datasets = datasets
```

This query generates a long list selects retrieving sourceFiles.
If I add to the criteria  fetchMode "files.sourceFiles", org.hibernate.FetchMode.JOIN
I get a null pointer exception:

```
java.lang.NullPointerException

at
org.hibernate.engine.internal.StatefulPersistenceContext.getLoadedCollectionOwnerOrNull(StatefulPersistenceContext.java:752)

at
org.hibernate.event.spi.AbstractCollectionEvent.getLoadedOwnerOrNull(AbstractCollectionEvent.java:75)

at
org.hibernate.event.spi.InitializeCollectionEvent.<init>(InitializeCollectionEvent.java:36)

at
org.hibernate.internal.SessionImpl.initializeCollection(SessionImpl.java:1895)

at
org.hibernate.collection.internal.AbstractPersistentCollection$4.doWork(AbstractPersistentCollection.java:558)

at
org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:260)

at
org.hibernate.collection.internal.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:554)

at
org.hibernate.collection.internal.AbstractPersistentCollection.read(AbstractPersistentCollection.java:142)

at
org.hibernate.collection.internal.PersistentSet.hashCode(PersistentSet.java:447)

at org.eso.phase3.rm.File.hashCode(File.groovy)

at java.util.HashMap.hash(HashMap.java:338)

at java.util.HashMap.put(HashMap.java:611)

at java.util.HashSet.add(HashSet.java:219)

at java.util.AbstractCollection.addAll(AbstractCollection.java:344)

at
org.hibernate.collection.internal.PersistentSet.endRead(PersistentSet.java:344)

at
org.hibernate.engine.loading.internal.CollectionLoadContext.endLoadingCollection(CollectionLoadContext.java:251)

at
org.hibernate.engine.loading.internal.CollectionLoadContext.endLoadingCollections(CollectionLoadContext.java:238)

at
org.hibernate.engine.loading.internal.CollectionLoadContext.endLoadingCollections(CollectionLoadContext.java:211)

at org.hibernate.loader.Loader.endCollectionLoad(Loader.java:1156)

at
org.hibernate.loader.Loader.initializeEntitiesAndCollections(Loader.java:1125)

at org.hibernate.loader.Loader.processResultSet(Loader.java:972)

at org.hibernate.loader.Loader.doQuery(Loader.java:920)

at
org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:354)

at org.hibernate.loader.Loader.doList(Loader.java:2553)

at org.hibernate.loader.Loader.doList(Loader.java:2539)

at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2369)

at org.hibernate.loader.Loader.list(Loader.java:2364)

at
org.hibernate.loader.criteria.CriteriaLoader.list(CriteriaLoader.java:126)

at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1682)

at org.hibernate.internal.CriteriaImpl.list(CriteriaImpl.java:380)

at
org.grails.datastore.gorm.GormStaticApi$_withCriteria_closure11.doCall(GormStaticApi.groovy:305)

at
org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)

at com.sun.proxy.$Proxy47.doInSession(Unknown Source)

at
org.grails.datastore.mapping.core.DatastoreUtils.execute(DatastoreUtils.java:302)

at
org.grails.datastore.gorm.AbstractDatastoreApi.execute(AbstractDatastoreApi.groovy:37)

at
org.grails.datastore.gorm.GormStaticApi.withCriteria(GormStaticApi.groovy:304)

at org.eso.phase3.rm.Dataset.withCriteria(Dataset.groovy)

at org.eso.phase3.rm.Dataset$withCriteria.call(Unknown Source)

at ConsoleScript0.run(ConsoleScript0:4)

at
org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
```

**Comment by graemerocher** [comment]
Can't reproduce this in GORM 6
