### ISSUE TITLE
ClassCastException using Mongo datastore

### ISSUE THREAD

**Issue by paulfairless** [grails/grails-data-mapping#605]
Attempting to update using latest mongo (:mongodb:5.0.0.RC2) using Grails 2.5.3 and encountered the following exception while using fixtures plugin to create domain objects. The issue appears to reside in the in the datastore itself:

```
java.lang.ClassCastException: org.bson.Document cannot be cast to com.mongodb.DBObject
	at org.grails.datastore.mapping.engine.types.AbstractMappingAwareCustomTypeMarshaller.write(AbstractMappingAwareCustomTypeMarshaller.java:54)
	at org.grails.datastore.mapping.mongo.engine.codecs.PersistentEntityCodec$CustomTypeEncoder.encode(PersistentEntityCodec.groovy:863)
	at org.grails.datastore.mapping.mongo.engine.codecs.PersistentEntityCodec$CustomTypeEncoder.encode(PersistentEntityCodec.groovy:856)
	at org.grails.datastore.mapping.mongo.engine.codecs.PersistentEntityCodec.encode(PersistentEntityCodec.groovy:493)
	at org.grails.datastore.mapping.mongo.engine.codecs.PersistentEntityCodec.encode(PersistentEntityCodec.groovy:254)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29)
	at com.mongodb.connection.InsertCommandMessage.writeTheWrites(InsertCommandMessage.java:101)
	at com.mongodb.connection.InsertCommandMessage.writeTheWrites(InsertCommandMessage.java:43)
	at com.mongodb.connection.BaseWriteCommandMessage.encodeMessageBodyWithMetadata(BaseWriteCommandMessage.java:129)
	at com.mongodb.connection.RequestMessage.encodeWithMetadata(RequestMessage.java:160)
	at com.mongodb.connection.WriteCommandProtocol.sendMessage(WriteCommandProtocol.java:212)
	at com.mongodb.connection.WriteCommandProtocol.execute(WriteCommandProtocol.java:101)
	at com.mongodb.connection.InsertCommandProtocol.execute(InsertCommandProtocol.java:67)
	at com.mongodb.connection.InsertCommandProtocol.execute(InsertCommandProtocol.java:37)
	at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:159)
	at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:286)
	at com.mongodb.connection.DefaultServerConnection.insertCommand(DefaultServerConnection.java:115)
	at com.mongodb.operation.MixedBulkWriteOperation$Run$2.executeWriteCommandProtocol(MixedBulkWriteOperation.java:455)
	at com.mongodb.operation.MixedBulkWriteOperation$Run$RunExecutor.execute(MixedBulkWriteOperation.java:646)
	at com.mongodb.operation.MixedBulkWriteOperation$Run.execute(MixedBulkWriteOperation.java:401)
	at com.mongodb.operation.MixedBulkWriteOperation$1.call(MixedBulkWriteOperation.java:179)
	at com.mongodb.operation.MixedBulkWriteOperation$1.call(MixedBulkWriteOperation.java:168)
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:230)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:221)
	at com.mongodb.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:168)
	at com.mongodb.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:74)
	at com.mongodb.Mongo.execute(Mongo.java:782)
	at com.mongodb.Mongo$2.execute(Mongo.java:765)
	at com.mongodb.MongoCollectionImpl.bulkWrite(MongoCollectionImpl.java:291)
	at com.mongodb.MongoCollectionImpl.bulkWrite(MongoCollectionImpl.java:245)
	at org.grails.datastore.mapping.mongo.MongoCodecSession.flush(MongoCodecSession.groovy:228)
	at org.grails.datastore.mapping.mongo.AbstractMongoSession.flush(AbstractMongoSession.java:67)
	at org.grails.datastore.gorm.GormInstanceApi.doSave(GormInstanceApi.groovy:206)
	at org.grails.datastore.gorm.GormInstanceApi$_save_closure5.doCall(GormInstanceApi.groovy:170)
	at org.grails.datastore.mapping.core.DatastoreUtils.execute(DatastoreUtils.java:310)
	at org.grails.datastore.gorm.AbstractDatastoreApi.execute(AbstractDatastoreApi.groovy:37)
	at org.grails.datastore.gorm.GormInstanceApi.save(GormInstanceApi.groovy:169)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.save(GormEntity.groovy:140)
	at grails.plugin.fixtures.builder.processor.FixtureBeanPostProcessor.postProcessAfterInitialization(FixtureBeanPostProcessor.groovy:45)
	at grails.spring.BeanBuilder.createApplicationContext(BeanBuilder.java:593)
	at grails.plugin.fixtures.builder.FixtureBuilder.createApplicationContext(FixtureBuilder.groovy:140)
	at grails.plugin.fixtures.files.FixtureFileLoader.load(FixtureFileLoader.groovy:56)
	at grails.plugin.fixtures.Fixture.load(Fixture.groovy:54)
	at grails.plugin.fixtures.FixtureLoader.load(FixtureLoader.groovy:46)
	at grails.plugin.fixtures.FixtureLoader.load(FixtureLoader.groovy:38)
```

**Comment by graemerocher** [comment]
This is because you are using another plugin with MongoDB that provides a custom type (such as JodaTime?) that needs to be updated to be MongoDB 3.x compatible

**Comment by paulfairless** [comment]
yes, thank you
