### ISSUE TITLE
Domain classes with a Map property fails with GroovyCastException on delete from MongoDB

### ISSUE THREAD

**Issue by dmahapatro** [grails/grails-data-mapping#615]
*_Grails 3.1.0.RC1_
*_org.grails.plugins:mongodb:5.0.0.RC3_

Example Domain:

```groovy
class Product {
    static mapWith = "mongo"

    String id
    String name
    Map characteristics

    static embedded = ['characteristics']
}
```

I am using a Restful API for `DELETE` for `Product`.

On `delete()` below stacktrace is seen.

```
org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'org.grails.datastore.mapping.dirty.checking.DirtyCheckingMap@19284357' with class 'org.grails.datastore.mapping.dirty.checking.DirtyCheckingMap' to class 'java.lang.Iterable' due to: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: java.lang.Iterable(org.grails.datastore.mapping.dirty.checking.DirtyCheckingMap)
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnSAM(DefaultTypeTransformation.java:403) ~[groovy-2.4.5.jar:2.4.5]
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnNumber(DefaultTypeTransformation.java:319) ~[groovy-2.4.5.jar:2.4.5]
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.castToType(DefaultTypeTransformation.java:232) ~[groovy-2.4.5.jar:2.4.5]
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.castToType(ScriptBytecodeAdapter.java:603) ~[groovy-2.4.5.jar:2.4.5]
	at org.grails.datastore.mapping.mongo.engine.MongoCodecEntityPersister.deleteEntity(MongoCodecEntityPersister.groovy:483) ~[grails-datastore-gorm-mongodb-5.0.0.RC2.jar:na]
	at org.grails.datastore.mapping.engine.EntityPersister.delete(EntityPersister.java:262) ~[grails-datastore-core-5.0.0.RC2.jar:na]
	at org.grails.datastore.mapping.core.AbstractSession.delete(AbstractSession.java:727) ~[grails-datastore-core-5.0.0.RC2.jar:na]
	at org.grails.datastore.gorm.GormInstanceApi$_delete_closure9.doCall(GormInstanceApi.groovy:262) ~[grails-datastore-gorm-5.0.0.RC2.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93) ~[groovy-2.4.5.jar:2.4.5]
```

Main class to look at is [`MongoCodecEntityPersister.groovy:484`](https://github.com/grails/grails-data-mapping/blob/master/grails-datastore-gorm-mongodb%2Fsrc%2Fmain%2Fgroovy%2Forg%2Fgrails%2Fdatastore%2Fmapping%2Fmongo%2Fengine%2FMongoCodecEntityPersister.groovy#L484
)

```groovy
if(v != null) {
    mongoSession.delete( (Iterable) v )
}
```

In case of a `Map` property `v` would be [`DirtyCheckingMap`](https://github.com/grails/grails-data-mapping/blob/master/grails-datastore-core/src/main/groovy/org/grails/datastore/mapping/dirty/checking/DirtyCheckingMap.groovy) which implements `Map` interface which in fact is not `Iterable`, therefore the exception.

#### Fix:  
A simple fix would be in `MongoCodecEntityPersister` as:

```groovy
if(v != null) {
    mongoSession.delete( v in DirtyCheckingMap ? v : (Iterable) v )
}
```

**Comment by graemerocher** [comment]
I think this may be the same as https://github.com/grails/grails-data-mapping/issues/607

which is fixed by https://github.com/grails/grails-data-mapping/commit/9e74481e9f3999ae428d5c4820f1fd91683713fb

**Comment by dmahapatro** [comment]
Thanks @graemerocher . When is the plan to release `5.0.0`?

**Comment by orubel** [comment]
Well first thing I'm seeing is you are using String id. You have to use Mongo's ID instead

**Comment by dmahapatro** [comment]
@orubel What is the problem in using String id?

**Comment by orubel** [comment]
from what I recall, it wanted to used it's own bson.objectid

ObjectId id

**Comment by dmahapatro** [comment]
@orubel You can still use a `String` id? GORM would create a hexadecimal identifier similar to `ObjectId` 's `str` representation. I do not think there should be any issue with using a `String` id, with a caveat that if the String id is `assigned` then different approach has to be used to persist that entity. But if generator is not assigned then a hexadecimal id will be created for a String id.

**Comment by orubel** [comment]
Interesting. I must not have used generator or something. Thanks.
