### ISSUE TITLE
java.lang.StackOverflowError when inserting bulk domain object in mongodb

### ISSUE THREAD

**Issue by naman90** [grails/grails-data-mapping#631]
I am running a performance test case, and looping through 50K rows and saving them to mongodb. It saves about 15k rows, then throws this error.

java.lang.StackOverflowError
	at org.grails.datastore.mapping.dirty.checking.DirtyCheckingCollection.iterator(DirtyCheckingCollection.groovy:14)
	at org.grails.datastore.mapping.dirty.checking.DirtyCheckingCollection.iterator(DirtyCheckingCollection.groovy:14)
	at org.grails.datastore.mapping.dirty.checking.DirtyCheckingCollection.iterator(DirtyCheckingCollection.groovy:14)
	at org.grails.datastore.mapping.dirty.checking.DirtyCheckingCollection.iterator(DirtyCheckingCollection.groovy:14)
	at

**Comment by graemerocher** [comment]
Probably the root cause is an OutOfMemory issue, are you periodically clearly the session?

**Comment by naman90** [comment]
I observed that i can save 300K rows without any problem, but if an entity has an embedded object, it gets out of memory around 15k rows. I tried to get sessionFactory.currentSession to clear it, but it throws no session found exception. 
I have the code at  https://github.com/naman90/grailsdataStackOverflowError.git which reproduces the problem when running integration tests.
