### ISSUE TITLE
Enums are mapped as INT when using Hibernate 5 with Gorm 5.0.1

### ISSUE THREAD

**Issue by hakanernam** [grails/grails-data-mapping#640]
Enums are mapped as INT instead of VARCHAR with Hibernate5. 

If Table is regenerated or created, enum values are saved as ints. But exception is thrown if an existing table with enum values in it is accessed. Therefore, upgrading an existing applcation is not possible as it stands.

Tested with Grails 3.0.14, 3.1.1, MySql, H2.

```
class Book {

   String title
   BookType type = BookType.GOOD

    static constraints = {
      title blank:false
    }
}

enum BookType{
    GOOD, BAD, BORING
}
```

![screenshot at feb 05 09-51-36](https://cloud.githubusercontent.com/assets/1321157/12841498/c5c35876-cbf4-11e5-8e04-5292443be88f.png)
![screenshot at feb 05 09-56-16](https://cloud.githubusercontent.com/assets/1321157/12841502/ceabb1d6-cbf4-11e5-956d-eba062014b8b.png)

Exception trying to access existing data with enums stored as VARCHARS (created with hibernate4):

```
Grails application running at http://localhost:8080 in environment: development
ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Invalid value for getInt() - 'BAD'
ERROR org.grails.web.errors.GrailsExceptionResolver - SQLException occurred when processing request: [GET] /book/index
Invalid value for getInt() - 'BAD'. Stacktrace follows:
org.springframework.dao.TransientDataAccessResourceException: Hibernate operation: could not execute query; SQL [select this_.id as id1_0_0_, this_.version as version2_0_0_, this_.title as title3_0_0_, this_.type as type4_0_0_ from book this_]; Invalid value for getInt() - 'BAD'; nested exception is java.sql.SQLException: Invalid value for getInt() - 'BAD'
	at app311.BookController.index(BookController.groovy:13) ~[main/:na]
	at grails.transaction.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:96) ~[grails-core-3.1.1.jar:3.1.1]
	at grails.transaction.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:93) ~[grails-core-3.1.1.jar:3.1.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_66]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]
Caused by: java.sql.SQLException: Invalid value for getInt() - 'BAD'
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957) ~[mysql-connector-java-5.1.38.jar:5.1.38]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:896) ~[mysql-connector-java-5.1.38.jar:5.1.38]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:885) ~[mysql-connector-java-5.1.38.jar:5.1.38]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860) ~[mysql-connector-java-5.1.38.jar:5.1.38]
	at com.mysql.jdbc.ResultSetImpl.getInt(ResultSetImpl.java:2514) ~[mysql-connector-java-5.1.38.jar:5.1.38]
	at com.mysql.jdbc.ResultSetImpl.getInt(ResultSetImpl.java:2580) ~[mysql-connector-java-5.1.38.jar:5.1.38]
	at grails.orm.PagedResultList.<init>(PagedResultList.java:43) ~[grails-datastore-gorm-hibernate5-5.0.1.RELEASE.jar:na]
	... 6 common frames omitted
```

**Comment by hakanernam** [comment]
Sample project is in:

https://github.com/hakanernam/app311.git

**Comment by zyro23** [comment]
related to this: https://github.com/hibernate/hibernate-orm/commit/e678a5b8cf23fbc7f2931689f4d8dae948ef2a05#commitcomment-15938574
but if it really is a hibernate issue or not, wont harm if just applies `useNamed=true` anyway.
woraround in the meantime:
```groovy
class Book {

    BookType type

    static mapping = {
        type type: EnumType, params: [enumClass: BookType.class.name, useNamed: "true"]
    }
}
```

**Comment by emorgado** [comment]
I have a domain class, wich a hasMany enum type with the same problem.
ex:
`
class Book {
     String name
     static hasMany = [sampleList: SampleEnum] 
}

enum SampleEnum {
   A, B;
}
`
what kind of workaround can i use?

**Comment by emorgado** [comment]
Thank's graeme.
