### ISSUE TITLE
Mapping composite key beyond 3 columns

### ISSUE THREAD

**Issue by joaquim-dalmark** [grails/grails-data-mapping#648]
Hi there!

I have 4 tables, each one of them have columns as primary keys and foreign keys at the same time, except "EM". See: [SQLPA.pdf](https://github.com/grails/grails-data-mapping/files/127023/SQLPA.pdf)

**PART 1:**

If I work with the first 3 tables EM, ES and PV it's ok, but when i add the 4th table (PI) i get this error:

_Caused by: org.hibernate.MappingException: Foreign key (FK_6ik73x01vfinmdae9lwgcy9xq:PI [CD_EM,CD_ES,NR_PV,pv_es_id,pv_code])) must have same number of columns as th
e referenced primary key (PV [CD_EM,CD_ES,NR_PV])
        at org.hibernate.mapping.ForeignKey.alignColumns(ForeignKey.java:110) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
        at org.hibernate.mapping.ForeignKey.alignColumns(ForeignKey.java:93) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
        at org.hibernate.cfg.Configuration.secondPassCompileForeignKeys(Configuration.java:1818) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
        at org.hibernate.cfg.Configuration.originalSecondPassCompile(Configuration.java:1741) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
        at org.hibernate.cfg.Configuration.secondPassCompile(Configuration.java:1426) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
        at org.grails.orm.hibernate.cfg.HibernateMappingContextConfiguration.secondPassCompile(HibernateMappingContextConfiguration.java:287) ~[grails-datastore-gorm
-hibernate4-5.0.1.RELEASE.jar:na]
        at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1846) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
        at org.grails.orm.hibernate.cfg.HibernateMappingContextConfiguration.buildSessionFactory(HibernateMappingContextConfiguration.java:196) ~[grails-datastore-go
rm-hibernate4-5.0.1.RELEASE.jar:na]
        at org.grails.orm.hibernate.HibernateMappingContextSessionFactoryBean.doBuildSessionFactory(HibernateMappingContextSessionFactoryBean.java:476) ~[grails-data
store-gorm-hibernate4-5.0.1.RELEASE.jar:na]
        at org.grails.orm.hibernate.HibernateMappingContextSessionFactoryBean.buildSessionFactory(HibernateMappingContextSessionFactoryBean.java:470) ~[grails-datast
ore-gorm-hibernate4-5.0.1.RELEASE.jar:na]
        at org.grails.orm.hibernate.HibernateMappingContextSessionFactoryBean.afterPropertiesSet(HibernateMappingContextSessionFactoryBean.java:93) ~[grails-datastor
e-gorm-hibernate4-5.0.1.RELEASE.jar:na]
        at org.springframework.beaory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637) ~[spring-beans-4.2.4
.RELEASE.jar:4.2.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574) ~[spring-beans-4
.2.4.RELEASE.jar:4.2.4.RELEASE]
        ... 35 common frames omitted_

**PART2:**

Look that if I comment / uncomment a field from the columns mapping (PI.groovy):

`static mapping = {
        id composite: ['pv', 'code']
        table 'PI'
        columns {
            pv {
                column name: 'CD_EM'
                column name: 'CD_ES'
/*                column name: 'NR_PV'*/
            }
        }
        code column: 'NR_PI'
    }`

 the error changes:

_Caused by: org.hibernate.MappingException: Foreign key (FK_leq3iaarv13ve1ljdufey7w3m:PI [CD_EM,CD_ES])) must have same number of columns as the referenced primary ke
y (PV [CD_EM,CD_ES,NR_PV])
        at org.hibernate.mapping.ForeignKey.alignColumns(ForeignKey.java:110) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
        at org.hibernate.mapping.ForeignKey.alignColumns(ForeignKey.java:93) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
        at org.hibernate.cfg.Configuration.secondPassCompileForeignKeys(Configuration.java:1818) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
        at org.hibernate.cfg.Configuration.originalSecondPassCompile(Configuration.java:1741) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
        at org.hibernate.cfg.Configuration.secondPassCompile(Configuration.java:1426) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
        at org.grails.orm.hibernate.cfg.HibernateMappingContextConfiguration.secondPassCompile(HibernateMappingContextConfiguration.java:287) ~[grails-datastore-gorm
-hibernate4-5.0.1.RELEASE.jar:na]
        at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1846) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
        at org.grails.orm.hibernate.cfg.HibernateMappingContextConfiguration.buildSessionFactory(HibernateMappingContextConfiguration.java:196) ~[grails-datastore-go
rm-hibernate4-5.0.1.RELEASE.jar:na]
        at org.grails.orm.hibernate.HibernateMappingContextSessionFactoryBean.doBuildSessionFactory(HibernateMappingContextSessionFactoryBean.java:476) ~[grails-data
store-gorm-hibernate4-5.0.1.RELEASE.jar:na]
        at org.grails.orm.hibernate.HibernateMappingContextSessionFactoryBean.buildSessionFactory(HibernateMappingContextSessionFactoryBean.java:470) ~[grails-datast
ore-gorm-hibernate4-5.0.1.RELEASE.jar:na]
        at org.grails.orm.hibernate.HibernateMappingContextSessionFactoryBean.afterPropertiesSet(HibernateMappingContextSessionFactoryBean.java:93) ~[grails-datastor
e-gorm-hibernate4-5.0.1.RELEASE.jar:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapaFactory.java:1637) ~[spring-beans-4.2.4
.RELEASE.jar:4.2.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574) ~[spring-beans-4
.2.4.RELEASE.jar:4.2.4.RELEASE]
        ... 35 common frames omitted_

The column mapping changes:

[CD_EM,CD_ES]

x

[CD_EM,CD_ES,NR_PV,pv_es_id,pv_code]

Is my code wrong or do we have a bug here? I'm running Grails 3.1.1 with rest-api profile. For the test i've used h2 database.

Code: [code.zip](https://github.com/grails/grails-data-mapping/files/127046/code.zip)

The real names of tables and classes were omitted.

Thank you for your attention.

**Comment by joaquim-dalmark** [comment]
Is there any chance of giving GORM support for @JoinColumnsOrFormulas? Schemas that does use natural keys are common to have overlapping foreign keys, and I'm having trouble with this. Is there any workaround at this moment?
