### ISSUE TITLE
Grails 3.0 support

### ISSUE THREAD

**Issue by miffels** [grails/grails-data-mapping#65]
Hi,

I just created a fresh Grails ``3.0.1`` project and added ``compile ":mongodb:3.0.3"`` as a dependency. The build fails with the error ``Error initializing classpath: org.gradle.api.internal.artifacts.DefaultModuleVersionSelector``, which I assume implies that there is no ``3.x`` version available yet. Is that correct?

Cheers,
Michael

**Comment by jeffbrown** [comment]
You probably want something like this:

        compile 'org.grails.plugins:mongodb'

or...

        compile 'org.grails.plugins:mongodb:4.0.0'

**Comment by jeffbrown** [comment]
The versions available for Grails 3 are listed at https://bintray.com/grails/plugins/org.grails.plugins%3Amongodb/view.

**Comment by miffels** [comment]
Thanks a bunch! I just started getting familiar with Grails via Grails in Action and they used ``compile ":mongodb:1.something.something", so I figured the most recent version of that artifact would be what I was looking for.

Am I correct when I assume that I can find the most recent plugins for the current ``3.x`` release on this page, too?

**Comment by jeffbrown** [comment]
> Am I correct when I assume that I can find the most recent plugins for the current 3.x release on this page, too?

If by "this page" you mean the page that I linked above then I should clarify that the link points specifically to the mongodb plugin releases.  The page at https://bintray.com/grails/plugins will allow you to browse all of the most recent Grails 3 plugins.

**Comment by kastork** [comment]
I have the same problem with neo4j

I add a dependency on the latest neo4j on the grails plugin page:

    compile "org.grails.plugins:neo4j:4.0.0"

and get the complaint

    Error initializing classpath: org.gradle.api.internal.artifacts.DefaultModuleVersionSelector

Tried it with the other tags listed on bintray as well as leaving off the version number -- same result.

I'm not even running a target, just trying to start the grails CLI.

```
 % grails -version
| Grails Version: 3.0.1
| Groovy Version: 2.4.3
| JVM Version: 1.8.0_40


 % grails --stacktrace                                                                                                                        moves-sim-webtools/quincy (master ⚡) lanchester

BUILD SUCCESSFUL

Total time: 2.088 secs
| Error Error initializing classpath: org.gradle.api.internal.artifacts.DefaultModuleVersionSelector (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
java.io.NotSerializableException: org.gradle.api.internal.artifacts.DefaultModuleVersionSelector
	at org.gradle.tooling.internal.provider.PayloadSerializer.serialize(PayloadSerializer.java:82)
	at org.gradle.tooling.internal.provider.ClientProvidedBuildAction.run(ClientProvidedBuildAction.java:59)
	at org.gradle.tooling.internal.provider.ClientProvidedBuildAction.run(ClientProvidedBuildAction.java:31)
	at org.gradle.tooling.internal.provider.ConfiguringBuildAction.run(ConfiguringBuildAction.java:119)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:48)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:71)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
| Error Error initializing classpath: org.gradle.api.internal.artifacts.DefaultModuleVersionSelector
 
```

But, if I use Gradle, I see different problems (transitive dependencies missing)

```
% gradle build                                                                                                                               moves-sim-webtools/quincy (master ⚡) lanchester
:quincy:assetCompile

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':quincy:runtime'.
> Could not find org.neo4j:neo4j-jdbc:2.1.4.
  Searched in the following locations:
      file:/Users/kirk/.m2/repository/org/neo4j/neo4j-jdbc/2.1.4/neo4j-jdbc-2.1.4.pom
      file:/Users/kirk/.m2/repository/org/neo4j/neo4j-jdbc/2.1.4/neo4j-jdbc-2.1.4.jar
      https://jcenter.bintray.com/org/neo4j/neo4j-jdbc/2.1.4/neo4j-jdbc-2.1.4.pom
      https://jcenter.bintray.com/org/neo4j/neo4j-jdbc/2.1.4/neo4j-jdbc-2.1.4.jar
      https://repo.grails.org/grails/core/org/neo4j/neo4j-jdbc/2.1.4/neo4j-jdbc-2.1.4.pom
      https://repo.grails.org/grails/core/org/neo4j/neo4j-jdbc/2.1.4/neo4j-jdbc-2.1.4.jar
  Required by:
      quincy:quincy:0.1 > org.grails.plugins:neo4j:4.0.0
> Could not find org.neo4j:neo4j-jdbc:2.1.4.
  Searched in the following locations:
      file:/Users/kirk/.m2/repository/org/neo4j/neo4j-jdbc/2.1.4/neo4j-jdbc-2.1.4.pom
      file:/Users/kirk/.m2/repository/org/neo4j/neo4j-jdbc/2.1.4/neo4j-jdbc-2.1.4.jar
      https://jcenter.bintray.com/org/neo4j/neo4j-jdbc/2.1.4/neo4j-jdbc-2.1.4.pom
      https://jcenter.bintray.com/org/neo4j/neo4j-jdbc/2.1.4/neo4j-jdbc-2.1.4.jar
      https://repo.grails.org/grails/core/org/neo4j/neo4j-jdbc/2.1.4/neo4j-jdbc-2.1.4.pom
      https://repo.grails.org/grails/core/org/neo4j/neo4j-jdbc/2.1.4/neo4j-jdbc-2.1.4.jar
  Required by:
      quincy:quincy:0.1 > org.grails.plugins:neo4j:4.0.0 > org.grails:grails-datastore-gorm-neo4j:4.0.0.RELEASE

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8.822 secs
```

Then I figured out that the dependency is in a strange place, added that to the repositories

    maven { url "http://m2.neo4j.org/content/groups/public"}


Okay now the gradle build works...  and lo; I can start grails with no complaints.

So this might not really be a bug in grails, since the problem was a missing dependency, (perhaps the error message could be more helpful).    But as a "supported" plugin (whatever that means in the post-Pivotal era) it seems odd to require a custom repo. Anyway it would be helpful to at least  doc the need to add a non-standard repo.
