### ISSUE TITLE
Using joinTable on domain classes with composite id failing with Foreign key must have same number of columns as the referenced primary key

### ISSUE THREAD

**Issue by sleonidy** [grails/grails-data-mapping#663]
Hi,
Domain classes definition:

``` groovy
class Parent {
    String name
    String last
    static hasMany = [children:Child]
    static mapping = {
        id composite: ['name','last']
        children joinTable: [name:'child_parent']

    }
}

class Child {

    static mapping = {

    }
    static constraints = {
    }
}
```

Failing with next exception:
Caused by: org.hibernate.MappingException: Foreign key (FK_lb4oarkcdnyk8beatokwigov9:child_parent [parent_children_id,parent_name,parent_last])) must have same number of columns as the referenced primary key (parent [name,last])
    at org.hibernate.mapping.ForeignKey.alignColumns(ForeignKey.java:110)
    at org.hibernate.mapping.ForeignKey.alignColumns(ForeignKey.java:93)
    at org.hibernate.cfg.Configuration.secondPassCompileForeignKeys(Configuration.java:1818)
    at org.hibernate.cfg.Configuration.originalSecondPassCompile(Configuration.java:1741)
    at org.hibernate.cfg.Configuration.secondPassCompile(Configuration.java:1426)
    at org.grails.orm.hibernate.cfg.HibernateMappingContextConfiguration.secondPassCompile(HibernateMappingContextConfiguration.java:287)
    at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1846)
    at org.grails.orm.hibernate.cfg.HibernateMappingContextConfiguration.buildSessionFactory(HibernateMappingContextConfiguration.java:196)
    at org.grails.orm.hibernate.HibernateMappingContextSessionFactoryBean.doBuildSessionFactory(HibernateMappingContextSessionFactoryBean.java:476)
    at org.grails.orm.hibernate.HibernateMappingContextSessionFactoryBean.buildSessionFactory(HibernateMappingContextSessionFactoryBean.java:470)
    at org.grails.orm.hibernate.HibernateMappingContextSessionFactoryBean.afterPropertiesSet(HibernateMappingContextSessionFactoryBean.java:93)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
    ... 41 common frames omitted

After some debugging - it looks like gorm is creating single ConfigColumn in join table for composite key (and naming it as concatenation of composite key column names), instead of two columns. (at org.grails.orm.hibernate.cfg.HibernateMappingBuilder line 557)

If I don't specify the joinTable, then the table created successfully.

Project with the issue attached.
Thanks
[mappinggorm.zip](https://github.com/grails/grails-data-mapping/files/161488/mappinggorm.zip)

**Comment by U47** [comment]
Running into this same issue. May also have something to do with #660, @graemerocher?

**Comment by timbonicus** [comment]
#829 and #835 seem to be similar issues. To add to the pile, here's a project that throws a similar error without a `joinTable` definition.
[test-composite-fk.zip](https://github.com/grails/grails-data-mapping/files/720336/test-composite-fk.zip)

Strangely, it runs if I comment out the `constraints` block from Project.

**Comment by graemerocher** [comment]
Fixed by https://github.com/grails/gorm-hibernate5/commit/c3c1c5f0fdd341e8b692bcd7c0ba16a5c1348778
