### ISSUE TITLE
Possible memory leak while using mongo datastore

### ISSUE THREAD

**Issue by pdemilly** [grails/grails-data-mapping#67]
Using grails 2.5.0 with mongodb plugin 3.0.3 (no hibernate)

I am processing in batch in a service an update of a Mongodb store. If I use GORM operation on the object to update like get or find, after around 100,000 operation I run out of memory. Replacing the code by straight gmongo calls has no incidence on the memory.

The pseudo code is like that

    xxx.each { custno -> 
    Customer.withTransaction { status ->
         def found = Customer.findByCustomerNo (custno) ?: new Customer()
         found.xxx = xxx
         // found.save (validate: true, failOnError: true) // not even necessary to save to break
   }

   if I replace by straight mongo I get no errors

   def found = mongo.DB.customers.find (customerNO: custno)

I tried to clear the session, and the propertyInstanceMap and I am still running out of memory

By the wayadding hibernate doesn't help. The error message I get is GC overhead limit exceeded. In my case I can see a degradation after 100,000 records processed. Slowly but surely it is taking longer and longer to process the records and memory gets eaten away even if I invoke the garbage collector. 

     processing [102764] (47%) errors (0) freeMem: 284M 11.343 seconds...
     processing [104951] (48%) errors (0) freeMem: 284M 14.167 seconds...
     processing [107137] (49%) errors (0) freeMem: 272M 16.198 seconds...
     processing [109323] (50%) errors (0) freeMem: 261M 17.081 seconds... 
     processing [111510] (51%) errors (0) freeMem: 250M 16.953 seconds...
     processing [113696] (52%) errors (0) freeMem: 239M 17.036 seconds...
     processing [115883] (53%) errors (0) freeMem: 228M 17.093 seconds...
     processing [118069] (54%) errors (0) freeMem: 217M 19.679 seconds...
     processing [120256] (55%) errors (0) freeMem: 206M 20.719 seconds...
     processing [122442] (56%) errors (0) freeMem: 194M 20.776 seconds...
     processing [124629] (57%) errors (0) freeMem: 183M 19.527 seconds...
     processing [126815] (58%) errors (0) freeMem: 172M 19.255 seconds...
     processing [129002] (59%) errors (0) freeMem: 169M 22.731 seconds...
     processing [131188] (60%) errors (0) freeMem: 157M 24.707 seconds...
     processing [133375] (61%) errors (0) freeMem: 146M 21.738 seconds...
     processing [135561] (62%) errors (0) freeMem: 135M 20.755 seconds...
     processing [137747] (63%) errors (0) freeMem: 124M 22.875 seconds...
     processing [139934] (64%) errors (0) freeMem: 113M 23.153 seconds...
     processing [142120] (65%) errors (0) freeMem: 103M 24.800 seconds...
     processing [144307] (66%) errors (0) freeMem: 95M 28.555 seconds...
     processing [146493] (67%) errors (0) freeMem: 84M 27.959 seconds...
     processing [148680] (68%) errors (0) freeMem: 73M 32.398 seconds...
     processing [150866] (69%) errors (0) freeMem: 62M 32.637 seconds...
     processing [153053] (70%) errors (0) freeMem: 53M 44.323 seconds...
     processing [155239] (71%) errors (0) freeMem: 41M 47.576 seconds...
     processing [157426] (72%) errors (0) freeMem: 31M 1 minutes, 1.743 seconds...
     processing [159612] (73%) errors (0) freeMem: 20M 1 minutes, 41.116 seconds...
`

**Comment by pdemilly** [comment]
I created a small grails application that showcase the problem if someone want to look at it

https://github.com/pdemilly/test-mongo-memory-leak.git

Thanks

Pascal

**Comment by SAgrawal14** [comment]
For some reason, Grails is shipping old version of mongo java driver which is having an on issue of memory leak. Try using the latest version something like this.

(I was intended to create Jira for this)

Exclude java driver from mongo

```
compile (":mongodb:3.0.3") {
    excludes("mongo-java-driver")
}
```

And use latest java driver

    dependencies {
        compile "org.mongodb:mongo-java-driver:2.13.1"
    }

Try this.

**Comment by pdemilly** [comment]
Thanks Sagrawal14. I just tried with the updated version of Mongo java driver and same problem. I updated my test program to include a noleak test using pure gmongo find versus a leak test using GORM
Over 160,000 GORM iterations will crash the JVM with .

GC overhead limit exceeded. Stacktrace follows:
Message: Executing action [index] of controller [TestController]  caused exception: Runtime error executing action
    Line | Method
->>  198 | doFilter  in grails.plugin.cache.web.filter.PageFragmentCachingFilter
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|     63 | doFilter  in grails.plugin.cache.web.filter.AbstractFilter
|   1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    615 | run       in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run . . . in java.lang.Thread
Caused by ControllerExecutionException: Runtime error executing action
->>  198 | doFilter  in grails.plugin.cache.web.filter.PageFragmentCachingFilter
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|     63 | doFilter  in grails.plugin.cache.web.filter.AbstractFilter
|   1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    615 | run       in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run . . . in java.lang.Thread
Caused by InvocationTargetException: null
->>  198 | doFilter  in grails.plugin.cache.web.filter.PageFragmentCachingFilter
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|     63 | doFilter  in grails.plugin.cache.web.filter.AbstractFilter
|   1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    615 | run       in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run . . . in java.lang.Thread
Caused by OutOfMemoryError: GC overhead limit exceeded
->> 2694 | copyOfRange in java.util.Arrays
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    203 | <init>    in java.lang.String
|    228 | asAscii . in org.bson.io.PoolOutputBuffer
|    516 | readCStr  in org.bson.BasicBSONDecoder$BSONInput
|    197 | decodeElement in org.bson.BasicBSONDecoder
|    153 | _decode   in     ''
|    131 | decode .  in     ''
|     61 | decode    in com.mongodb.DefaultDBDecoder
|     85 | <init> .  in com.mongodb.Response
|    164 | execute   in com.mongodb.DBPort$1
|    158 | execute . in     ''
|    187 | doOperation in com.mongodb.DBPort
|    158 | call . .  in     ''
|    290 | innerCall in com.mongodb.DBTCPConnector
|    269 | call . .  in     ''
|    235 | call      in     ''
|    145 | getMore . in com.mongodb.QueryResultIterator
|    135 | hasNext   in     ''
|    626 | _hasNext  in com.mongodb.DBCursor
|    657 | hasNext   in     ''
^     20 | leak . .  in LeakService$$EPB9PjGq

**Comment by pdemilly** [comment]
I changed the program to not use a cursor as the previous stacktrace was making GMongo the culprit. Here I preallocate the list of keys I want to search for and then issue my GORM calls. After a while I get this

sample size: 800000
processing [1] (0%) 213M free 8.407 seconds
processing [40001] (5%) 91M free 32.121 seconds
| Error 2015-04-28 12:43:22,807 [http-bio-8181-exec-6] ERROR errors.GrailsExceptionResolver  - OutOfMemoryError occurred when processing request: [GET] /test-mongo-memory-leak/test/
GC overhead limit exceeded. Stacktrace follows:
org.codehaus.groovy.grails.web.servlet.mvc.exceptions.ControllerExecutionException: Executing action [index] of controller [TestController]  caused exception: Runtime error executing action
	at org.codehaus.groovy.grails.web.servlet.mvc.AbstractGrailsControllerHelper.executeAction(AbstractGrailsControllerHelper.java:260)
	at org.codehaus.groovy.grails.web.servlet.mvc.AbstractGrailsControllerHelper.handleURI(AbstractGrailsControllerHelper.java:205)
	at org.codehaus.groovy.grails.web.servlet.mvc.AbstractGrailsControllerHelper.handleURI(AbstractGrailsControllerHelper.java:126)
	at org.codehaus.groovy.grails.web.servlet.mvc.SimpleGrailsController.handleRequest(SimpleGrailsController.java:72)
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:50)
	at org.codehaus.groovy.grails.web.servlet.GrailsDispatcherServlet.doDispatch(GrailsDispatcherServlet.java:347)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:877)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:857)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:486)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:411)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:338)
	at org.codehaus.groovy.grails.web.mapping.UrlMappingUtils.forwardRequestForUrlMappingInfo(UrlMappingUtils.java:178)
	at org.codehaus.groovy.grails.web.mapping.UrlMappingUtils.forwardRequestForUrlMappingInfo(UrlMappingUtils.java:144)
	at org.codehaus.groovy.grails.web.mapping.UrlMappingUtils.forwardRequestForUrlMappingInfo(UrlMappingUtils.java:135)
	at org.codehaus.groovy.grails.web.mapping.filter.UrlMappingsFilter.doFilterInternal(UrlMappingsFilter.java:216)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.codehaus.groovy.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:69)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.codehaus.groovy.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.codehaus.groovy.grails.web.servlet.mvc.exceptions.ControllerExecutionException: Runtime error executing action
	at org.codehaus.groovy.grails.web.servlet.mvc.MixedGrailsControllerHelper.invoke(MixedGrailsControllerHelper.java:159)
	at org.codehaus.groovy.grails.web.servlet.mvc.AbstractGrailsControllerHelper.handleAction(AbstractGrailsControllerHelper.java:375)
	at org.codehaus.groovy.grails.web.servlet.mvc.AbstractGrailsControllerHelper.executeAction(AbstractGrailsControllerHelper.java:252)
	... 69 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springsource.loaded.ri.OriginalClassInvoker.invoke(OriginalClassInvoker.java:47)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1299)
	at org.codehaus.groovy.grails.web.servlet.mvc.MixedGrailsControllerHelper.invoke(MixedGrailsControllerHelper.java:154)
	... 71 more
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.codehaus.groovy.grails.commons.spring.OptimizedAutowireCapableBeanFactory$4.call(OptimizedAutowireCapableBeanFactory.java:216)
	at org.codehaus.groovy.grails.commons.spring.OptimizedAutowireCapableBeanFactory$4.call(OptimizedAutowireCapableBeanFactory.java:214)
	at org.codehaus.groovy.grails.commons.spring.OptimizedAutowireCapableBeanFactory.resolveAutowireablePropertyDescriptorsForClass(OptimizedAutowireCapableBeanFactory.java:236)
	at org.codehaus.groovy.grails.commons.spring.OptimizedAutowireCapableBeanFactory.resolveAutowireablePropertyDescriptors(OptimizedAutowireCapableBeanFactory.java:214)
	at org.codehaus.groovy.grails.commons.spring.OptimizedAutowireCapableBeanFactory.populateBeanInAutowireByName(OptimizedAutowireCapableBeanFactory.java:166)
	at org.codehaus.groovy.grails.commons.spring.OptimizedAutowireCapableBeanFactory.autowireBeanProperties(OptimizedAutowireCapableBeanFactory.java:120)
	at org.grails.datastore.gorm.events.DomainEventListener.autowireBeanProperties(DomainEventListener.java:213)
	at org.grails.datastore.gorm.events.DomainEventListener.afterLoad(DomainEventListener.java:208)
	at org.grails.datastore.gorm.events.DomainEventListener.onPersistenceEvent(DomainEventListener.java:101)
	at org.grails.datastore.mapping.engine.event.AbstractPersistenceEventListener.onApplicationEvent(AbstractPersistenceEventListener.java:47)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:151)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:128)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:331)
	at org.grails.datastore.mapping.engine.EntityPersister.firePostLoadEvent(EntityPersister.java:314)
	at org.grails.datastore.mapping.engine.NativeEntryEntityPersister.refreshObjectStateFromNativeEntry(NativeEntryEntityPersister.java:644)
	at org.grails.datastore.mapping.mongo.engine.MongoEntityPersister.refreshObjectStateFromNativeEntry(MongoEntityPersister.java:110)
	at org.grails.datastore.mapping.mongo.engine.MongoEntityPersister.refreshObjectStateFromNativeEntry(MongoEntityPersister.java:80)
	at org.grails.datastore.mapping.engine.NativeEntryEntityPersister.createObjectFromEmbeddedNativeEntry(NativeEntryEntityPersister.java:392)
	at org.grails.datastore.mapping.engine.NativeEntryEntityPersister.refreshObjectStateFromNativeEntry(NativeEntryEntityPersister.java:459)
	at org.grails.datastore.mapping.mongo.engine.MongoEntityPersister.refreshObjectStateFromNativeEntry(MongoEntityPersister.java:113)
	at org.grails.datastore.mapping.mongo.engine.MongoEntityPersister.refreshObjectStateFromNativeEntry(MongoEntityPersister.java:80)
	at org.grails.datastore.mapping.engine.NativeEntryEntityPersister.createObjectFromNativeEntry(NativeEntryEntityPersister.java:385)
	at org.grails.datastore.mapping.mongo.query.MongoQuery$MongoResultList.convertDBObject(MongoQuery.java:1949)
	at org.grails.datastore.mapping.mongo.query.MongoQuery$MongoResultList.get(MongoQuery.java:1822)
	at org.grails.datastore.gorm.finders.AbstractFindByFinder.invokeQuery(AbstractFindByFinder.java:37)
	at org.grails.datastore.gorm.finders.AbstractFindByFinder$1.doInSession(AbstractFindByFinder.java:24)
	at org.grails.datastore.mapping.core.DatastoreUtils.execute(DatastoreUtils.java:302)
	at org.grails.datastore.gorm.finders.AbstractFinder.execute(AbstractFinder.java:41)
	at org.grails.datastore.gorm.finders.AbstractFindByFinder.doInvokeInternal(AbstractFindByFinder.java:22)
	at org.grails.datastore.gorm.finders.DynamicFinder.invoke(DynamicFinder.java:152)
	at org.grails.datastore.gorm.finders.DynamicFinder.invoke(DynamicFinder.java:352)
	at org.grails.datastore.gorm.finders.FinderMethod$invoke.call(Unknown Source)

**Comment by SAgrawal14** [comment]
Sorry @pdemilly, I had misinterpreted your comment. I thought you was talking about memory leak after shutting down the application. The another thing is that coincidently, we came across the same exception some hours before for one of our production server in which we are iterating over 20,000 records.

In my case, it failed around 8000 records.

:+1:

**Comment by ddiman** [comment]
I'm very interested in resolution to this also; I am facing the same problem.

**Comment by pdemilly** [comment]
I opened an issue in JIRA. Go and vote for it.

https://jira.grails.org/browse/GPMONGODB-409

**Comment by chubbard** [comment]
In batch processing scenario I've had to make sure I periodically flush and clear the session or else the cache that GORM will fill up eventually.  So something like this usually works:

```groovy
SomeDomain.withSession { session ->
    ...
    session.flush() // make sure you flush so saves are saved to the DB BEFORE you clear
    session.clear()
}
```

**Comment by ddiman** [comment]
As pdemilly mentioned (and I can confirm), flushing and clearing the session does not solve the problem.

> I tried to clear the session, and the propertyInstanceMap and I am still running out of memory

**Comment by SAgrawal14** [comment]
We recently upgraded our whole application i.e. Grails to 2.5.0, MongoDB to 3.0.2, Grails mongodb plugin to 3.0.3 and mongo java driver to 2.13.1. Like my previous reply we were facing the same issue but after upgrade as above, that issue no longer exists. Looks like there was a problem with older version MongoDB 3.0.2 or java driver.

Hope this helps to someone else.
