### ISSUE TITLE
Spring boot plugin for Hibernate 5

### ISSUE THREAD

**Issue by bestan** [grails/grails-data-mapping#673]
## Issue

I'm using Spring boot with Java 8, which means that Hibernate 5 is a requirement for the application, since Hibernate 4 doesn't support Java 8 classes out of the box.

`gorm-hibernate4-spring-boot` throws an exception `java.lang.NoClassDefFoundError: org/hibernate/cfg/Mappings` (see full stack trace below), which makes sense, because plugin's name implies that it was built for Hibernate 4 and class Mappings was removed in Hibernate 5.

Are there any plans for developing Spring boot plugin that supports Hibernate 5? How can I contribute?

## Stack trace

```
java.lang.NoClassDefFoundError: org/hibernate/cfg/Mappings
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[na:1.8.0_73]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[na:1.8.0_73]
	at java.lang.Class.privateGetPublicMethods(Class.java:2902) ~[na:1.8.0_73]
	at java.lang.Class.getMethods(Class.java:1615) ~[na:1.8.0_73]
	at java.beans.Introspector.getPublicDeclaredMethods(Introspector.java:1336) ~[na:1.8.0_73]
	at java.beans.Introspector.getTargetMethodInfo(Introspector.java:1197) ~[na:1.8.0_73]
	at java.beans.Introspector.getBeanInfo(Introspector.java:426) ~[na:1.8.0_73]
	at java.beans.Introspector.getBeanInfo(Introspector.java:173) ~[na:1.8.0_73]
	at java.beans.Introspector.getBeanInfo(Introspector.java:260) ~[na:1.8.0_73]
	at java.beans.Introspector.<init>(Introspector.java:407) ~[na:1.8.0_73]
	at java.beans.Introspector.getBeanInfo(Introspector.java:173) ~[na:1.8.0_73]
	at groovy.lang.MetaClassImpl$15.run(MetaClassImpl.java:3289) ~[groovy-all-2.4.6.jar:2.4.6]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_73]
	at groovy.lang.MetaClassImpl.addProperties(MetaClassImpl.java:3287) ~[groovy-all-2.4.6.jar:2.4.6]
	at groovy.lang.MetaClassImpl.initialize(MetaClassImpl.java:3263) ~[groovy-all-2.4.6.jar:2.4.6]
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClassUnderLock(ClassInfo.java:254) ~[groovy-all-2.4.6.jar:2.4.6]
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:285) ~[groovy-all-2.4.6.jar:2.4.6]
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.getMetaClass(MetaClassRegistryImpl.java:257) ~[groovy-all-2.4.6.jar:2.4.6]
	at org.codehaus.groovy.runtime.InvokerHelper.getMetaClass(InvokerHelper.java:881) ~[groovy-all-2.4.6.jar:2.4.6]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallStaticSite(CallSiteArray.java:75) [groovy-all-2.4.6.jar:2.4.6]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallSite(CallSiteArray.java:162) [groovy-all-2.4.6.jar:2.4.6]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) [groovy-all-2.4.6.jar:2.4.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) [groovy-all-2.4.6.jar:2.4.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133) [groovy-all-2.4.6.jar:2.4.6]
	at grails.orm.bootstrap.HibernateDatastoreSpringInitializer$_getBeanDefinitions_closure1.doCall(HibernateDatastoreSpringInitializer.groovy:221) ~[grails-datastore-gorm-hibernate4-5.0.3.RELEASE.jar:na]
	at grails.orm.bootstrap.HibernateDatastoreSpringInitializer$_getBeanDefinitions_closure1.doCall(HibernateDatastoreSpringInitializer.groovy) ~[grails-datastore-gorm-hibernate4-5.0.3.RELEASE.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_73]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_73]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93) ~[groovy-all-2.4.6.jar:2.4.6]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) ~[groovy-all-2.4.6.jar:2.4.6]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294) ~[groovy-all-2.4.6.jar:2.4.6]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021) ~[groovy-all-2.4.6.jar:2.4.6]
	at groovy.lang.Closure.call(Closure.java:426) ~[groovy-all-2.4.6.jar:2.4.6]
	at groovy.lang.Closure.call(Closure.java:420) ~[groovy-all-2.4.6.jar:2.4.6]
	at org.springframework.beans.factory.groovy.GroovyBeanDefinitionReader.invokeBeanDefiningClosure(GroovyBeanDefinitionReader.java:446) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.groovy.GroovyBeanDefinitionReader.beans(GroovyBeanDefinitionReader.java:279) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.groovy.GroovyBeanDefinitionReader$beans.call(Unknown Source) ~[na:na]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) [groovy-all-2.4.6.jar:2.4.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) [groovy-all-2.4.6.jar:2.4.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [groovy-all-2.4.6.jar:2.4.6]
	at org.grails.datastore.gorm.bootstrap.AbstractDatastoreInitializer$GroovyBeanReaderInit.registerBeans(AbstractDatastoreInitializer.groovy:346) ~[grails-datastore-gorm-5.0.3.RELEASE.jar:na]
	at org.grails.datastore.gorm.bootstrap.AbstractDatastoreInitializer.configureForBeanDefinitionRegistry(AbstractDatastoreInitializer.groovy:222) ~[grails-datastore-gorm-5.0.3.RELEASE.jar:na]
	at org.grails.datastore.gorm.boot.autoconfigure.HibernateGormAutoConfiguration.registerBeanDefinitions(HibernateGormAutoConfiguration.groovy:83) ~[gorm-hibernate4-spring-boot-5.0.3.RELEASE.jar:na]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsFromRegistrars(ConfigurationClassBeanDefinitionReader.java:352) ~[spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:143) ~[spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:116) ~[spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:333) ~[spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:243) ~[spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:273) ~[spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:98) ~[spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:678) ~[spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:520) ~[spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[spring-boot-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766) [spring-boot-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361) [spring-boot-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) [spring-boot-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1191) [spring-boot-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1180) [spring-boot-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.boot.SpringApplication$run.call(Unknown Source) [spring-boot-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) [groovy-all-2.4.6.jar:2.4.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) [groovy-all-2.4.6.jar:2.4.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133) [groovy-all-2.4.6.jar:2.4.6]
```

**Comment by mpazitny** [comment]
Is there any known workaround?

**Comment by graemerocher** [comment]
What needs to happen is this subproject needs to be created for Hibernate 5

https://github.com/grails/grails-data-mapping/tree/master/boot-plugins/gorm-hibernate4-spring-boot

Pull requests welcome

**Comment by graemerocher** [comment]
Implemented here  https://github.com/grails/gorm-hibernate5/tree/master/boot-plugin
