### ISSUE TITLE
Grails 3 Geb functional tests with MongoDB

### ISSUE THREAD

**Issue by Eylen** [grails/grails-data-mapping#674]
I'm trying to do some functional tests for an application with Grails 3.1.4 and MongoDB plugin 5.0.3 and I'm facing a problem while trying to create some default values for the domain objects.

This is the basic test I'm trying to do:

```groovy
@Integration
@Rollback
class LoginSpec extends GebSpec {
@Shared
Company company
@Shared
BackendUser backendUser
@Shared
Role rol

    def setupSpec() {
        Company.withNewTransaction {
            company = new Company(name: 'company 1', enterprise: 'enterprise1', contactMail: 'test@test.com', companyKey: 'companyKey').save(flush: true, failOnError: true)
            backendUser = new BackendUser(email: 'test@test.com', firstName: 'user', password: '12345678', newPassword: null)
            backendUser.company = company
            backendUser.save(flush: true, failOnError: true)
            rol = Role.findByAuthority("ROLE_USER")
            println "Role->" + rol
            BackendUserRole.create(backendUser, rol).save()
        }
    }

    def cleanup() {
    }

    void "load login page"() {
        when:
            to LoginPage

        then:
            at LoginPage
    }

    void "do login"() {
        when:
            println BackendUser.list().enabled
            println BackendUser.findByEmail("test@test.com")
            to LoginPage
            username = "test@test.com"
            password = "12345678"
            enterButton.click()

        then:
            at CompanyPage
    }
}
```

And this is the error it gives:

```
Either class [net.tests.domain.Company] is not a domain class or GORM has not been initialized correctly or has already been shutdown. If you are unit testing your entities using the mocking APIs
java.lang.IllegalStateException: Either class [net.ds.gamileku.domain.Company] is not a domain class or GORM has not been initialized correctly or has already been shutdown. If you are unit testing your entities using the mocking APIs
	at org.grails.datastore.gorm.GormEnhancer.stateException(GormEnhancer.groovy:159)
	at org.grails.datastore.gorm.GormEnhancer.findStaticApi(GormEnhancer.groovy:153)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.currentGormStaticApi(GormEntity.groovy:1315)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.withNewTransaction(GormEntity.groovy:911)
	at backend.tests.functional.LoginSpec.setupSpec(LoginSpec.groovy:28)
```

I've seen lots of examples of using Geb with Grails 3 and they look the same as this one so I'm guessing this is an issue with MongoDB integration with Grails 3 and Geb

The relevant part of build.gradle:
```gradle
    testCompile "org.grails.plugins:geb"
    testCompile "org.seleniumhq.selenium:selenium-firefox-driver:2.52.0"
    testRuntime "org.seleniumhq.selenium:selenium-support:2.52.0"
  
    compile "org.grails.plugins:mongodb:5.0.3"
```

**Comment by graemerocher** [comment]
Currently you cannot use `setupSpec` directly in this way. See https://gist.github.com/graemerocher/d0a56cc91b6f06b304b9#file-bookspec-groovy-L29

for a workaround. Either way this is not a bug in GORM itself.

**Comment by Eylen** [comment]
Hadn't seen that one. Thanks for the workaround :)

**Comment by jrgleason** [comment]
So wait I don't get it what is the workaround? Is it the `context = Holders.findApplicationContext()`

**Comment by Eylen** [comment]
@jrgleason I tried with the full setupSpec and cleanupSpec, changing the fixture, and it worked

**Comment by sciros** [comment]
Interesting. Is it a race condition so we wait until the application context is available and the data store is initialized? The flags that Bootstrap uses to set stuff up must not be used to start integration tests in Grails. I'll have to do some reading on the timing of all this stuff...
