### ISSUE TITLE
association id's stopped working in grails 3.1.4

### ISSUE THREAD

**Issue by erichelgeson** [grails/grails-data-mapping#686]
Accessing an association id via `foo.barId` (instead of `foo.bar.id`) seems to have stopped working in grails 3.1.x

The exception is odd because there has to be a hibernate session working as I can access `thing.otherThing.id` but not `thing.otherThingId`

```
ERROR org.grails.web.errors.GrailsExceptionResolver - IllegalStateException occurred when processing request: [GET] /thing/
No Datastore Session bound to thread, and configuration does not allow creation of non-transactional one here. Stacktrace follows:
java.lang.reflect.InvocationTargetException: null
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.grails.web.converters.exceptions.ConverterException: java.lang.IllegalStateException: No Datastore Session bound to thread, and configuration does not allow creation of non-transactional one here
	at grails.converters.JSON.value(JSON.java:184)
	at grails.converters.JSON.render(JSON.java:119)
	at grails.converters.JSON.render(JSON.java:132)
	at grails.artefact.controller.support.ResponseRenderer$Trait$Helper.render(ResponseRenderer.groovy:191)
	at associationid.ThingController.index(ThingController.groovy:13)
	... 3 common frames omitted
Caused by: java.lang.IllegalStateException: No Datastore Session bound to thread, and configuration does not allow creation of non-transactional one here
	at associationid.marshallers.ThingMarshallerJson$__clinit__closure1.doCall(ThingMarshallerJson.groovy:13)
	... 8 common frames omitted
```

Fails in Marshallers, Controllers, GSP. 

Fresh grails 3.1.4 app with 1 commit showing the issue here: https://github.com/erichelgeson/associationid/commits/master

**Comment by erichelgeson** [comment]
Just tried `org.grails.plugins:hibernate4:5.0.4.BUILD-SNAPSHOT` and the same issue exists

Exact deps resolved:
```
Download https://repo.grails.org/grails/core/org/grails/plugins/hibernate4/5.0.4.BUILD-SNAPSHOT/hibernate4-5.0.4.BUILD-20160401.095148-4.pom
Download https://repo.grails.org/grails/core/org/grails/grails-datastore-simple/5.0.4.BUILD-SNAPSHOT/grails-datastore-simple-5.0.4.BUILD-20160401.095002-4.pom
Download https://repo.grails.org/grails/core/org/grails/grails-datastore-gorm-support/5.0.4.BUILD-SNAPSHOT/grails-datastore-gorm-support-5.0.4.BUILD-20160401.094929-4.pom
Download https://repo.grails.org/grails/core/org/grails/grails-datastore-gorm-hibernate4/5.0.4.BUILD-SNAPSHOT/grails-datastore-gorm-hibernate4-5.0.4.BUILD-20160401.094759-4.pom
Download https://repo.grails.org/grails/core/org/grails/grails-datastore-core/5.0.4.BUILD-SNAPSHOT/grails-datastore-core-5.0.4.BUILD-20160401.094627-4.pom
Download https://repo.grails.org/grails/core/org/grails/grails-datastore-gorm/5.0.4.BUILD-SNAPSHOT/grails-datastore-gorm-5.0.4.BUILD-20160401.094642-4.pom
Download https://repo.grails.org/grails/core/org/grails/grails-datastore-gorm-hibernate-core/5.0.4.BUILD-SNAPSHOT/grails-datastore-gorm-hibernate-core-5.0.4.BUILD-20160401.094741-4.pom
Download https://repo.grails.org/grails/core/org/grails/plugins/hibernate4/5.0.4.BUILD-SNAPSHOT/hibernate4-5.0.4.BUILD-20160401.095148-4.jar
Download https://repo.grails.org/grails/core/org/grails/grails-datastore-simple/5.0.4.BUILD-SNAPSHOT/grails-datastore-simple-5.0.4.BUILD-20160401.095002-4.jar
Download https://repo.grails.org/grails/core/org/grails/grails-datastore-gorm-support/5.0.4.BUILD-SNAPSHOT/grails-datastore-gorm-support-5.0.4.BUILD-20160401.094929-4.jar
Download https://repo.grails.org/grails/core/org/grails/grails-datastore-gorm-hibernate4/5.0.4.BUILD-SNAPSHOT/grails-datastore-gorm-hibernate4-5.0.4.BUILD-20160401.094759-4.jar
Download https://repo.grails.org/grails/core/org/grails/grails-datastore-core/5.0.4.BUILD-SNAPSHOT/grails-datastore-core-5.0.4.BUILD-20160401.094627-4.jar
Download https://repo.grails.org/grails/core/org/grails/grails-datastore-gorm/5.0.4.BUILD-SNAPSHOT/grails-datastore-gorm-5.0.4.BUILD-20160401.094642-4.jar
Download https://repo.grails.org/grails/core/org/grails/grails-datastore-gorm-hibernate-core/5.0.4.BUILD-SNAPSHOT/grails-datastore-gorm-hibernate-core-5.0.4.BUILD-20160401.094741-4.jar
```

**Comment by graemerocher** [comment]
I tested locally with your example project and simply added 

```
compile "org.grails:grails-datastore-gorm-hibernate4:5.0.4.BUILD-SNAPSHOT"
```

And it worked for me. You may have an out of date snapshot

**Comment by erichelgeson** [comment]
Ahh, I had the wrong dep. It does work as expected now. Thanks for the clarification.

**Comment by erichelgeson** [comment]
I was looking to add a test for this, but it seems there is already one: 
https://github.com/grails/grails-data-mapping/blob/5.x/grails-datastore-gorm-hibernate4/src/test/groovy/org/grails/orm/hibernate/AssociationIdSpec.groovy#L5

Is there a reason why this test didn't pick up the issue?
