### ISSUE TITLE
Inheritance in classes with MONGO DB with Hibernate maps classes to mongo instead of hibernate

### ISSUE THREAD

**Issue by pavanKal** [grails/grails-data-mapping#712]
I have grails app created using 3.1.4, Hibernate5  & MongoDB plugin 5.0.5 

I have only two domain classes as below 

`

class Book {
	String name
	String author
    static constraints = {
    }
	
	static mapping = {
        tablePerHierarchy(false)
		id generator: 'sequence', params: [sequence: 'PK_BOOK_SEQ']
		
        
    }
}
`

Its child class
`

class FoodBook extends Book{
	String category
    static constraints = {
    }
}
`

Now when i start my app & try to do criteria query as below it throws me below error
` Long  maxId = Book.createCriteria().get {
                                projections {
                                    max "id"
                                }
                            }`

Error Trace 
`
Class:class cgw_sample.FoodBook
sessionFactory.getClassMetadata(it):GroovyAwareJoinedSubclassEntityPersister(cgw_sample.FoodBook)
tableName:food_book
ERROR org.springframework.boot.SpringApplication - Application startup failed
org.springframework.dao.InvalidDataAccessResourceUsageException: Attempt to project on a non-existent project [id]
        at org.grails.datastore.mapping.mongo.query.MongoQuery.executeQuery(MongoQuery.java:936)
        at org.grails.datastore.mapping.query.Query.list(Query.java:567)
        at org.grails.datastore.mapping.query.Query.singleResult(Query.java:585)
        at grails.gorm.CriteriaBuilder.get(CriteriaBuilder.java:297)
        at org.grails.datastore.mapping.query.api.BuildableCriteria$get.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at edu.wustl.cgw.service.OracleDatabaseSequenceService$_resetSequence_closure1.doCall(OracleDatabaseSequenceService.groovy:38)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021)
`

According to which it shows me that My domain class got mapped with Mongo instead of hibernate even if i did not specified MappedWith

**Comment by graemerocher** [comment]
Upload an example that reproduces the issue

**Comment by graemerocher** [comment]
Fixed by https://github.com/grails/grails-data-mapping/commit/5b119fc26a913fc2607d32a53d16351e52369915

**Comment by mehtaabhishek** [comment]
When I add following lines in example to extract the identity information
if (sessionFactory.getClassMetadata(it)) {
	String tableName = sessionFactory.getClassMetadata(it).getTableName()
	println("tableName:"+tableName)
	if (sql.rows("select * from pg_tables where lower(tablename) = ? and schemaname = current_schema()", [tableName?.toLowerCase()]).size() > 0) {
		def domainBinder = new GrailsDomainBinder()
		def identity = domainBinder.getMapping(it)?.identity
		}
}

I started getting the below exception, This seems bit illogical as default constructor should present 

ERROR org.springframework.boot.SpringApplication - Application startup failed
groovy.lang.GroovyRuntimeException: Could not find matching constructor for: org.grails.orm.hibernate.cfg.GrailsDomainBinder()
    at groovy.lang.MetaClassImpl.invokeConstructor(MetaClassImpl.java:1728)
    at groovy.lang.MetaClassImpl.invokeConstructor(MetaClassImpl.java:1531)
    at org.codehaus.groovy.runtime.callsite.MetaClassConstructorSite.callConstructor(MetaClassConstructorSite.java:49)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:239)
    at edu.wustl.cgw.service.OracleDatabaseSequenceService$_resetSequence_closure1.doCall(OracleDatabaseSequenceService.groovy:34)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426)
