### ISSUE TITLE
Could not find matching constructor for: org.grails.orm.hibernate.cfg.GrailsDomainBinder()

### ISSUE THREAD

**Issue by mehtaabhishek** [grails/grails-data-mapping#725]
I have grails app created using 3.1.5, Hibernate5 & MongoDB plugin 5.0.8

When I Try to access all the classes for the identity information
if (sessionFactory.getClassMetadata(it)) {
String tableName = sessionFactory.getClassMetadata(it).getTableName()
println("tableName:"+tableName)
if (sql.rows("select * from pg_tables where lower(tablename) = ? and schemaname = current_schema()", [tableName?.toLowerCase()]).size() > 0) {
def domainBinder = new GrailsDomainBinder()
def identity = domainBinder.getMapping(it)?.identity
}
}

When I start the application, it fail with the below exception,This seems bit illogical as default constructor should be present

ERROR org.springframework.boot.SpringApplication - Application startup failed
groovy.lang.GroovyRuntimeException: Could not find matching constructor for: org.grails.orm.hibernate.cfg.GrailsDomainBinder()
at groovy.lang.MetaClassImpl.invokeConstructor(MetaClassImpl.java:1728)
at groovy.lang.MetaClassImpl.invokeConstructor(MetaClassImpl.java:1531)
at org.codehaus.groovy.runtime.callsite.MetaClassConstructorSite.callConstructor(MetaClassConstructorSite.java:49)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:239)
at edu.wustl.cgw.service.OracleDatabaseSequenceService$_resetSequence_closure1.doCall(OracleDatabaseSequenceService.groovy:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426)

**Comment by graemerocher** [comment]
It is a static method now, just don't instantiate it https://github.com/grails/grails-data-mapping/blob/master/grails-datastore-gorm-hibernate5/src/main/groovy/org/grails/orm/hibernate/cfg/GrailsDomainBinder.java#L1291

**Comment by mehtaabhishek** [comment]
Thanks Graem
