### ISSUE TITLE
Error with mongodb gorm plugin!

### ISSUE THREAD

**Issue by redraushan** [grails/grails-data-mapping#757]
This error is appearing since a few days  and it wont go until I drop the current database and restart the server.

| Grails Version: 3.1.1
| Groovy Version: 2.4.6
| JVM Version: 1.8.0_91

The following is the version of plugin for mongodb :
compile "org.grails.plugins:mongodb:5.0.0.RC1"

Below is the generated  log.

readStartArray can only be called when CurrentBSONType is ARRAY, not when CurrentBSONType is DOCUMENT.. 

Stacktrace follows:
org.bson.BsonInvalidOperationException: readStartArray can only be called when CurrentBSONType is ARRAY, not when CurrentBSONType is DOCUMENT.
        at org.bson.AbstractBsonReader.verifyBSONType(AbstractBsonReader.java:655)
        at org.bson.AbstractBsonReader.checkPreconditions(AbstractBsonReader.java:687)
        at org.bson.AbstractBsonReader.readStartArray(AbstractBsonReader.java:414)
        at com.mongodb.operation.CommandResultArrayCodec.decode(CommandResultArrayCodec.java:48)
        at com.mongodb.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:53)
        at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:81)
        at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:40)
        at org.bson.codecs.configuration.LazyCodec.decode(LazyCodec.java:47)
        at org.bson.codecs.BsonDocumentCodec.readValue(BsonDocumentCodec.java:98)
        at com.mongodb.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:56)
        at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:81)
        at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:40)
        at com.mongodb.connection.CommandProtocol.execute(CommandProtocol.java:123)

**Comment by Schlogen** [comment]
Please include an example to reproduces the issue

**Comment by graemerocher** [comment]
The issue is because for one attribute the underlying data doesn't match your domain model. Your domain model defines a list or array but the data is a document

**Comment by redraushan** [comment]
@graemerocher Thanks sir! It solved the problem

**Comment by ishkabirkumar** [comment]
how to embed a document then?? or a part of it in the system?
