### ISSUE TITLE
ClassCastException when using unique constraint on multiple columns

### ISSUE THREAD

**Issue by goeh** [grails/grails-data-mapping#760]
Grails 3.2.0-M2 (hibernate5)

If I have a unique constraint that is combined with another field/column I get `java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer` when I try to save a Person instance.

``` groovy
class Person {
    Long tenantId
    Integer customerId
    String firstName
    String lastName

    static constraints = {
        customerId(unique: 'tenantId')
    }
}
```

```
java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
    at org.hibernate.type.descriptor.java.IntegerTypeDescriptor.unwrap(IntegerTypeDescriptor.java:19)
    at org.hibernate.type.descriptor.sql.IntegerTypeDescriptor$1.doBind(IntegerTypeDescriptor.java:46)
    at org.hibernate.type.descriptor.sql.BasicBinder.bind(BasicBinder.java:74)
    at org.hibernate.type.AbstractStandardBasicType.nullSafeSet(AbstractStandardBasicType.java:253)
    at org.hibernate.type.AbstractStandardBasicType.nullSafeSet(AbstractStandardBasicType.java:248)
    at org.hibernate.loader.Loader.bindPositionalParameters(Loader.java:2044)
    at org.hibernate.loader.Loader.bindParameterValues(Loader.java:2013)
    at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1943)
    at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1896)
    at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1874)
    at org.hibernate.loader.Loader.doQuery(Loader.java:919)
    at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:336)
    at org.hibernate.loader.Loader.doList(Loader.java:2610)
    at org.hibernate.loader.Loader.doList(Loader.java:2593)
    at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2422)
    at org.hibernate.loader.Loader.list(Loader.java:2417)
    at org.hibernate.loader.criteria.CriteriaLoader.list(CriteriaLoader.java:109)
    at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1787)
    at org.hibernate.internal.CriteriaImpl.list(CriteriaImpl.java:363)
    at org.hibernate.internal.CriteriaImpl.uniqueResult(CriteriaImpl.java:385)
    at grails.orm.HibernateCriteriaBuilder.executeUniqueResultWithProxyUnwrap(HibernateCriteriaBuilder.java:144)
```

If both columns has the same type I don't get an exception. But I'm not sure that the unique check works. Haven't tested that.

Sample app with test here https://github.com/goeh/grails-unique-test

**Comment by graemerocher** [comment]
I don't see this as a bug. Your 2 columns are of a different type. One is `Long tenantId` the other is `Integer customerId`, when Hibernate tries to apply the equals constraint it uses `eq "customerId", tenantId` and since tenantId cannot safely be converted to an Integer without losing precision you get the exception.

**Comment by goeh** [comment]
I don't understand. There is no equals constraint, it's a unique constraint. The property customerId must be unique within the tenantId. I have lots of constraints like this in my Grails 2 apps.

**Comment by graemerocher** [comment]
When you apply a `unique: 'tenantId'` it ends up here:

https://github.com/grails/grails-data-mapping/blob/master/grails-datastore-gorm/src/main/groovy/org/grails/datastore/gorm/validation/constraints/builtin/UniqueConstraint.groovy#L58

The `eq propertyName, value` applies to `customId` with a value that is a `Long` value (the `tenantId`. We cannot convert this `Long` value to an integer safely without losing precision.  So you get a ClassCastException.

If you have lots of these in your app already then your app is at risk to strange bugs when you have a tenantId that has a value greater than a customer id.

**Comment by goeh** [comment]
Sorry but I'm still confused. Shouldn't line 58 be `eq propName, value` instead of `eq propertyName, value` ?
`propertyName` translates to `getPropertyName()` in `AbstractConstraint` and that returns the constraint property ("customerId" in my case). But it should be using "tenantId" in the `eq` statement on line 58.

**Comment by graemerocher** [comment]
You are right of course. Silly me. Fortunately it only impacts testing, and standalone usage. In a Grails app the Grails validator infrastructure is used.

**Comment by goeh** [comment]
Thanks, no worries. Good to know it only impacts my tests.
