### ISSUE TITLE
DetachedCriteria with junction on associated domain queries on the wrong domain

### ISSUE THREAD

**Issue by dpcasady** [grails/grails-data-mapping#776]
### Steps to Reproduce

Take the following two simple domains:

``` groovy
class Book {
    Genre genre
}

class Genre {
    String description
}
```

If you construct a `BuildableCriteria` query that has a critereon inside of a junction on an associated domain, the query is run without issue.

``` groovy
BuildableCriteria query = Book.createCriteria()
Book result = query.get {
    genre {
        or {
            eq("id", 0)
            eq("description", "horror")
        }
    }
}
```

If however you construct a `DetachedCriteria` query and pass it the exact same closure, an exception is thrown. It appears the actual query that is executed attempts to query the `Book` domain for the given `description`, and the property doesn't exist there.

``` groovy
DetachedCriteria<Book> query = Book.where {
    genre {
        or {
            eq("id", 0)
            eq("description", "horror")
        }
    }
}
query.get()
```
### Expected Behaviour

I would expect `DetachedCriteria` to function similarly to `CriteriaBuilder` where the criterion method inside of a junction is tied to the associated domain (`Genre`) and not the "parent" (`Book`) criteria instance.
### Actual Behaviour

Instead, the `eq()` criterion method is invoked on the criteria builder tied to `Book`and an `InvalidDataAccessResourceUsageException` is thrown:

```
org.springframework.dao.InvalidDataAccessResourceUsageException: Cannot query [org.grails.Book] on non-existent property: description

    at org.grails.datastore.mapping.simple.query.SimpleMapQuery.getValidProperty(SimpleMapQuery.groovy:751)
    at org.grails.datastore.mapping.simple.query.SimpleMapQuery.executeSubQueryInternal(SimpleMapQuery.groovy:690)
    at org.grails.datastore.mapping.simple.query.SimpleMapQuery.executeSubQuery(SimpleMapQuery.groovy:676)
    at org.grails.datastore.mapping.simple.query.SimpleMapQuery.executeQuery(SimpleMapQuery.groovy:63)
    at org.grails.datastore.mapping.query.Query.list(Query.java:567)
    at org.grails.datastore.mapping.query.Query.singleResult(Query.java:585)
    at grails.gorm.DetachedCriteria.get_closure2(DetachedCriteria.groovy:853)
    at grails.gorm.DetachedCriteria.withPopulatedQuery_closure10(DetachedCriteria.groovy:1248)
    at groovy.lang.Closure.call(Closure.java:414)
    at groovy.lang.Closure.call(Closure.java:430)
    at org.grails.datastore.gorm.GormStaticApi.withDatastoreSession_closure23(GormStaticApi.groovy:736)
    at groovy.lang.Closure.call(Closure.java:414)
    at org.grails.datastore.mapping.core.DatastoreUtils.execute(DatastoreUtils.java:310)
    at org.grails.datastore.gorm.AbstractDatastoreApi.execute(AbstractDatastoreApi.groovy:37)
    at org.grails.datastore.gorm.GormStaticApi.withDatastoreSession(GormStaticApi.groovy:735)
    at org.grails.datastore.gorm.GormEntity$Trait$Helper.withDatastoreSession(GormEntity.groovy:895)
    at grails.gorm.DetachedCriteria.withPopulatedQuery(DetachedCriteria.groovy:1219)
    at grails.gorm.DetachedCriteria.get(DetachedCriteria.groovy:852)
    at grails.gorm.DetachedCriteria.get(DetachedCriteria.groovy:851)
    at org.grails.BookSpec.DetachedCriteria with an association and a disjunction queries on the wrong domain(BookSpec.groovy:47)
```

If you modify the `DetachedCriteria` to explicitly call `eq()`on `delegate` (which is the criteria tied to `Genre`), the query is executed successfully:

``` groovy
DetachedCriteria<Book> query = Book.where {
    genre {
        or {
            delegate.eq("id", 0)
            delegate.eq("description", horrorGenre.description)
        }
    }
}
query.get()
```

This "workaround" isn't bad but it seems inconsistent that a closure passed to `DetachedCriteria` wouldn't work, while that same one passed to `BuildableCriteria` would.
### Environment Information
- **Operating System**: OS X 10.11.6 (El Capitan)
- **Grails Version:** 3.1.10
- **GORM Version:** 5.0.10.RELEASE
- **JDK Version:** Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
### Example Application

I've created a Grails [bug report](https://github.com/grails/grails-data-mapping/files/443850/associated-junction-criteria-bug-report-29082016.zip) and a full Grails [application](https://github.com/dpcasady/associated-junction-criteria) with a unit test that demonstrates the issue.

**Comment by graemerocher** [comment]
Seems to work fine in recent versions of GORM 6 https://github.com/grails/grails-data-mapping/commit/9ea2f694c54f004d3f465a4a8d917da3c6be3eac
