### ISSUE TITLE
Allow type coercion for parameter to Tenants.withId()

### ISSUE THREAD

**Issue by goeh** [grails/grails-data-mapping#785]
While developing with multi-tenancy in Grails 3.2.0.RC1 I had a domain class with a `Long tenantId` property. Then when using Tenants.withId(1) to force current tenant:
```
Tenants.withId(1) {
    new Person(firstName: "Lisa", lastName: "Long").save(failOnError: true)
}
```
 I got the following exception:
```
java.lang.IllegalArgumentException: Incorrect type for parameter [tenantId]

	at org.hibernate.internal.FilterImpl.setParameter(FilterImpl.java:82)
	at org.grails.orm.hibernate.AbstractHibernateDatastore.enableMultiTenancyFilter(AbstractHibernateDatastore.java:342)
	at org.grails.orm.hibernate.AbstractHibernateDatastore$1.call(AbstractHibernateDatastore.java:368)
	at groovy.lang.Closure.call(Closure.java:430)
	at org.grails.orm.hibernate.GrailsHibernateTemplate$1.doInHibernate(GrailsHibernateTemplate.java:140)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.doExecute(GrailsHibernateTemplate.java:243)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.execute(GrailsHibernateTemplate.java:187)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.executeWithNewSession(GrailsHibernateTemplate.java:137)
	at org.grails.orm.hibernate.AbstractHibernateDatastore.withNewSession(AbstractHibernateDatastore.java:322)
	at org.grails.orm.hibernate.AbstractHibernateDatastore.withNewSession(AbstractHibernateDatastore.java:331)
	at grails.gorm.multitenancy.Tenants.withTenantIdInternal_closure1(Tenants.groovy:182)
	at grails.gorm.multitenancy.Tenants$CurrentTenant.withTenant(Tenants.groovy:273)
	at grails.gorm.multitenancy.Tenants.withTenantIdInternal(Tenants.groovy:181)
	at grails.gorm.multitenancy.Tenants.withId(Tenants.groovy:157)
```
Because tenantId is a Long you must make sure the parameter also is a Long `Tenants.withId(1L)`.

Should GORM be forgiving here and do automatic type coercion to Long?
GORM do type coercion in other places so I think it's natural for the developer to not think about types here. I guess it's only a problem when tenantId is a Long. Integer or String will not have this problem.

**Comment by graemerocher** [comment]
It is difficult to enforce this, because the tenant id is declared in each domain class and can be of any serializable type. It could even be another domain instance or a subclass or some parent type.

On the other hand `withId` is generic and does not know about the types that are declared in the individual domain classes. I'm not sure if there is any easy solution to this problem.

**Comment by goeh** [comment]
Thanks for the explanation. I understand now that this is not possible to implement.
Maybe we can add a note in the documentation because I guess Long will be among the top-three most common types used for tenantId (String, Integer, Long).
