### ISSUE TITLE
Nested Tenants.withId() calls clears current tenant

### ISSUE THREAD

**Issue by goeh** [grails/grails-data-mapping#787]
GORM v6.0.0.RC1

`Tenants.withId()` calls `CurrentTenant.withTenant()` that sets the wanted tenant identifier in a `ThreadLocal` then calls the `Closure` code block. After the code block has executed it removes the tenant identifier from the `ThreadLocal`. This causes problem for nested `withId()` calls. It should save the current tenant and restore it after, not remove it.

https://github.com/grails/grails-data-mapping/blob/01433a75db8a245ca27adbb9f3c1a57fb70e1bbd/grails-datastore-gorm/src/main/groovy/org/grails/datastore/gorm/CurrentTenant.groovy#L44

```
static <T> T withTenant(Serializable tenantId, Closure<T> callable) {
    try {
        set(tenantId)
        callable.call(tenantId)
    } finally {
        remove()
    }
}
```

Example that shows the problem:

```
class PersonService {

    Person getPerson(long tenant, String firstName, String lastName) {
        Tenants.withId(tenant) {
            Person.createCriteria().get {
                eq 'firstName', firstName
                eq 'lastName', lastName
            }
        } as Person
    }

    Person createWithCar(long tenant, String firstName, String lastName, String make, String model) {
        Tenants.withId(tenant) {
            def person = getPerson(tenant, firstName, lastName)
            if (person == null) {
                person = new Person(firstName: firstName, lastName: lastName)
                person.addToCars(new Car(person: person, make: make, model: model))
                person.save(failOnError: true)
            }
            person
        } as Person
    }
}
```

Exception:

```
org.grails.datastore.mapping.multitenancy.exceptions.TenantNotFoundException: Tenant could not be resolved outside a web request

	at org.grails.datastore.mapping.multitenancy.web.SessionTenantResolver.resolveTenantIdentifier(SessionTenantResolver.groovy:39)
	at grails.gorm.multitenancy.Tenants.currentId(Tenants.groovy:58)
	at current.tenant.issue.Person.beforeValidate(Person.groovy:27)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:216)
	at org.grails.datastore.gorm.support.EventTriggerCaller$MethodCaller.call(EventTriggerCaller.java:147)
	at org.grails.datastore.gorm.support.EventTriggerCaller.call(EventTriggerCaller.java:90)
	at org.grails.datastore.gorm.support.BeforeValidateHelper$BeforeValidateEventTriggerCaller.call(BeforeValidateHelper.java:44)
	at org.grails.orm.hibernate.support.ClosureEventListener.onValidate(ClosureEventListener.java:383)
	at org.grails.orm.hibernate.EventTriggeringInterceptor.onValidate(EventTriggeringInterceptor.java:181)
	at org.grails.orm.hibernate.EventTriggeringInterceptor.onPersistenceEvent(EventTriggeringInterceptor.java:92)
	at org.grails.datastore.mapping.engine.event.AbstractPersistenceEventListener.onApplicationEvent(AbstractPersistenceEventListener.java:51)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:382)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:336)
	at org.grails.datastore.gorm.events.ConfigurableApplicationContextEventPublisher.publishEvent(ConfigurableApplicationContextEventPublisher.groovy:30)
	at org.grails.orm.hibernate.AbstractHibernateGormInstanceApi.save(AbstractHibernateGormInstanceApi.groovy:114)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.save(GormEntity.groovy:151)
	at current.tenant.issue.PersonHandler.createWithCar_closure2(PersonHandler.groovy:29)
```

A test app will soon be provided.

**Comment by goeh** [comment]
Test app here: https://github.com/goeh/grails-current-tenant-issue
