### ISSUE TITLE
org.hibernate.DuplicateMappingException: Same physical table name references several logical table names

### ISSUE THREAD

**Issue by kalpanaDasireddy** [grails/grails-data-mapping#789]
grails 3.1.10 run-app failing with org.hibernate.DuplicateMappingException: Same physical table name references several logical table names.
I have a base class with tablePerHierarchy set to false. 

```groovy
class BaseConfig implements OrgDomainType
{   static mapping =
    {
        autoTimestamp true
        tablePerHierarchy false
        table('CONFIGURATION')
         }
}
```

And Subclass 

```groovy
class Shift extends BaseConfig
{
      static mapping = {
        id(column:'SHIFT_CONFIG_ID')
    }
}
```

Failed with error

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is org.hibernate.DuplicateMappingException: Same physical table name [CONFIGURATION] references several logical table names: [Shift], [CostCode]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1578)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
    at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:351)
    ... 48 common frames omitted
Caused by: org.hibernate.DuplicateMappingException: Same physical table name [CONFIGURATION] references several logical table names: [Shift], [CostCode]
    at org.hibernate.cfg.Configuration$MappingsImpl.addTableBinding(Configuration.java:3172)
    at org.grails.orm.hibernate.cfg.AbstractGrailsDomainBinder.getJoinedSubClassTableName(AbstractGrailsDomainBinder.java:1617)
    at org.grails.orm.hibernate.cfg.AbstractGrailsDomainBinder.bindJoinedSubClass(AbstractGrailsDomainBinder.java:1591)
    at org.grails.orm.hibernate.cfg.AbstractGrailsDomainBinder.bindSubClass(AbstractGrailsDomainBinder.java:1518)
    at org.grails.orm.hibernate.cfg.AbstractGrailsDomainBinder.bindSubClasses(AbstractGrailsDomainBinder.java:1472)
    at org.grails.orm.hibernate.cfg.AbstractGrailsDomainBinder.bindRoot(AbstractGrailsDomainBinder.java:1448)
    at org.grails.orm.hibernate.cfg.AbstractGrailsDomainBinder.bindClass(AbstractGrailsDomainBinder.java:1283)
    at org.grails.orm.hibernate.cfg.HibernateMappingContextConfiguration.secondPassCompile(HibernateMappingContextConfiguration.java:283)
    at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1846)
    at org.grails.orm.hibernate.cfg.HibernateMappingContextConfiguration.buildSessionFactory(HibernateMappingContextConfiguration.java:196)
    at org.grails.orm.hibernate.HibernateMappingContextSessionFactoryBean.doBuildSessionFactory(HibernateMappingContextSessionFactoryBean.java:476)
    at org.grails.orm.hibernate.HibernateMappingContextSessionFactoryBean.buildSessionFactory(HibernateMappingContextSessionFactoryBean.java:470)
    at org.grails.orm.hibernate.HibernateMappingContextSessionFactoryBean.afterPropertiesSet(HibernateMappingContextSessionFactoryBean.java:93)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
    ... 55 common frames omitted
```
However if I add table name explicitly to sub class mapping, it doesn't seem to have issues.

**Comment by kalpanaDasireddy** [comment]
Adding table name explicitly to subclass throws error
ERROR hibernate.AssertionFailure: an assertion failure occured (this may indicate a bug in Hibernate, but is more likely due to unsafe use of the session)
org.hibernate.AssertionFailure: not a joined-subclass

**Comment by graemerocher** [comment]
This is by design, the mapping is inherited from the parent, so the solution to specify the mapping in the child is the correct one.

**Comment by viswanadh1983** [comment]
Hi I am also facing the same issue , please provide solution
