### ISSUE TITLE
MultiDataSources issue Grails 2.5.4

### ISSUE THREAD

**Issue by Travis9011** [grails/grails-data-mapping#794]
Hi, I have an issue with new MultiDasources mode on Grails 2.5.4, MongoDb 3.x and plugin version mongodb:6.0.0.BUILD-SNAPSHOT

I was trying to implement grails.mongodb.connections setting as you can see in DataSource.groovy below.

```
grails {
  mongodb {
    url = 'mongodb://xxxx:xxxx@xxxxx:27700/db_default'
      connections {
        ds1 {
          url = 'mongodb://yyyy:yyy@yyyyyy:21036/ds1_test'
        }
        ds2 {
          url = 'mongodb://zzzzz:zzzzzz@zzzzzz:19916/ds2_test'
        }
      }
  }
}
```

Then I create a domain class Country which has to be mapped to all datasources

```
package geo

class Country {

    String countryCode
    String countryName
    String area

    static mapWith = "mongo"

    static constraints = {
        countryCode blank: false, unique: true
        countryName blank: false
        area blank: false
    }

    static mapping = {
        connections (["ds1","ds2"])
        collection "Country"
        countryCode attr: "countryCode"
        countryName attr: "countryName"
        area attr: "area"

    }
}
```

With this connection configuration I have the following cast exception:

```
context.GrailsContextLoaderListener Error initializing the application: Error creating bean with name 'transactionManagerPostProcessor': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'mongoTransactionManager' while setting constructor argument with key [1]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongoDatastore': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.grails.datastore.mapping.mongo.MongoDatastore]: Constructor threw exception; nested exception is java.lang.ClassCastException: [Ljava.lang.String; cannot be cast to java.util.List
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManagerPostProcessor': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'mongoTransactionManager' while setting constructor argument with key [1]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongoDatastore': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.grails.datastore.mapping.mongo.MongoDatastore]: Constructor threw exception; nested exception is java.lang.ClassCastException: [Ljava.lang.String; cannot be cast to java.util.List
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'mongoTransactionManager' while setting constructor argument with key [1]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongoDatastore': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.grails.datastore.mapping.mongo.MongoDatastore]: Constructor threw exception; nested exception is java.lang.ClassCastException: [Ljava.lang.String; cannot be cast to java.util.List
	... 4 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongoDatastore': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.grails.datastore.mapping.mongo.MongoDatastore]: Constructor threw exception; nested exception is java.lang.ClassCastException: [Ljava.lang.String; cannot be cast to java.util.List
	... 4 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.grails.datastore.mapping.mongo.MongoDatastore]: Constructor threw exception; nested exception is java.lang.ClassCastException: [Ljava.lang.String; cannot be cast to java.util.List
	... 4 more
Caused by: java.lang.ClassCastException: [Ljava.lang.String; cannot be cast to java.util.List
	at org.grails.datastore.mapping.config.groovy.DefaultMappingConfigurationBuilder.invokeMethod(DefaultMappingConfigurationBuilder.groovy:61)
	at geo.Country$__clinit__closure2.doCall(Country.groovy:20)
	at org.grails.datastore.mapping.config.groovy.DefaultMappingConfigurationBuilder.evaluate(DefaultMappingConfigurationBuilder.groovy:91)
```

If i try to switch the domain class connection configuration to `connection ConnectionSource.ALL` I have this exception:

```
Caused by: org.grails.datastore.mapping.core.exceptions.ConfigurationException: Invalid connection [ALL] configured for class [class geo.Country]
	at org.grails.datastore.mapping.mongo.MongoDatastore$5.getDatastoreForQualifier(MongoDatastore.java:651)
	at org.grails.datastore.mapping.mongo.MongoDatastore$5.getStaticApi(MongoDatastore.java:629)
	at org.grails.datastore.mapping.mongo.MongoDatastore$5.getStaticApi(MongoDatastore.java:626)
```

If I am doing something wrong, please let me know.
Thanks

**Comment by gianlucagenga** [comment]
Hi, I'm facing the same issue.
Please can you provide me a solution for this problem?
Thanks

**Comment by graemerocher** [comment]
The first problem can be resolved by simply changing:

```groovy
connections (["ds1","ds2"])
```

To

```groovy
connections ("ds1","ds2")
```
