### ISSUE TITLE
querying joda-time DateTime fields in Unit Specs fails

### ISSUE THREAD

**Issue by peh** [grails/grails-data-mapping#797]
When querying for joda DateTime fields in UnitSpecs the result is always:

```
Cannot query [joda.test.Person] on non-existent property: dateCreated
org.springframework.dao.InvalidDataAccessResourceUsageException: Cannot query [joda.test.Person] on non-existent property: dateCreated
	at org.grails.datastore.mapping.simple.query.SimpleMapQuery.getValidProperty(SimpleMapQuery.groovy:751)
	at org.grails.datastore.mapping.simple.query.SimpleMapQuery.executeSubQueryInternal(SimpleMapQuery.groovy:690)
	at org.grails.datastore.mapping.simple.query.SimpleMapQuery.executeSubQuery(SimpleMapQuery.groovy:676)
	at org.grails.datastore.mapping.simple.query.SimpleMapQuery.executeQuery(SimpleMapQuery.groovy:63)
	at org.grails.datastore.mapping.query.Query.list(Query.java:567)
	at org.grails.datastore.mapping.query.Query.singleResult(Query.java:585)
	at org.grails.datastore.gorm.finders.AbstractFindByFinder.invokeQuery(AbstractFindByFinder.java:30)
	at org.grails.datastore.gorm.finders.AbstractFindByFinder$1.doInSession(AbstractFindByFinder.java:24)
	at org.grails.datastore.mapping.core.DatastoreUtils.execute(DatastoreUtils.java:310)
	at org.grails.datastore.gorm.finders.AbstractFinder.execute(AbstractFinder.java:41)
	at org.grails.datastore.gorm.finders.AbstractFindByFinder.doInvokeInternal(AbstractFindByFinder.java:22)
	at org.grails.datastore.gorm.finders.DynamicFinder.invoke(DynamicFinder.java:157)
	at org.grails.datastore.gorm.finders.DynamicFinder.invoke(DynamicFinder.java:357)
	at org.grails.datastore.gorm.GormStaticApi.methodMissing(GormStaticApi.groovy:141)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.staticMethodMissing(GormEntity.groovy:745)
	at joda.test.PersonSpec.This should work too(PersonSpec.groovy:17)
```

no matter if HibernateTestMixin is used or not or what type of query is used (dynamic finder, criteria or detached critera)

sample app can be found at: https://github.com/peh/joda-test

tested on grails versions 3.1.11 to 3.2-M2

**Comment by peh** [comment]
a simple

```
def setupSpec() {
        SimpleMapJodaTimeMarshaller.initialize()
    }```

fixes it.

So it looks like the bug is in the joda-time plugin. closing this one
