### ISSUE TITLE
ExecuteUpdatePersistentMethod throws NPE when named parameter is null

### ISSUE THREAD

**Issue by snimavat** [grails/grails-data-mapping#852]
ExecuteUpdatePersistentMethod:93 would throw null pointer exception when a named parameter passed to Domain.executeUpdate() is null. However if the parameter is positional parameter, it would work.

Shouldnt it check, if parameter value is null and if so, just set it on query without doing any further checks ?

```
java.lang.NullPointerException
	at org.codehaus.groovy.grails.orm.hibernate.metaclass.ExecuteUpdatePersistentMethod$1.doInHibernate(ExecuteUpdatePersistentMethod.java:93)
	at org.codehaus.groovy.grails.orm.hibernate.GrailsHibernateTemplate.doExecute(GrailsHibernateTemplate.java:188)
	at org.codehaus.groovy.grails.orm.hibernate.GrailsHibernateTemplate.execute(GrailsHibernateTemplate.java:132)
	at org.codehaus.groovy.grails.orm.hibernate.metaclass.ExecuteUpdatePersistentMethod.doInvokeInternal(ExecuteUpdatePersistentMethod.java:70)
	at org.codehaus.groovy.grails.orm.hibernate.metaclass.AbstractStaticPersistentMethod.invoke(AbstractStaticPersistentMethod.java:79)
	at org.codehaus.groovy.grails.orm.hibernate.metaclass.AbstractStaticPersistentMethod.invoke(AbstractStaticPersistentMethod.java:72)
	at org.codehaus.groovy.grails.orm.hibernate.HibernateGormStaticApi.executeUpdate(HibernateGormStaticApi.groovy:574)
```

**Comment by graemerocher** [comment]
You must be using an old version of GORM, since ExecuteUpdatePersistentMethod no longer exists. Please upgrade.

**Comment by snimavat** [comment]
Oh yes, grails 2.5.5 ...
