### ISSUE TITLE
HibernateDataStore fails to instantiate on Turkish Locale

### ISSUE THREAD

**Issue by hakanernam** [grails/grails-data-mapping#862]
Setting a new Grails 3.2.5 application locale to "TR" causes gdm/hibernate to fail with exception:

```
Caused by: org.grails.datastore.mapping.model.DatastoreConfigurationException: Invalid id generation strategy for entity [gapp325.Book]: native
```
I believe  `generatorName.toUpperCase()` on  the line:

https://github.com/grails/grails-data-mapping/blob/master/grails-datastore-gorm-hibernate-core/src/main/groovy/org/grails/orm/hibernate/cfg/HibernateMappingContext.java#L257

is causing this by turning 'native' to 'NATİVE'. Same for other values with 'i' in them.

To replicate:

```
HMBP$ grails create-app gapp325
HMBP$cd gapp325
HMBP$grails create-domain-class gapp325.Book

Add this to grails-app/conf/spring/resources:

 localeResolver(org.springframework.web.servlet.i18n.SessionLocaleResolver) {
        defaultLocale = new Locale("tr", "TR")
        java.util.Locale.setDefault(defaultLocale)
    }

HMBP$grails run-app
```

Fails with stacktrace:

```
...

        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:351)
        ... 61 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.grails.orm.hibernate.HibernateDatastore]: Constructor threw exception; nested exception is org.grails.datastore.mapping.model.DatastoreConfigurationException: Invalid id generation strategy for entity [gapp325.Book]: native
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:154)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:122)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:271)
        ... 70 common frames omitted
Caused by: org.grails.datastore.mapping.model.DatastoreConfigurationException: Invalid id generation strategy for entity [gapp325.Book]: native
        at org.grails.orm.hibernate.cfg.HibernateMappingContext$HibernateMappingFactory.createIdentityMapping(HibernateMappingContext.java:263)
        at org.grails.orm.hibernate.cfg.HibernatePersistentEntity$1.<init>(HibernatePersistentEntity.java:37)
        at org.grails.orm.hibernate.cfg.HibernatePersistentEntity.<init>(HibernatePersistentEntity.java:35)
        at org.grails.orm.hibernate.cfg.HibernateMappingContext.createPersistentEntity(HibernateMappingContext.java:144)
        at org.grails.datastore.mapping.model.AbstractMappingContext.addPersistentEntities(AbstractMappingContext.java:271)
        at org.grails.orm.hibernate.cfg.HibernateMappingContext.<init>(HibernateMappingContext.java:73)
        at org.grails.orm.hibernate.connections.HibernateConnectionSourceFactory.buildConfiguration(HibernateConnectionSourceFactory.java:88)
        at org.grails.orm.hibernate.connections.HibernateConnectionSourceFactory.create(HibernateConnectionSourceFactory.java:79)
        at org.grails.orm.hibernate.connections.AbstractHibernateConnectionSourceFactory.create(AbstractHibernateConnectionSourceFactory.java:38)
        at org.grails.orm.hibernate.connections.AbstractHibernateConnectionSourceFactory.create(AbstractHibernateConnectionSourceFactory.java:22)
        at org.grails.datastore.mapping.core.connections.AbstractConnectionSourceFactory.create(AbstractConnectionSourceFactory.java:64)
        at org.grails.datastore.mapping.core.connections.AbstractConnectionSourceFactory.create(AbstractConnectionSourceFactory.java:52)
        at org.grails.datastore.mapping.core.connections.ConnectionSourcesInitializer.create(ConnectionSourcesInitializer.groovy:24)
        at org.grails.orm.hibernate.HibernateDatastore.<init>(HibernateDatastore.java:206)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrConstructorNewInstance(ReflectiveInterceptor.java:1075)
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:142)
        ... 72 common frames omitted

...
```

Works after commenting out the locale setting code.

**Comment by hakanernam** [comment]
I would like to send a PR for this. I realize some people may depend on their current locale for upper/lowercase conversions, but I believe in this case using Locale.English does not harm anyone due to predefined enum values.

**Comment by graemerocher** [comment]
Go ahead. Thanks.
