### ISSUE TITLE
Mongo Cursor Not Found Exception in Grails 3 and mongodb:5.0.5 plugin

### ISSUE THREAD

**Issue by ChiranjibKarn** [grails/grails-data-mapping#871]
We are having issue with Mongodb plugin for grails, following is the error log snippet:

> Caused by: com.mongodb.MongoCursorNotFoundException: Query failed with error code -5 and error message 'Cursor 150498570815 not found on server <server>:<port>' on server localhost:27017
        at com.mongodb.operation.QueryHelper.translateCommandException(QueryHelper.java:27)
        at com.mongodb.operation.QueryBatchCursor.getMore(QueryBatchCursor.java:215)
        at com.mongodb.operation.QueryBatchCursor.hasNext(QueryBatchCursor.java:103)
        at com.mongodb.MongoBatchCursorAdapter.hasNext(MongoBatchCursorAdapter.java:46)
        at org.grails.datastore.gorm.query.AbstractResultList.convertObject(AbstractResultList.java:98)
        at org.grails.datastore.gorm.query.AbstractResultList$1.next(AbstractResultList.java:161)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.size(DefaultGroovyMethods.java:6774)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.size(DefaultGroovyMethods.java:6793)
        at grails.plugin.json.view.api.internal.JsonGrailsViewHelper.render(JsonGrailsViewHelper.groovy:288)
        at backend_seriesAPI_seriesLandingPage_gson$_run_closure1.doCall(backend_seriesAPI_seriesLandingPage_gson:25)
        at backend_seriesAPI_seriesLandingPage_gson$_run_closure1.call(backend_seriesAPI_seriesLandingPage_gson)
        at grails.plugin.json.builder.StreamingJsonBuilder$StreamingJsonDelegate.cloneDelegateAndGetContent(StreamingJsonBuilder.java:691)
        at grails.plugin.json.builder.StreamingJsonBuilder$StreamingJsonDelegate.cloneDelegateAndGetContent(StreamingJsonBuilder.java:683)
        at grails.plugin.json.builder.StreamingJsonBuilder.call(StreamingJsonBuilder.java:199)
        at grails.plugin.json.view.JsonViewTemplate.json(JsonViewTemplate.groovy:54)
        at backend_seriesAPI_seriesLandingPage_gson.run(backend_seriesAPI_seriesLandingPage_gson:20)
        at grails.plugin.json.view.JsonViewTemplate.doWrite(JsonViewTemplate.groovy:32)
        at grails.views.AbstractWritableScript.writeTo(AbstractWritableScript.groovy:30)
        ... 132 common frames omitted

When this error thrown, the CPU usage of the server instance goes 100%.

**Comment by graemerocher** [comment]
We'll need an example as it isn't clear if this is a GORM bug, a MongoDB bug or an application bug

**Comment by ChiranjibKarn** [comment]
May be you are right, will do more testing and if needed will send you the example code. For now am closing this.
