### ISSUE TITLE
6.1 - TransactionRequiredException trying to use hibernate-5.2.9.Final

### ISSUE THREAD

**Issue by zyro23** [grails/grails-data-mapping#898]
just wanted to check the hibernate 5.2 support of gorm/gdm 6.1.
sample app will be referenced in a minute.
```
2017-03-29 16:25:20.201 ERROR --- [           main] o.s.boot.SpringApplication               : Application startup failed

javax.persistence.TransactionRequiredException: no transaction is in progress
	at org.hibernate.internal.SessionImpl.checkTransactionNeeded(SessionImpl.java:3450)
	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1418)
	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1414)
	at org.grails.orm.hibernate5.support.HibernatePersistenceContextInterceptor.flush(HibernatePersistenceContextInterceptor.java:129)
	at org.grails.orm.hibernate.support.AbstractMultipleDataSourceAggregatePersistenceContextInterceptor.flush(AbstractMultipleDataSourceAggregatePersistenceContextInterceptor.java:93)
	at org.grails.web.servlet.context.GrailsConfigUtils.executeGrailsBootstraps(GrailsConfigUtils.java:68)
	at org.grails.plugins.web.servlet.context.BootStrapClassRunner.onStartup(BootStrapClassRunner.groovy:53)
	at grails.boot.config.GrailsApplicationPostProcessor.onApplicationEvent(GrailsApplicationPostProcessor.groovy:256)
	at grails.boot.config.GrailsApplicationPostProcessor.onApplicationEvent(GrailsApplicationPostProcessor.groovy)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:383)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:337)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:882)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:545)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:372)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:83)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:388)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:375)
	at grails.boot.GrailsApp$run.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at myapp.Application.main(Application.groovy:8)
```

**Comment by graemerocher** [comment]
this is more a bug in Grails which should be wrapping the call to `BootStrap` in a transaction

**Comment by zyro23** [comment]
but the service is autowired into the non-tx `BootStrap` calss and the service is annotated `@Transactional`? the same is working just fine with hibernate-5.1.2.Final. thank you for taking a look!

**Comment by graemerocher** [comment]
the exception is not coming from the service, but from the logic that wraps the execution of BootStrap inside a session

**Comment by zyro23** [comment]
the fix ensures that the `persistenceInterceptor` does not flush the session if on hibernate-5.2 and outside a transaction.

but auto-flushes still may happen because the interceptors' flush mode is `AUTO`: https://github.com/grails/grails-data-mapping/blob/1a6571b1bed2869d96d73e121f971fb77b961687/grails-datastore-gorm-support/src/main/groovy/org/grails/orm/hibernate5/support/HibernatePersistenceContextInterceptor.java#L185

do you think it would make sense to align the flush mode of `HibernatePersistenceContextInterceptor` with the globally configured one (i.e. `hibernate.flush.mode`)?

**Comment by graemerocher** [comment]
It would make sense yes
