### ISSUE TITLE
[6.1.1] @CurrentTenant causes java.lang.VerifyError when used with grails.transaction.Transactional

### ISSUE THREAD

**Issue by andersb** [grails/grails-data-mapping#910]
Hi

When @CurrentTenant defined on service method, it will work as expected but will cause a compilation error when defined on class level.

This will work
```groovy
@Transactional
class BookService {

  @CurrentTenant
  Book saveBook(String title) {
    Book book = new Book()
    book.title = title
    book.save(flush: true)
    return book
  }
```

And this
```groovy
@CurrentTenant
@Transactional
class Book2Service {

  Book saveBook(String title) {
    Book book = new Book()
    book.title = title
    book.save(flush: true)
    return book
  }
}
```

Will result in
```groovy
Caused by: java.lang.VerifyError: (class: se/multitenantdemo/Book2Service, method: saveBook signature: (Ljava/lang/String;)Lse/multitenantdemo/tenantdb/Book;) Unable to pop operand off an empty stack
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredFields(Class.java:1916)
	at org.codehaus.groovy.util.LazyReference.getLocked(LazyReference.java:49)
	at org.codehaus.groovy.util.LazyReference.get(LazyReference.java:36)
	at org.grails.core.util.ClassPropertyFetcher.init(ClassPropertyFetcher.java:180)
	at org.grails.core.util.ClassPropertyFetcher.<init>(ClassPropertyFetcher.java:150)
	at org.grails.core.util.ClassPropertyFetcher.forClass(ClassPropertyFetcher.java:91)
	at org.grails.core.util.ClassPropertyFetcher.forClass(ClassPropertyFetcher.java:66)
	at org.grails.core.AbstractGrailsClass.<init>(AbstractGrailsClass.java:87)
	at org.grails.core.AbstractInjectableGrailsClass.<init>(AbstractInjectableGrailsClass.java:31)
	at org.grails.core.DefaultGrailsServiceClass.<init>(DefaultGrailsServiceClass.java:32)
	... 43 more
```

Here is a sample project with Grails 3.2.8 and Gorm 6.1.1

[multi-tenant-demo.zip](https://github.com/grails/grails-data-mapping/files/913051/multi-tenant-demo.zip)

I noticed that when using default dependencies groovy-test will land on 2.4.9.
Changing it it to 2.4.10 will still lead to the same error.

Same error will happen for @WithoutTenant and wouldn't be to much of a surprise if it also happen for @Tenant.

**Comment by graemerocher** [comment]
Thanks for the report. Quick question, which `@Transactional` annotation are you using?

**Comment by andersb** [comment]
grails.transaction.Transactional

**Comment by andersb** [comment]
Just tried with grails.gorm.transactions.Transactional which made it work.

**Comment by graemerocher** [comment]
Thanks for confirming, we plan to deprecate `grails.transaction.Transactional` in Grails 3.3 and replace it with the new version.

**Comment by andersb** [comment]
Thanks for the info.

Is it safe to replace all imports of `grails.transaction.Transactional` with `grails.gorm.transactions.Transactional` ?

**Comment by graemerocher** [comment]
Yes

**Comment by graemerocher** [comment]
Given that Grails' `@Transactional` will be replaced by GORM's one in Grails 3.3 I don't believe it is worth the effort to fix this as a workaround exists
