### ISSUE TITLE
Exception thrown when creating domain class instance with Set property

### ISSUE THREAD

**Issue by ilPittiz** [grails/grails-data-mapping#911]
Environment:
- JDK 1.8.0.60
- Grails 3.2.8
- GORM for MongoDB plugin 6.1.1

I defined in my domain class a `Set` property, initialized as empty set by default.
Creating a new instance throws `IllegalArgumentException`.
When using `List` in place of `Set` instead, everything work as expected.

_Domain class_

    class Person {
        String email
        TreeSet<String> roles = new TreeSet<String>()
    }

_Code triggering the exception_

    new Person(email: 'user@mydomain.com').insert()

_Stacktrace_

	java.lang.IllegalArgumentException: Cannot assign value [org.grails.datastore.mapping.dirty.checking.DirtyCheckingSet@7439493e] with type [org.grails.datastore.mapping.dirty.checking.DirtyCheckingSet] to property [roles] of class [my.package.Person]. The value is not an acceptable type: Cannot set field [roles] of object [Person(email:user@mydomain.com)] for value [org.grails.datastore.mapping.dirty.checking.DirtyCheckingSet@7439493e] of type [org.grails.datastore.mapping.dirty.checking.DirtyCheckingSet]
		at org.grails.datastore.mapping.reflect.FieldEntityAccess.setPropertyNoConversion(FieldEntityAccess.java:154)
		at org.grails.datastore.bson.codecs.encoders.BasicCollectionTypeEncoder.encode(BasicCollectionTypeEncoder.groovy:50)
		at org.grails.datastore.bson.codecs.encoders.BasicCollectionTypeEncoder.encode(BasicCollectionTypeEncoder.groovy)
		at org.grails.datastore.bson.codecs.BsonPersistentEntityCodec.encode(BsonPersistentEntityCodec.groovy:180)
		at org.grails.datastore.bson.codecs.BsonPersistentEntityCodec.encode(BsonPersistentEntityCodec.groovy:153)
		at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63)
		at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29)
		at com.mongodb.connection.InsertCommandMessage.writeTheWrites(InsertCommandMessage.java:101)
		at com.mongodb.connection.InsertCommandMessage.writeTheWrites(InsertCommandMessage.java:43)
		at com.mongodb.connection.BaseWriteCommandMessage.encodeMessageBodyWithMetadata(BaseWriteCommandMessage.java:129)
		at com.mongodb.connection.RequestMessage.encodeWithMetadata(RequestMessage.java:160)
		at com.mongodb.connection.WriteCommandProtocol.sendMessage(WriteCommandProtocol.java:212)
		at com.mongodb.connection.WriteCommandProtocol.execute(WriteCommandProtocol.java:101)
		at com.mongodb.connection.InsertCommandProtocol.execute(InsertCommandProtocol.java:67)
		at com.mongodb.connection.InsertCommandProtocol.execute(InsertCommandProtocol.java:37)
		at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:159)
		at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:286)
		at com.mongodb.connection.DefaultServerConnection.insertCommand(DefaultServerConnection.java:115)
		at com.mongodb.operation.MixedBulkWriteOperation$Run$2.executeWriteCommandProtocol(MixedBulkWriteOperation.java:455)
		at com.mongodb.operation.MixedBulkWriteOperation$Run$RunExecutor.execute(MixedBulkWriteOperation.java:646)
		at com.mongodb.operation.MixedBulkWriteOperation$Run.execute(MixedBulkWriteOperation.java:401)
		at com.mongodb.operation.MixedBulkWriteOperation$1.call(MixedBulkWriteOperation.java:179)
		at com.mongodb.operation.MixedBulkWriteOperation$1.call(MixedBulkWriteOperation.java:168)
		at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:230)
		at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:221)
		at com.mongodb.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:168)
		at com.mongodb.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:74)
		at com.mongodb.Mongo.execute(Mongo.java:781)
		at com.mongodb.Mongo$2.execute(Mongo.java:764)
		at com.mongodb.MongoCollectionImpl.bulkWrite(MongoCollectionImpl.java:291)
		at com.mongodb.MongoCollectionImpl.bulkWrite(MongoCollectionImpl.java:245)
		at org.grails.datastore.mapping.mongo.MongoCodecSession.flush(MongoCodecSession.groovy:234)
		at org.grails.datastore.mapping.mongo.AbstractMongoSession.flush(AbstractMongoSession.java:73)
		at org.grails.datastore.mapping.web.support.OpenSessionInViewInterceptor.postHandle(OpenSessionInViewInterceptor.java:78)
		at org.springframework.web.servlet.handler.WebRequestHandlerInterceptorAdapter.postHandle(WebRequestHandlerInterceptorAdapter.java:64)
		at org.springframework.web.servlet.HandlerExecutionChain.applyPostHandle(HandlerExecutionChain.java:152)
		at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:970)
		at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
		at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
		at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
		at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
		at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.groovy:58)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
		at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:169)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
		at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
		at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:158)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
		at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
		at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:105)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
		at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
		at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
		at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:115)
		at grails.plugin.springsecurity.web.UpdateRequestContextHolderExceptionTranslationFilter.doFilter(UpdateRequestContextHolderExceptionTranslationFilter.groovy:64)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
		at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.groovy:53)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
		at org.springframework.security.web.session.ConcurrentSessionFilter.doFilter(ConcurrentSessionFilter.java:134)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
		at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.groovy:62)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
		at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
		at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
		at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
		at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
		at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
		at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
		at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
		at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:474)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.lang.Thread.run(Thread.java:745)

**Comment by graemerocher** [comment]
Is there a specific reason you need `TreeSet` and cannot just use the interface type `Set`?

**Comment by ilPittiz** [comment]
Actually it's not a strict requirement, it was just for my convenience, to get an ordered set of strings (max ~20 entries) when accessing the `roles` property of domain class instances, plus to prevent including `null` values.
I agree this can be done however with some fine tuning on specific portions of code.

**Comment by graemerocher** [comment]
In that case please use `Set` instead of `TreeSet`
