### ISSUE TITLE
Grails 3.2.8 + GORM for MongoDB - NoClassDefFoundError on application boot

### ISSUE THREAD

**Issue by ilPittiz** [grails/grails-data-mapping#912]
Environment:
- JDK 1.8.0.60
- Grails 3.2.8
- GORM for MongoDB plugin 6.1.1 (dependency `compile "org.grails.plugins:mongodb:6.1.0"`)

With this configuration, regardless of the data source configuration, the Application boot (`bootRun` Gradle task) fails with `NoClassDefFoundError` being thrown.

The same issue occurs when downgrading to Grails 3.2.7, but not with Grails 3.2.6.

_Stacktrace_

	java.lang.NoClassDefFoundError: org/grails/datastore/mapping/core/connections/MultipleConnectionSourceCapableDatastore
		at java.lang.ClassLoader.defineClass1(Native Method)
		at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
		at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
		at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
		at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
		at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
		at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
		at java.security.AccessController.doPrivileged(Native Method)
		at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
		at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		at grails.mongodb.bootstrap.MongoDbDataStoreSpringInitializer$_getBeanDefinitions_closure1.doCall(MongoDbDataStoreSpringInitializer.groovy:103)
		at grails.mongodb.bootstrap.MongoDbDataStoreSpringInitializer$_getBeanDefinitions_closure1.doCall(MongoDbDataStoreSpringInitializer.groovy)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:497)
		at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426)
		at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
		at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
		at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
		at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
		at groovy.lang.Closure.call(Closure.java:414)
		at groovy.lang.Closure.call(Closure.java:408)
		at grails.spring.BeanBuilder.invokeBeanDefiningClosure(BeanBuilder.java:759)
		at grails.spring.BeanBuilder.beans(BeanBuilder.java:588)
		at grails.spring.BeanBuilder.invokeMethod(BeanBuilder.java:531)
		at org.grails.plugins.DefaultGrailsPlugin.doWithRuntimeConfiguration(DefaultGrailsPlugin.java:559)
		at org.grails.plugins.AbstractGrailsPluginManager.doRuntimeConfiguration(AbstractGrailsPluginManager.java:167)
		at grails.boot.config.GrailsApplicationPostProcessor.postProcessBeanDefinitionRegistry(GrailsApplicationPostProcessor.groovy:171)
		at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:118)
		at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:686)
		at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:524)
		at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
		at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762)
		at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:372)
		at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
		at grails.boot.GrailsApp.run(GrailsApp.groovy:83)
		at grails.boot.GrailsApp.run(GrailsApp.groovy:388)
		at grails.boot.GrailsApp.run(GrailsApp.groovy:375)
		at grails.boot.GrailsApp$run.call(Unknown Source)
		at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
		at Application.main(Application.groovy:8)
	Caused by: java.lang.ClassNotFoundException: org.grails.datastore.mapping.core.connections.MultipleConnectionSourceCapableDatastore
		at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
		at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		... 46 common frames omitted
	
	2017-04-13 10:16:01.456 ERROR --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Destroy method on bean with name 'grailsApplicationPostProcessor' threw an exception
	
	java.lang.IllegalStateException: ApplicationEventMulticaster not initialized - call 'refresh' before multicasting events via the context: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@5dda6f9: startup date [Thu Apr 13 10:16:00 CEST 2017]; root of context hierarchy
		at org.springframework.context.support.AbstractApplicationContext.getApplicationEventMulticaster(AbstractApplicationContext.java:404)
		at org.springframework.context.support.ApplicationListenerDetector.postProcessBeforeDestruction(ApplicationListenerDetector.java:97)
		at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:253)
		at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:578)
		at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:554)
		at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:961)
		at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:523)
		at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:968)
		at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1033)
		at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1009)
		at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:961)
		at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:819)
		at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
		at grails.boot.GrailsApp.run(GrailsApp.groovy:83)
		at grails.boot.GrailsApp.run(GrailsApp.groovy:388)
		at grails.boot.GrailsApp.run(GrailsApp.groovy:375)
		at grails.boot.GrailsApp$run.call(Unknown Source)
		at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
		at Application.main(Application.groovy:8)
	
	2017-04-13 10:16:01.456 ERROR --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Destroy method on bean with name 'org.springframework.boot.autoconfigure.internalCachingMetadataReaderFactory' threw an exception
	
	java.lang.IllegalStateException: ApplicationEventMulticaster not initialized - call 'refresh' before multicasting events via the context: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@5dda6f9: startup date [Thu Apr 13 10:16:00 CEST 2017]; root of context hierarchy
		at org.springframework.context.support.AbstractApplicationContext.getApplicationEventMulticaster(AbstractApplicationContext.java:404)
		at org.springframework.context.support.ApplicationListenerDetector.postProcessBeforeDestruction(ApplicationListenerDetector.java:97)
		at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:253)
		at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:578)
		at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:554)
		at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:961)
		at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:523)
		at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:968)
		at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1033)
		at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1009)
		at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:961)
		at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:819)
		at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
		at grails.boot.GrailsApp.run(GrailsApp.groovy:83)
		at grails.boot.GrailsApp.run(GrailsApp.groovy:388)
		at grails.boot.GrailsApp.run(GrailsApp.groovy:375)
		at grails.boot.GrailsApp$run.call(Unknown Source)
		at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
		at Application.main(Application.groovy:8)

**Comment by graemerocher** [comment]
Did you set `gormVersion` in `gradle.properties`?

**Comment by ilPittiz** [comment]
Sorry, I definitely missed that.. Once added `gormVersion = 6.1.1.RELEASE` I was able to boot my application as expected. Going to close this issue.
Thanks for your help!
