### ISSUE TITLE
NotReadablePropertyException thrown when validating hasMany

### ISSUE THREAD

**Issue by dpcasady** [grails/grails-data-mapping#926]
In GORM 6.1.x (I think on 6.0.x as well), attempting to save an invalid object with a hasMany collection (that belongsTo the object) throws a `NotReadablePropertyException`.

This only seems to happen if the hasMany is for an abstract or parent class. Take the following domains:

```groovy
abstract class Person {

}

class Employee extends Person {
    static belongsTo = [
        business: Business
    ]
}

class Business {
    String name

    static hasMany = [
        people: Person
    ]
}
```

In a more real world example, `Business` would probably extend another class and the hasMany relationship would be defined there but the error still occurs for this simpler model.

This test illustrates the issue:

```groovy
void "invalid business has errors"() {
    given: "an invalid business"
    Business b = new Business(name: null)

    and: "a valid employee that belongs to the business"
    Person p = new Employee(business: b)
    b.addToPeople(p)

    when:
    b.save()
    // Validation causes a NotReadablePropertyException: Invalid property 'people[0].people[0]'

    then:
    !b.hasErrors()
}
```
It appears as though this happens as part of the cascading validation where each person on the business is validated, which causes validation on the person's back reference to the business.

Stacktrace:
```
org.springframework.beans.NotReadablePropertyException: Invalid property 'people[0].people[0]' of bean class [nested.association.validation.Business]: Bean property 'people[0].people[0]' is not readable or has an invalid getter method: Does the return type of the getter match the parameter type of the setter?
	at org.springframework.beans.AbstractNestablePropertyAccessor.getPropertyValue(AbstractNestablePropertyAccessor.java:633)
	at org.springframework.beans.AbstractNestablePropertyAccessor.getNestedPropertyAccessor(AbstractNestablePropertyAccessor.java:850)
	at org.springframework.beans.AbstractNestablePropertyAccessor.getPropertyAccessorForPropertyPath(AbstractNestablePropertyAccessor.java:827)
	at org.springframework.beans.AbstractNestablePropertyAccessor.getPropertyAccessorForPropertyPath(AbstractNestablePropertyAccessor.java:828)
	at org.springframework.beans.AbstractNestablePropertyAccessor.getPropertyValue(AbstractNestablePropertyAccessor.java:622)
	at org.springframework.validation.AbstractPropertyBindingResult.getActualFieldValue(AbstractPropertyBindingResult.java:99)
	at org.springframework.validation.AbstractBindingResult.rejectValue(AbstractBindingResult.java:108)
	at org.grails.orm.hibernate.validation.HibernateDomainClassValidator.cascadeValidationToOne(HibernateDomainClassValidator.java:109)
	at org.grails.validation.GrailsDomainClassValidator.cascadeToAssociativeProperty(GrailsDomainClassValidator.java:131)
	at org.grails.validation.GrailsDomainClassValidator.cascadeValidationToOne(GrailsDomainClassValidator.java:260)
	at org.grails.orm.hibernate.validation.HibernateDomainClassValidator.cascadeValidationToOne(HibernateDomainClassValidator.java:115)
	at org.grails.validation.GrailsDomainClassValidator.cascadeValidationToMany(GrailsDomainClassValidator.java:161)
	at org.grails.orm.hibernate.validation.HibernateDomainClassValidator.cascadeValidationToMany(HibernateDomainClassValidator.java:90)
	at org.grails.validation.GrailsDomainClassValidator.cascadeToAssociativeProperty(GrailsDomainClassValidator.java:134)
	at org.grails.validation.GrailsDomainClassValidator.validate(GrailsDomainClassValidator.java:90)
	at org.grails.orm.hibernate.AbstractHibernateGormInstanceApi.save(AbstractHibernateGormInstanceApi.groovy:122)
	at org.grails.datastore.gorm.GormInstanceApi.save(GormInstanceApi.groovy:116)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.save(GormEntity.groovy:98)
	at nested.association.validation.BusinessSpec.$tt__$spock_feature_0_0(BusinessSpec.groovy:20)
	at nested.association.validation.BusinessSpec.invalid business has errors_closure1(BusinessSpec.groovy)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at grails.transaction.GrailsTransactionTemplate$1.doInTransaction(GrailsTransactionTemplate.groovy:70)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at grails.transaction.GrailsTransactionTemplate.executeAndRollback(GrailsTransactionTemplate.groovy:67)
	at nested.association.validation.BusinessSpec.invalid business has errors(BusinessSpec.groovy)
```

[Example grails 3.2.9/GORM 6.1.2 app](https://github.com/dpcasady/nested-association-validation) that demonstrates the issue. Run the integration tests and you should see the failures.

**Comment by graemerocher** [comment]
Seems to be a bug in `grails-validation` works fine with the GORM `grails-datastore-gorm-validation` module.

**Comment by dpcasady** [comment]
Thanks for looking into it and getting a fix together!
