### ISSUE TITLE
6.1.2 - id generator: "sequence" prevents entity from being persisted

### ISSUE THREAD

**Issue by zyro23** [grails/grails-data-mapping#927]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. run sample app
2. app will fail to start because the assertion in BootStrapService fails
3. change `gormVersion` from `6.1.2.RELEASE` to `6.1.1.RELEASE` in `gradle.properties`
4. run sample app again
5. app starts, code works with gorm-6.1.1

### Expected Behaviour

sample app should work with gorm-6.1.1 and 6.1.2 (see `BootStrap`)

```groovy
package myapp

import grails.gorm.transactions.Transactional

@Transactional
class BootStrapService {

	void init() {
		new Dummy(name: "dummy").save()
		assert Dummy.list()
	}

}
```

### Actual Behaviour

gorm-6.1.1 works, gorm-6.1.2 fails:

```
:bootRun
2017-04-29 14:04:52.231 ERROR --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.codehaus.groovy.runtime.powerassert.PowerAssertionError: assert Dummy.list()
             |
             []
	at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:404)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:650)
	at myapp.BootStrapService.$tt__init(BootStrapService.groovy:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:925)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:908)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:76)
	at myapp.BootStrapService$_init_closure1.doCall(BootStrapService.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
	at groovy.lang.Closure.call(Closure.java:414)
	at myapp.BootStrapService$_init_closure1.call(BootStrapService.groovy)
	at groovy.lang.Closure.call(Closure.java:430)
	at myapp.BootStrapService$_init_closure1.call(BootStrapService.groovy)
	at grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)
	at myapp.BootStrapService.init(BootStrapService.groovy)
	at myapp.BootStrapService$init.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at myapp.BootStrap$_closure1.doCall(BootStrap.groovy:8)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

### Environment Information

- **Operating System**: win x64
- **GORM Version:** `6.1.2.RELEASE` / `6.1.1.RELEASE`
- **Grails Version (if using Grails):** `3.2.9`
- **JDK Version:** oracle 8u121

### Example Application

will be referenced in a minute

**Comment by zyro23** [comment]
seems we have a "workaround" available. app works with gorm-6.1.2 using the new mapping builder:

instead of
```groovy
static mapping = {
    id generator: "sequence"
}
```
using this works:
```groovy
static mapping = {
    orm {
        id {
            generator "sequence"
        }
    }
}
```

**Comment by zyro23** [comment]
deleted my last comment - workaround does not work. i had the syntax of the new orm mapping builder wrong so it was ignored, thats why i thought it works. so the issue is not related to using old/new orm dsl syntax.

**Comment by zyro23** [comment]
after seeing grails/grails-core#10615, i took another look at the 6.1.2 changes related to flush mode.

flush mode handling seems to be the cause for the behavior described above,

adding `flush: true` to the save operations makes the sample app start.

also, setting
```yml
hibernate:
  flush:
    mode: AUTO
```
(`application.yml`) makes the sample app work with gorm-6.1.2.

ref. https://github.com/grails/grails-data-mapping/commits/v6.1.2/grails-datastore-gorm-hibernate-core/src/main/groovy/org/grails/orm/hibernate/connections/HibernateConnectionSourceSettings.groovy

question: does gorm `@Transactional` not behave like the spring pendant, i.e. switching the sessions flush mode to `AUTO` inside a transaction regardless of the hibernate configuration (used outside of transactions)?

**Comment by zyro23** [comment]
also note that setting the flush mode to `AUTO` works up to hibernate-5.1.x.

with hibernate-5.2.x a new config setting was introduced: `hibernate.allow_update_outside_transaction`
* https://github.com/hibernate/hibernate-orm/blob/5.2.10/hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java#L1602
* https://github.com/hibernate/hibernate-orm/blob/5.2.10/hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryBuilderImpl.java#L746

that defaults to false and has to be enabled explicitly, or else an exception is thrown immediately when going to `http://localhost:8080`:
```
javax.persistence.TransactionRequiredException: no transaction is in progress
	at org.hibernate.internal.SessionImpl.checkTransactionNeeded(SessionImpl.java:3450)
	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1418)
	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1414)
	at org.grails.orm.hibernate5.support.GrailsOpenSessionInViewInterceptor.postHandle(GrailsOpenSessionInViewInterceptor.java:68)
	at org.springframework.web.servlet.handler.WebRequestHandlerInterceptorAdapter.postHandle(WebRequestHandlerInterceptorAdapter.java:64)
	at org.springframework.web.servlet.HandlerExecutionChain.applyPostHandle(HandlerExecutionChain.java:152)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:970)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
```

**Comment by graemerocher** [comment]
No in Grails it doesn't work like that, since setting the flush mode to `AUTO` can result in poor read performance since the behaviour of `AUTO` is to always execute a `flush()` before every query

**Comment by graemerocher** [comment]
Also I don't think it is the right thing to do to enable `hibernate.allow_update_outside_transaction` since you should never perform write operations outside of a transaction. So we would be encouraging bad practise by enabling that setting

**Comment by zyro23** [comment]
ok. then it sounds this is all by design. feel free to close. but please be aware that if gorm does not set the flush mode to `AUTO` inside transactions, that means querying for non-flushed entities will fail if the saved entity does need a flush (e.g. if associations are involved or if using `id generator: "sequence"`):

```groovy
@Transactional
class MyService {

    void doIt() {
        // a successful save, but not flushed explicitly
        new Dummy(name: "dummy").save()
        // will fail (Dummy uses id generator: "sequence")
        assert Dummy.list()
    }

}
```

**Comment by graemerocher** [comment]
Yes we are of that, and if that is a problem for you in your application you can configure the default flush mode in `application.yml`

**Comment by zyro23** [comment]
got it
