### ISSUE TITLE
findAllWithSql(String, Map) with arguments seems to conflict with findAll dynamic finder

### ISSUE THREAD

**Issue by zyro23** [grails/grails-data-mapping#948]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. run sample app
2. exception in BootStrap

### Expected Behaviour

startup without errors

### Actual Behaviour

```
org.hibernate.QueryException: could not resolve property: withSql of: myapp.Dummy
	at org.hibernate.persister.entity.AbstractPropertyMapping.propertyException(AbstractPropertyMapping.java:62)
	at org.hibernate.persister.entity.AbstractPropertyMapping.toType(AbstractPropertyMapping.java:56)
	at org.hibernate.persister.entity.AbstractEntityPersister.getSubclassPropertyTableNumber(AbstractEntityPersister.java:1831)
	at org.hibernate.persister.entity.BasicEntityPropertyMapping.toColumns(BasicEntityPropertyMapping.java:46)
	at org.hibernate.persister.entity.AbstractEntityPersister.toColumns(AbstractEntityPersister.java:1806)
	at org.hibernate.loader.criteria.CriteriaQueryTranslator.getColumns(CriteriaQueryTranslator.java:510)
	at org.hibernate.loader.criteria.CriteriaQueryTranslator.findColumns(CriteriaQueryTranslator.java:525)
	at org.hibernate.criterion.SimpleExpression.toSqlString(SimpleExpression.java:66)
	at org.hibernate.loader.criteria.CriteriaQueryTranslator.getWhereCondition(CriteriaQueryTranslator.java:400)
	at org.hibernate.loader.criteria.CriteriaJoinWalker.<init>(CriteriaJoinWalker.java:106)
	at org.hibernate.loader.criteria.CriteriaJoinWalker.<init>(CriteriaJoinWalker.java:75)
	at org.hibernate.loader.criteria.CriteriaLoader.<init>(CriteriaLoader.java:80)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1773)
	at org.hibernate.internal.CriteriaImpl.list(CriteriaImpl.java:363)
	at org.grails.orm.hibernate.query.AbstractHibernateQuery.listForCriteria(AbstractHibernateQuery.java:716)
	at org.grails.orm.hibernate.query.AbstractHibernateQuery.list(AbstractHibernateQuery.java:706)
	at org.grails.datastore.gorm.finders.FindAllByFinder.invokeQuery(FindAllByFinder.java:54)
	at org.grails.datastore.gorm.finders.FindAllByFinder$1.doInSession(FindAllByFinder.java:48)
	at org.grails.datastore.mapping.core.DatastoreUtils.execute(DatastoreUtils.java:319)
	at org.grails.datastore.gorm.finders.AbstractFinder.execute(AbstractFinder.java:42)
	at org.grails.datastore.gorm.finders.FindAllByFinder.doInvokeInternal(FindAllByFinder.java:45)
	at org.grails.datastore.gorm.finders.DynamicFinder.invoke(DynamicFinder.java:252)
	at org.grails.datastore.gorm.finders.DynamicFinder.invoke(DynamicFinder.java:390)
	at org.grails.datastore.gorm.finders.FinderMethod$invoke$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:141)
	at org.grails.datastore.gorm.GormStaticApi.methodMissing(GormStaticApi.groovy:172)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.staticMethodMissing(GormEntity.groovy:757)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper$staticMethodMissing$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:141)
	at myapp.Dummy.staticMethodMissing(Dummy.groovy)
	at myapp.Dummy$staticMethodMissing.callStatic(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:56)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:194)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:214)
	at myapp.Dummy.$static_methodMissing(Dummy.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaClassImpl.invokeStaticMissingMethod(MetaClassImpl.java:1504)
	at groovy.lang.MetaClassImpl.invokeStaticMethod(MetaClassImpl.java:1492)
	at org.codehaus.groovy.runtime.callsite.StaticMetaClassSite.call(StaticMetaClassSite.java:53)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at myapp.BootStrap$_closure1.doCall(BootStrap.groovy:6)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

### Environment Information

- **Operating System**: win x64
- **GORM Version:** 6.1.3
- **Grails Version (if using Grails):** 3.2.9
- **JDK Version:** oracle 8u112

### Example Application

- will be referenced in a minute

**Comment by graemerocher** [comment]
You have to implement `HibernateEntity`

**Comment by zyro23** [comment]
added `implements HibernateEntity<Dummy>` but same exception.

i saw that `HibernateEntity` does only contain the `findWithSql(String)` methods while the ones with a second `Map` parameter are only in `AbstractHibernateGormStaticApi`.

if adding those signatures to `HibernateEntity` would fix this, consider this a feature request.

reopening would be kind. not allowed to do that. thank you!

**Comment by graemerocher** [comment]
Note that only that signature is really needed since if you pass a gstring it will be escaped automatically, so there is no need to pass a map

**Comment by zyro23** [comment]
the map is not for the query parameters but for the additional args like `[max: 10, sort: "name"]`

**Comment by graemerocher** [comment]
sure but you would have to pass those values in manually anyway into the raw SQL query

**Comment by zyro23** [comment]
agreed regarding `sort` and `order` - those can/will be handled manually as `ORDER BY ${mySort} ${myOrder}` (or similar - was not the best example..).

it is especially about `max` and `offset` which are mapped to `org.hibernate.Query.setMaxResults(int)` and `org.hibernate.Query.setFirstResult(int)`.
we currently like those to stay database-agnostic (i.e. legacy mssql `TOP x` vs. h2 `LIMIT x` for unit testing).
hibernate takes care of that even for a `NativeQuery` without having to write that sql part explicitly.
