### ISSUE TITLE
GORM 6 PersistentEntityValidator.validate() problem when used inside pure SpringBoot app

### ISSUE THREAD

**Issue by hugheba** [grails/grails-data-mapping#970]
### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Configure GORM 6 in a SpringBoot application as per http://gorm.grails.org/latest/hibernate/manual/index.html#outsideGrails
2. Create a domain class and try to do an insert with it.

### Expected Behaviour

GORM should insert a new record with no error.

### Actual Behaviour

Failure happens when calling Domain.save() with the error below.

`java.lang.IllegalArgumentException: Argument [demo.domain.Hit : (unsaved)] is not an instance of [class demo.domain.Hit] which this validator is configured for
	at grails.gorm.validation.PersistentEntityValidator.validate(PersistentEntityValidator.groovy:60) ~[grails-datastore-gorm-validation-6.1.4.RELEASE.jar:na]
	at org.grails.orm.hibernate.AbstractHibernateGormInstanceApi.save(AbstractHibernateGormInstanceApi.groovy:123) ~[grails-datastore-gorm-hibernate-core-6.1.4.RELEASE.jar:na]
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.save(GormEntity.groovy:152) ~[grails-datastore-gorm-6.1.4.RELEASE.jar:na]
	at org.grails.datastore.gorm.GormEntity$Trait$Helper$save.call(Unknown Source) ~[na:na]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) ~[groovy-all-2.4.11.jar:2.4.11]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) ~[groovy-all-2.4.11.jar:2.4.11]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133) ~[groovy-all-2.4.11.jar:2.4.11]
	at demo.domain.Hit.save(Hit.groovy) ~[classes/:na]
	at demo.service.HitServiceImpl.addHit(HitServiceImpl.groovy:15) ~[classes/:na]`

### Environment Information

- **Operating System**: Mac OS X 10.12.5
- **GORM Version:** GORM 6.1.4
- **Grails Version (if using Grails): NA
- **JDK Version:** 1.8.0_131

### Example Application

Here is an example application

Clone project and run `./gradlew bootRun`

- https://github.com/hugheba/springboot-gorm6/

**Comment by graemerocher** [comment]
This seems to be a problem with Spring `devtools`.  The check here fails because the same class is loaded by 2 different class loaders. One if the system class loader and the other is devtools' RestartClassLoader.

It is not clear to me why Spring Boot DevTools is loading the same classes in multiple class loaders. Seems like a bug in Boot.

Removing the `devtools` dependency from `build.gradle` works around the issue.
