### ISSUE TITLE
Unique validator does not use current Tenant

### ISSUE THREAD

**Issue by kayr** [grails/grails-data-mapping#987]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce
Given a domain...
```groovy
class Vehicle implements MultiTenant<Vehicle> { 
    String model
    Integer year
    static constraints = {
        model blank:false, unique: true//make vehicle model unique
    }
}
```

And the following datasource config
```yml
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    #do not create the default datasource tables
    dbCreate: none
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE

dataSources:
    ford:
      dbCreate: create-drop
      url: jdbc:h2:mem:fordDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    audi:
      dbCreate: create-drop
      url: jdbc:h2:mem:audiDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
```
if you run this code in the main Application class
```groovy
......
class Application extends GrailsAutoConfiguration implements ApplicationRunner {
......
    @Override
    @Transactional
    void run(ApplicationArguments args) throws Exception { 
        Tenants.eachTenant { t ->
            println("Tenant $t")
            new Vehicle(model: "$t - Explorer", year: 2017).save(failOnError: true, flush: true)

        }
    }
}
```
### Expected Behaviour

App should startup with no problem with two vehicles inserted in the two databases

### Actual Behaviour

I get a Table not found Exception with the following stacktrace
```
Caused by: org.h2.jdbc.JdbcSQLException: Table "VEHICLE" not found; SQL statement:
select this_.id as y0_ from vehicle this_ where this_.model=? limit ? [42102-195]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
.......
	org.springframework.jdbc.datasource.LazyConnectionDataSourceProxy$LazyConnectionInvocationHandler.invoke(LazyConnectionDataSourceProxy.java:376)
.....	
org.springframework.jdbc.datasource.TransactionAwareDataSourceProxy$TransactionAwareInvocationHandler.invoke(TransactionAwareDataSourceProxy.java:240)
	org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:146)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:172)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:148)
	at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1934)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1903)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1881)
	at org.hibernate.loader.Loader.doQuery(Loader.java:925)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:342)
	at org.hibernate.loader.Loader.doList(Loader.java:2622)
	at org.hibernate.loader.Loader.doList(Loader.java:2605)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2434)
	at org.hibernate.loader.Loader.list(Loader.java:2429)
	at org.hibernate.loader.criteria.CriteriaLoader.list(CriteriaLoader.java:109)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1787)
	at org.hibernate.internal.CriteriaImpl.list(CriteriaImpl.java:363)
	at org.grails.orm.hibernate.query.AbstractHibernateQuery.singleResultViaListCall(AbstractHibernateQuery.java:801)
	at org.grails.orm.hibernate.query.AbstractHibernateQuery.singleResult(AbstractHibernateQuery.java:791)
	at grails.gorm.DetachedCriteria$_get_closure1.doCall(DetachedCriteria.groovy:115)
org.grails.datastore.gorm.GormStaticApi$_withDatastoreSession_closure22.doCall(GormStaticApi.groovy:836)
	at org.grails.datastore.mapping.core.DatastoreUtils.execute(DatastoreUtils.java:319)
	at org.grails.datastore.gorm.AbstractDatastoreApi.execute(AbstractDatastoreApi.groovy:40)
	at org.grails.datastore.gorm.GormStaticApi.withDatastoreSession(GormStaticApi.groovy:835)
	at grails.gorm.DetachedCriteria.withPopulatedQuery(DetachedCriteria.groovy:737)
	at grails.gorm.DetachedCriteria.get(DetachedCriteria.groovy:114)
	at grails.gorm.DetachedCriteria.get(DetachedCriteria.groovy:113)
	at org.grails.datastore.gorm.validation.constraints.builtin.UniqueConstraint.processValidate(UniqueConstraint.groovy:75)
	at org.grails.datastore.gorm.validation.constraints.AbstractConstraint.validate(AbstractConstraint.java:88)
	at grails.gorm.validation.DefaultConstrainedProperty.validate(DefaultConstrainedProperty.groovy:601)
	at grails.gorm.validation.PersistentEntityValidator.validatePropertyWithConstraint(PersistentEntityValidator.groovy:296)
	at grails.gorm.validation.PersistentEntityValidator.validate(PersistentEntityValidator.groovy:73)
	at org.grails.orm.hibernate.AbstractHibernateGormInstanceApi.save(AbstractHibernateGormInstanceApi.groovy:123)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.save(GormEntity.groovy:151)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper$save.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at example.Vehicle.save(Vehicle.groovy)
	at example.Application$__tt__application_run_closure2.doCall(Application.groovy:23)
	at example.Application$__tt__application_run_closure2.call(Application.groovy)
	at grails.gorm.multitenancy.Tenants$_withId_closure1$_closure3.doCall(Tenants.groovy:229)
	at grails.gorm.multitenancy.Tenants$_withId_closure1$_closure3.call(Tenants.groovy)
	at org.grails.orm.hibernate.GrailsHibernateTemplate$1.doInHibernate(GrailsHibernateTemplate.java:152)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.doExecute(GrailsHibernateTemplate.java:298)
	... 50 common frames omitted
```

### Environment Information

- **GORM Version:** 6.1.6-RELEASE
- **Grails Version (if using Grails):**  3.3.0
- **JDK Version:** Java 8

### Example Application
See a fork of the multi-tenant example 
https://github.com/kayr/database-per-tenant/tree/tenant-validation-error

**Comment by kayr** [comment]
Should have searched more before posting this...
Seems like a duplicate of grails/grails-core#10481?

**Comment by graemerocher** [comment]
Yes it duplicates that issue. Hard one to fix unfortunately

**Comment by kayr** [comment]
unfortunate :(. Let me close this then.
