### ISSUE TITLE
MongoDB aggregates are not working anymore with Gorm 6.1.6.RELEASE

### ISSUE THREAD

**Issue by NukeToad** [grails/grails-data-mapping#990]
After upgrading and application fron Grails 3.2.11 (Gorm 6.0.9) to Grails 3.3.0 (Gorm 6.1.6) all aggregates queries stopped working.

For example, this query is not working anymore:

```
Project.aggregate([
                        ['$match': ['reportingYear': 2015, 'flowType': '10']],
                        ['$unwind': '$transactions'],
                        ['$group': ['_id': '$transactions.type', 'usdTotalValue': ['$sum': '$transactions.usdValue']]],
                ])
```

the resulting exception is 

java.util.NoSuchElementException: Cannot access first() element from an empty List
	at org.grails.datastore.bson.codecs.CodecExtensions.getBsonConverter(CodecExtensions.groovy:235)
	at org.grails.datastore.bson.codecs.BsonPersistentEntityCodec.readSchemaless(BsonPersistentEntityCodec.groovy:371)
	at org.grails.datastore.bson.codecs.BsonPersistentEntityCodec.decode(BsonPersistentEntityCodec.groovy:126)
	at com.mongodb.operation.CommandResultArrayCodec.decode(CommandResultArrayCodec.java:52)
	at com.mongodb.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:53)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:84)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:41)
	at org.bson.codecs.configuration.LazyCodec.decode(LazyCodec.java:47)
	at org.bson.codecs.BsonDocumentCodec.readValue(BsonDocumentCodec.java:101)
	at com.mongodb.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:56)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:84)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:41)
	at com.mongodb.connection.ReplyMessage.<init>(ReplyMessage.java:57)
	at com.mongodb.connection.CommandProtocol.getResponseDocument(CommandProtocol.java:139)
	at com.mongodb.connection.CommandProtocol.execute(CommandProtocol.java:118)
	at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:168)
	at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:289)
	at com.mongodb.connection.DefaultServerConnection.command(DefaultServerConnection.java:176)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:216)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:207)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:113)
	at com.mongodb.operation.AggregateOperation$1.call(AggregateOperation.java:257)
	at com.mongodb.operation.AggregateOperation$1.call(AggregateOperation.java:253)
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:431)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:404)
	at com.mongodb.operation.AggregateOperation.execute(AggregateOperation.java:253)
	at com.mongodb.operation.AggregateOperation.execute(AggregateOperation.java:67)
	at com.mongodb.Mongo.execute(Mongo.java:836)
	at com.mongodb.Mongo$2.execute(Mongo.java:823)
	at com.mongodb.OperationIterable.iterator(OperationIterable.java:47)
	at com.mongodb.AggregateIterableImpl.iterator(AggregateIterableImpl.java:123)
	at org.grails.datastore.gorm.mongo.api.MongoStaticApi.aggregate_closure12(MongoStaticApi.groovy:219)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at org.grails.datastore.gorm.GormStaticApi.withSession_closure21(GormStaticApi.groovy:824)
	at groovy.lang.Closure.call(Closure.java:414)
	at org.grails.datastore.mapping.core.DatastoreUtils.execute(DatastoreUtils.java:319)
	at org.grails.datastore.gorm.AbstractDatastoreApi.execute(AbstractDatastoreApi.groovy:40)
	at org.grails.datastore.gorm.GormStaticApi.withSession(GormStaticApi.groovy:823)
	at org.grails.datastore.gorm.mongo.api.MongoStaticApi.aggregate(MongoStaticApi.groovy:200)
	at grails.mongodb.MongoEntity$Trait$Helper.aggregate(MongoEntity.groovy:234)
	at grails.mongodb.MongoEntity$Trait$Helper.aggregate(MongoEntity.groovy:233)
	at eu.europa.ec.aiddatahubimport.aggregates.AggregatesGeneratorService._tt__testAggregates_closure36(AggregatesGeneratorService.groovy:35)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at org.grails.datastore.gorm.mongo.api.MongoStaticApi.withCollection_closure8(MongoStaticApi.groovy:156)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at org.grails.datastore.gorm.GormStaticApi.withSession_closure21(GormStaticApi.groovy:824)
	at groovy.lang.Closure.call(Closure.java:414)
	at org.grails.datastore.mapping.core.DatastoreUtils.execute(DatastoreUtils.java:319)
	at org.grails.datastore.gorm.AbstractDatastoreApi.execute(AbstractDatastoreApi.groovy:40)
	at org.grails.datastore.gorm.GormStaticApi.withSession(GormStaticApi.groovy:823)
	at org.grails.datastore.gorm.mongo.api.MongoStaticApi.withCollection(MongoStaticApi.groovy:148)
	at ...

if I remove the group stage

```
Project.aggregate([
                        ['$match': ['reportingYear': 2015, 'flowType': '10']],
                        ['$unwind': '$transactions']
                ])
```

 the exception is different:

org.bson.BsonInvalidOperationException: readStartArray can only be called when CurrentBSONType is ARRAY, not when CurrentBSONType is DOCUMENT.
	at org.bson.AbstractBsonReader.verifyBSONType(AbstractBsonReader.java:692)
	at org.bson.AbstractBsonReader.checkPreconditions(AbstractBsonReader.java:724)
	at org.bson.AbstractBsonReader.readStartArray(AbstractBsonReader.java:445)
	at org.grails.datastore.bson.codecs.decoders.EmbeddedCollectionDecoder.decode(EmbeddedCollectionDecoder.groovy:36)
	at org.grails.datastore.bson.codecs.BsonPersistentEntityCodec.decode(BsonPersistentEntityCodec.groovy:121)
	at com.mongodb.operation.CommandResultArrayCodec.decode(CommandResultArrayCodec.java:52)
	at com.mongodb.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:53)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:84)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:41)
	at org.bson.codecs.configuration.LazyCodec.decode(LazyCodec.java:47)
	at org.bson.codecs.BsonDocumentCodec.readValue(BsonDocumentCodec.java:101)
	at com.mongodb.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:56)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:84)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:41)
	at com.mongodb.connection.ReplyMessage.<init>(ReplyMessage.java:57)
	at com.mongodb.connection.CommandProtocol.getResponseDocument(CommandProtocol.java:139)
	at com.mongodb.connection.CommandProtocol.execute(CommandProtocol.java:118)
	at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:168)
	at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:289)
	at com.mongodb.connection.DefaultServerConnection.command(DefaultServerConnection.java:176)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:216)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:207)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:113)
	at com.mongodb.operation.AggregateOperation$1.call(AggregateOperation.java:257)
	at com.mongodb.operation.AggregateOperation$1.call(AggregateOperation.java:253)
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:431)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:404)
	at com.mongodb.operation.AggregateOperation.execute(AggregateOperation.java:253)
	at com.mongodb.operation.AggregateOperation.execute(AggregateOperation.java:67)
	at com.mongodb.Mongo.execute(Mongo.java:836)
	at com.mongodb.Mongo$2.execute(Mongo.java:823)
	at com.mongodb.OperationIterable.iterator(OperationIterable.java:47)
	at com.mongodb.AggregateIterableImpl.iterator(AggregateIterableImpl.java:123)
	at org.grails.datastore.gorm.mongo.api.MongoStaticApi.aggregate_closure12(MongoStaticApi.groovy:219)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at org.grails.datastore.gorm.GormStaticApi.withSession_closure21(GormStaticApi.groovy:824)
	at groovy.lang.Closure.call(Closure.java:414)
	at org.grails.datastore.mapping.core.DatastoreUtils.execute(DatastoreUtils.java:319)
	at org.grails.datastore.gorm.AbstractDatastoreApi.execute(AbstractDatastoreApi.groovy:40)
	at org.grails.datastore.gorm.GormStaticApi.withSession(GormStaticApi.groovy:823)
	at org.grails.datastore.gorm.mongo.api.MongoStaticApi.aggregate(MongoStaticApi.groovy:200)
	at grails.mongodb.MongoEntity$Trait$Helper.aggregate(MongoEntity.groovy:234)
	at 

If i remove the unwind phase 

```
Project.aggregate([
                        ['$match': ['reportingYear': 2015, 'flowType': '10']]
                ])
```

it works as expected.

### Environment Information
- **Operating System**: Windows 7 
- **GORM Version:** 6.1.6
- **Grails Version:** 3.3.0
- **JDK Version:** 1.8.0_121

**Comment by graemerocher** [comment]
Please provide an example that reproduces the issue

**Comment by NukeToad** [comment]
[TestAggregates.zip](https://github.com/grails/grails-data-mapping/files/1248341/TestAggregates.zip)

Hi, I created a simple Grails app to reproduce the problem. It connects to a local MongoDB instance.
I added 3 simple integration tests to reproduce the described behaviors, one working a 2 failing.

**Comment by graemerocher** [comment]
Thanks will take a look

**Comment by graemerocher** [comment]
The above commit fixes the original report. Removing the `group` stage causes invalid BSON to be returned which cannot be decoded so that is not a bug. See the docs for unwind for more info https://docs.mongodb.com/manual/reference/operator/aggregation/unwind/
