### ISSUE TITLE
Cycle while creating a Custom Tenant Resolver Using springSecurityService 

### ISSUE THREAD

**Issue by sdelamo** [grails/grails-data-mapping#999]
## Introduction 

Trying to create a Custom Tenant Resolver which uses the `springSecurityService` of [Spring Security Core Plugin](https://grails-plugins.github.io/grails-spring-security-core/latest/) I get an error because: 
_The dependencies of some of the beans in the application context form a cycle_.

### Steps to Reproduce

Define a new bean which will be used as custom resolver: 

```
import demo.CurrentUserTenantResolver
beans = {
    CurrentUserTenantResolver(CurrentUserTenantResolver)
}
```

Create the `src/main/groovy/demo/CurrentUserTenantResolver.groovy` class: 

```
package demo

import grails.plugin.springsecurity.SpringSecurityService
import groovy.transform.CompileDynamic
import groovy.transform.CompileStatic
import org.grails.datastore.mapping.multitenancy.TenantResolver
import org.grails.datastore.mapping.multitenancy.exceptions.TenantNotFoundException
import org.springframework.beans.factory.annotation.Autowired

@CompileStatic
class CurrentUserTenantResolver implements TenantResolver {

    @Autowired
    SpringSecurityService springSecurityService


    @Override
    Serializable resolveTenantIdentifier() throws TenantNotFoundException {

        String username = loggedUsername()
        if ( username ) {
            return username
        }
        throw new TenantNotFoundException("Tenant could not be resolved from Spring Security Principal")
    }

    @CompileDynamic
    String loggedUsername() {
        springSecurityService.principal?.username
    }
}
```
execute: 

`cd complete`
`./gradlew bootRun`

You will get the next error: 

```
2017-09-08 12:06:36.310 ERROR --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Destroy method on bean with name 'org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor' threw an exception

java.lang.IllegalStateException: ApplicationEventMulticaster not initialized - call 'refresh' before multicasting events via the context: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@2f162cc0: startup date [Fri Sep 08 12:06:31 CEST 2017]; root of context hierarchy
        at org.springframework.context.support.AbstractApplicationContext.getApplicationEventMulticaster(AbstractApplicationContext.java:414)
        at org.springframework.context.support.ApplicationListenerDetector.postProcessBeforeDestruction(ApplicationListenerDetector.java:97)
        at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:253)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:578)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:554)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:961)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:523)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:968)
        at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1030)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:556)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:83)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:388)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:375)
        at grails.boot.GrailsApp$run.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
        at demo.Application.main(Application.groovy:8)

2017-09-08 12:06:36.313 ERROR --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Destroy method on bean with name 'grailsApplicationPostProcessor' threw an exception

java.lang.IllegalStateException: ApplicationEventMulticaster not initialized - call 'refresh' before multicasting events via the context: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@2f162cc0: startup date [Fri Sep 08 12:06:31 CEST 2017]; root of context hierarchy
        at org.springframework.context.support.AbstractApplicationContext.getApplicationEventMulticaster(AbstractApplicationContext.java:414)
        at org.springframework.context.support.ApplicationListenerDetector.postProcessBeforeDestruction(ApplicationListenerDetector.java:97)
        at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:253)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:578)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:554)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:961)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:523)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:968)
        at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1030)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:556)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:83)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:388)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:375)
        at grails.boot.GrailsApp$run.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
        at demo.Application.main(Application.groovy:8)

2017-09-08 12:06:36.314 ERROR --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Destroy method on bean with name 'org.springframework.boot.autoconfigure.internalCachingMetadataReaderFactory' threw an exception

java.lang.IllegalStateException: ApplicationEventMulticaster not initialized - call 'refresh' before multicasting events via the context: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@2f162cc0: startup date [Fri Sep 08 12:06:31 CEST 2017]; root of context hierarchy
        at org.springframework.context.support.AbstractApplicationContext.getApplicationEventMulticaster(AbstractApplicationContext.java:414)
        at org.springframework.context.support.ApplicationListenerDetector.postProcessBeforeDestruction(ApplicationListenerDetector.java:97)
        at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:253)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:578)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:554)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:961)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:523)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:968)
        at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1030)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:556)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:83)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:388)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:375)
        at grails.boot.GrailsApp$run.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
        at demo.Application.main(Application.groovy:8)

2017-09-08 12:06:36.332 ERROR --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

The dependencies of some of the beans in the application context form a cycle:

   methodValidationPostProcessor defined in class path resource [org/springframework/boot/autoconfigure/validation/ValidationAutoConfiguration.class]
      ↓
   hibernateDatastoreServiceRegistry
┌─────┐
|  hibernateDatastore
↑     ↓
|  hibernateConnectionSourceFactory
↑     ↓
|  CurrentUserTenantResolver (field private grails.plugin.springsecurity.SpringSecurityService demo.CurrentUserTenantResolver.springSecurityService)
↑     ↓
|  springSecurityCoreSpringSecurityService
```

### Expected Behaviour

I expected the bean to be loaded correctly.

### Actual Behaviour

An error occcurs when trying to load the custom resolver bean. 

### Environment Information

- **Operating System**: MacOs
- **GORM Version:** 6.1.6
- **Grails Version (if using Grails):** 3.3.0
- **JDK Version:** 1.8.0_121

### Example Application

Clone branch `current-user-with-spring-security-service` of Github `grails-guides/grails-custom-security-tenant-resolvergrails-guides/grails-custom-security-tenant-resolver` repository:

https://github.com/grails-guides/grails-custom-security-tenant-resolver/tree/current-user-with-spring-security-service

The Grails app with the issue is in the `complete` folder.

**Comment by graemerocher** [comment]
probably because as the error says `springSecurityCoreSpringSecurityService` depends on the `datastore` bean and the `datastore` bean depends the tenant resolver which depends on `springSecurityCoreSpringSecurityService` hence the cycle

**Comment by Anthony-ESP** [comment]
Having a similar issue, did you manage to find the solution to breaking your cycle?

**Comment by panksoni** [comment]
Having exactly same issue. Any solution yet

**Comment by jeffbrown** [comment]
I am not 100% sure this is the same root cause but we have a scenario leading to the following:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

The dependencies of some of the beans in the application context form a cycle:

   pluginManagerPostProcessor
      ↓
   org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration
      ↓
   org.springframework.cache.config.internalCacheAdvisor
      ↓
   org.springframework.cache.annotation.AnnotationCacheOperationSource#0
      ↓
   authorizationAttributeSourceAdvisor
      ↓
   shiroSecurityManager
      ↓
   shiroDbRealmWrapper
      ↓
   shiroDbRealm
      ↓
   securityService
┌─────┐
|  hibernateDatastore
↑     ↓
|  hibernateConnectionSourceFactory
↑     ↓
|  hibernateDatastoreServiceRegistry
└─────┘
```

That is with GORM 6.1.7, Hibernate 5.1.9 and Grails 3.2.11.

**Comment by jeffbrown** [comment]
The project related to the error I just pasted above also contains the following:

```
    compile "org.grails.plugins:spring-security-core:3.1.2"
    compile "org.grails.plugins:spring-security-rest:2.0.0.M2"
```

**Comment by jameskleeh** [comment]
@sdelamo This could be avoided by injecting the service lazily

`@Autowired @Lazy SpringSecurityService springSecurityService`

**Comment by abhaygoel** [comment]
@jameskleeh Injecting the service lazily also does not help. Please advice.

**Comment by graemerocher** [comment]
The problem is pretty simple. If you try and inject `SpringSecurityService` into the `TenantResolver` that creates an issue because `SpringSecurityService` depends on `HibernateDatastore` which depends on `TenantResolver` which now depends on `SpringSecurityService` hence you have a cycle. So you have to break that cycle.

There are several ways to do that. You could use `@Lazy` as suggested, alternatively you could use `ApplicationContextAware` and call `ctx.getBean("springSecurityService")` inside the `TenantResolver` so that you are not creating a cycle. 

Really there is nothing we can do about this at the the GORM level to fix the issue

**Comment by abhaygoel** [comment]
Thanks Graeme. This helps. Pardon my ignorance.

**Comment by sdelamo** [comment]
I have added an example of custom tenant resolver by logged in user http://guides.grails.org/grails-custom-security-tenant-resolver/guide/index.html#tenantResolverByUser

**Comment by jeffbrown** [comment]
@abhaygoel It looks like `@Lazy` does work for me.  When it didn't work for you, is it possible you were using `groovy.lang.Lazy` instead of `org.springframework.context.annotation.Lazy`?
